### ISSUE TITLE
Night Vision does not function

### ISSUE THREAD

**Issue by novasolarius** [CyclopsMC/EverlastingAbilities#1]
There's painfully little else I can tell you. All other abilities I have tested work fine, but night vision will not give me the buff. Shame, as NV and water breathing are a brilliant combination when playing with underground oceans.

MC: 1.10.2
Forge: 1.10.2-12-18-1-2049
Liteloader: 1.10.2-00-SNAPSHOT

**Comment by rubensworks** [comment]
Are you sure there's no other mod disabling that ability? Because I can not reproduce this.

**Comment by novasolarius** [comment]
I'll try removing mods, I guess. I'll report when I have found something.

**Comment by rubensworks** [comment]
Assuming invalid, haven't been able to reproduce this, and no other reports of this have come in.

**Comment by milano1110** [comment]
I am having the same bug, so far all of my abilities work perfectly, but Night Vision doesn't.

**Comment by milano1110** [comment]
I just tested if a Night Vision potions worked and it did.

**Comment by rubensworks** [comment]
@milano1110 Is the night vision effect active at all if you use the ability?

**Comment by milano1110** [comment]
No, unlike fire resistance which shows up at the side of my inventory, the night vision ability doesn't activate at all

**Comment by rubensworks** [comment]
@milano1110 Can you reproduce it without any other mods installed?
If not, then another mod is probably blocking the potion effect.

**Comment by milano1110** [comment]
Okay, I tested it and Night Vision works with only your mods installed. So that means there is a conflict with an other mod that prevents Night Vision from working.

**Comment by milano1110** [comment]
So after testing, I found that apparently Inventory Pets is somehow conflicting and stopping Night Vision from working. After I took it out, the Night Vision started working again. I don't why that would be a conflict, but it was.

**Comment by rubensworks** [comment]
@milano1110 Can you report it to their issue tracker and reference this issue here?
