### ISSUE TITLE
Repositionable Active Effects display

### ISSUE THREAD

**Issue by Zarepheth** [CyclopsMC/EverlastingAbilities#100]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

The abilities which display their active effects in the upper left corner of the screen are conflicting with other mods that also put UI elements in the upper left corner of the screen (specifically Thaumcraft).

It would be good if we could reposition those elements. As four corners, the center top and center bottom are already populated with content from the game itself or other mods, free positioning which allows us to offset the display from a particular corner or edge would be best.

Since I only see abilities that directly affect my own character, and I see negative effects in that list when I'm attacked by certain mobs, I'm entirely sure whether Everlasting Abilities is displaying those effects or some other mod...

**Comment by rubensworks** [comment]
You are talking about Vanilla's potion effect display. This is not something EA adds. Just applying vanilla potions on yourself will have the same effect.

It is out of scope for this mod to customize guis of Vanilla, sorry.

**Comment by Zarepheth** [comment]
Thanks for pointing out the source. 
I’ve so many installed mods that I don’t always know the source of various features on my screen.
