### ISSUE TITLE
On a brand new world, you get experience and a random effect

### ISSUE THREAD

**Issue by jinkhya** [CyclopsMC/EverlastingAbilities#101]
#### Issue type:

- :bug: Bug

____

#### Short description:

When I start a new world, I get between 9 to 14 levels of experience and if I open the ability bottle it has one random effect that I can apply to my character (I've seen night vision, strength 1, bonemeal 1 so far)

#### Steps to reproduce the problem:

Create a pack with just forge and Everlasting Abilities, start a new world.

#### Expected behaviour:

No experience and no random effect :)
____

#### Versions:

- This mod: 1.3.18
- Minecraft: 1.12
- Forge: 2759

**Comment by jinkhya** [comment]
And I think it gives you the exact amount of xp needed to apply the random effect already available in the bottle.

**Comment by rubensworks** [comment]
That's not a bug, it's a feature!

You can disable it from the config file.

**Comment by jinkhya** [comment]
Oups I'm so sorry. I did look in the configs to find something about it but didn't find it. I'll look more closely tonight. Thank you.
