### ISSUE TITLE
Some abilities stop working if daylight cycle is set to false.

### ISSUE THREAD

**Issue by PurpleHel** [CyclopsMC/EverlastingAbilities#102]
#### Issue type:

- :bug: Bug

____

#### Short description:

When doDaylightCycle is set to false, many abilities stop working, such as waterbreathing.

#### Steps to reproduce the problem:

1. Equip water breathing ability
2. Set /gamerule doDaylightCycle false
3. Go in water
4. Drown

#### Expected behaviour:

All abilities work regardless of daylight cycle setting.

____

#### Versions:

- This mod: EverlastingAbilities-1.12.2-1.3.18
- Minecraft: 1.12.2
- Forge: forge-1.12.2-14.23.5.2768-universal.jar

All mods used for testing-
 CodeChickenLib-1.12.2-3.2.2.353-universal
  CyclopsCore-1.12.2-0.11.10
  EverlastingAbilities-1.12.2-1.3.18
  jei_1.12.2-4.13.1.225
  NotEnoughItems-1.12.2-2.4.2.240-universal

**Comment by rubensworks** [comment]
It looks like @josephcsible already fixed it :-)
Will it release in a bit!
