### ISSUE TITLE
A Config option, to prevent players from taking dmg from abilities like wither and poison?

### ISSUE THREAD

**Issue by SirAron111** [CyclopsMC/EverlastingAbilities#105]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

At the moment abilities that do dmg around the player like wither and poison or even status effects like weakness always affect my friends when we use them and also our pets and friendly passive mobs making them aggressive?
Is it possible to have these abilities only affect things you actively attack? Like Appling the effect on hit? Or simply turn it off to affect friendlies?

**Comment by rubensworks** [comment]
Those effects should only apply to hostile mobs and players in different teams, does that work for you?

**Comment by SirAron111** [comment]
In my modpack „Dimension Zero“these effects applied to other players and allot of neutral and passive mobs even to summoned pets from the electro blobs wizardry mod. That’s why I asked. How are teams defined? Players in a Better questing party? Players in a FTB config Party? I think applying these effects one hit would be the best solution to stop any other modded creature or player to be affected unintentionally.

**Comment by rubensworks** [comment]
EA just uses the plain old vanilla teams: https://minecraft.gamepedia.com/Commands/team

You can configure passive mobs in the config file with the `friendlyMobs` settings.

If those things don't work for you, please let me know.

<blockquote><img src="https://d1u5p3l4wpay3k.cloudfront.net/minecraft_gamepedia/b/bc/Wiki.png?version=f7d0a27afa6ae010a5a99c80a036a9ee" width="48" align="right"><div>Minecraft Wiki</div><div><strong><a href="https://minecraft.gamepedia.com/Commands/team">Commands/team</a></strong></div></blockquote>

**Comment by SirAron111** [comment]
The team thingy works but the mobs didn’t get ignored even when added to the list (used mob id (mod:mobname))
But the problem is that in my Modpack an on the servers mostly people can’t use commands. As they aren’t op!
If I could simply set it in the config that players aren’t affected at all. And there are could be config option to not affect passives and neutrals in general only aggressive mobs. That would be ideal or simply an option to change the aoe effect of these abilities to one hit application.

**Comment by rubensworks** [comment]
Sure, it should be easy to implement support for `minecraft:player` in the config file.
