### ISSUE TITLE
Flight not working

### ISSUE THREAD

**Issue by Darkfiend009** [CyclopsMC/EverlastingAbilities#112]
Adding the flight ability is not granting flight.

1. Added the ability to the player with proper experience available.
2. Checked config file to make sure flight was enabled for the mod.
3. Ensured flying was allowed in the server properties.
4. Checked to make sure no keys needed to be bound to toggle flight on and off.
5. Tried double tapping jump to fly as if in creative.

- This mod: 1.4.0
- Minecraft: 1.12.2
- Forge: 2811

There are no crashes or logs i can provide. If you need screenshots of anything, just let me know. I'm not sure what else to try and i've searched the internet and mod spotlights for answers before posting. I thoroughly enjoy the mod! Thank you for all the work you've put into it!

**Comment by rubensworks** [comment]
Are you using any other mods? If so, please try reproducing without any other mods installed, because another mod may be blocking this.

**Comment by rubensworks** [comment]
Just tested myself, works fine in a clean environment. So there must be some other mod breaking this in your environment.
