### ISSUE TITLE
Abilities drop even when keepInventory is true

### ISSUE THREAD

**Issue by ArmandAgopian** [CyclopsMC/EverlastingAbilities#113]
#### Issue type:

- :bug: Bug

____

#### Short description:

Regardless of if I have keepInventory set to true or false, I still lose an ability.

#### Steps to reproduce the problem:

1. `/gamerule keepInventory true`
2. On death, an ability still drops.

#### Expected behaviour:

When I die, the ability should not be dropped if I set it to true.
____

#### Versions:

- This mod: 1.4.0
- Minecraft: 1.12.2
- Forge: 14.23.5.2808

**Comment by rubensworks** [comment]
This is not a bug, it's just not a feature.

You can play around with these config options to achieve what you want: `alwaysDropAbilities`, `dropAbilitiesOnPlayerDeath`.
