### ISSUE TITLE
Cant disable effect

### ISSUE THREAD

**Issue by violetkitty87** [CyclopsMC/EverlastingAbilities#114]
I found a bug while playing PO3 i have enabled fire resistance twice and now i cant get rid of it cause it is on both sides
![2019-02-28_19 38 50](https://user-images.githubusercontent.com/13909869/53608419-b2a50780-3b90-11e9-98f2-93dcbd383082.png)

**Comment by violetkitty87** [comment]
had to kill myself to remove it

**Comment by rubensworks** [comment]
You have to craft a new ability bottle, as each bottle has a limit for each ability, just like the player.
