### ISSUE TITLE
Using JEI to create teams not counting to prevent negative effects

### ISSUE THREAD

**Issue by Bioshokar** [CyclopsMC/EverlastingAbilities#115]
#### Issue type:

- :question: Question

____

#### Question:

Im not sure if its just me and my friends but we recently started a Project ozone 3 server and the negative effects still apply to each other while being in the same team

**Comment by rubensworks** [comment]
What kind of teams are you using? Are these vanilla teams?

**Comment by Bioshokar** [comment]
No sadly any of the vanilla commands for teams have been over taken by the FTB utilities teams options

**Comment by rubensworks** [comment]
Not much I can do about that then. FTB utilities should be compatible with vanilla teams. This will probably break things in other mods as well. Feel free to create an issue on their issue tracker and link back here.

**Comment by Bioshokar** [comment]
No worries we worked around it and just added players to the ignore list, i;ll do what you suggest, thank you :)
