### ISSUE TITLE
Ability Toggle

### ISSUE THREAD

**Issue by Graywaren** [CyclopsMC/EverlastingAbilities#116]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

I really enjoy this mod, but one thing I have problems with is the inability to turn abilities on and off easily at any time. I'd really love to be able to toggle abilities on and off with a hot bar or something rather than having to either have them on all the time or carry/find a bottle. This is especially desirable when having abilities causes you to starve to death while standing still/afk. I don't want to lose hunger when I'm doing nothing, but I appreciate having the cost when I'm actually using an ability. Being able to move slower than speed X or turn off jump boost in precarious situations when I want without having to go find a bottle and being able to activate the negative effects on nearby entities rather than having it always active would be extremely useful, especially since they target passive mobs.

**Comment by rubensworks** [comment]
Someone suggested this already, see #39.

**Comment by Graywaren** [comment]
Whoops, missed that in my search. My apologies.
