### ISSUE TITLE
Ability Level Stacking + Recipe + XP questions

### ISSUE THREAD

**Issue by Graywaren** [CyclopsMC/EverlastingAbilities#117]
Really enjoying this mod, however the friend I am playing with is finding things somewhat OP and would like to customize things for our game. I know we can create recipes for totems, and JEI shows that there are separate totems for each level of ability, but I'm confused about how they're implemented. In game when totems drop, you can just apply two Ability 1 totems to get level 2 of that ability and so on. Is this different if you were to when you craft them? 

The config also only allows for a set number of xp per level of applying a totem. Is there any way to set xp required for each level of ability separately and/or make it so that you cannot stack level 1 totems so that creating recipes for higher level totems can enforce a higher cost? Or to adjust the power of an ability per level?

If this is not currently possible, would like to feature request it! 

Thanks!

**Comment by rubensworks** [comment]
> you can just apply two Ability 1 totems to get level 2 of that ability and so on. Is this different if you were to when you craft them?

The totems can hold any number of abilities at any level.

> Is there any way to set xp required for each level of ability separately

Not possible atm indeed.

> make it so that you cannot stack level 1 totems so that creating recipes for higher level totems can enforce a higher cost

Not sure if I see the point of this.

> Or to adjust the power of an ability per level?

Not possible as well.

> If this is not currently possible, would like to feature request it!

Sure, these things are possible, but will require some effort to implement it. PRs are welcome! :-)

**Comment by rubensworks** [comment]
Should be possible now with the datapack functionality.
