### ISSUE TITLE
Adjustable totems strength to better balance them out.

### ISSUE THREAD

**Issue by SirAron111** [CyclopsMC/EverlastingAbilities#118]
Being able to adjust how much power the different totems give you on the stages. For example just one saturation results in you never having to eat again. Is a bit op. First lvl of saturation should just disable the hunger drain from totems next one should give the periodical extra feeding. But it should fill up the saturation fully only just barely over the food lvl

**Comment by rubensworks** [comment]
Should be possible now with the datapack functionality.
