### ISSUE TITLE
Levels whilst adding and removing abilities is inconsistent

### ISSUE THREAD

**Issue by JonaBrackenwood** [CyclopsMC/EverlastingAbilities#12]
The consistency of levels whilst adding and removing abilities is inconsistent.

As an example, I start out with 3000 xp. This gives met 40 levels (and the bar is half full).
![image](https://cloud.githubusercontent.com/assets/1567798/17836684/c6b6738e-679a-11e6-8dfb-8bf8b68740a7.png)

If I apply a glowing effect on me, I suddenly have 45 levels, whilst the xp has correctly gone down in the AE interface.
![image](https://cloud.githubusercontent.com/assets/1567798/17836687/f58be9b4-679a-11e6-91a6-d26920e0c27d.png)

Now if I put the ability back in the bottle, I have 47 levels whilst xp is back to 3000.
![image](https://cloud.githubusercontent.com/assets/1567798/17836691/249c8fec-679b-11e6-8b66-151b53f24127.png)

**Comment by rubensworks** [comment]
Thanks for reporting, will look into it.
