### ISSUE TITLE
Haste and Weakness Totems Bestowing Unfair/Unexpected Abilities

### ISSUE THREAD

**Issue by Barerock** [CyclopsMC/EverlastingAbilities#120]
Issue type: Bug

- :bug: Bug

____

**#### Short description:** The haste and weakness totems seem to add an invincibility/deflection rule to the player, preventing all types of damage except burning, drowning, and fall damage.

****
The haste totem adds a deflection rule to the player, deflecting all projectiles of any type (tested with wither, blaze, ghast, arrows, snowballs, etc.) Similar to this issue, the weakness totem disables hostiles from melee attacking the player at all instead of simply weakening the attack and/or health of enemies. The bug also occurs on a Forge server I run and happens to multiple players.

**#### Steps to reproduce the problem:**
Equip at least one of either type of totem and the effect is duplicated.

**#### Expected behaviour:**

**Expected:** I expected haste to follow its description and only give me a mining enhancement. I expected the weakness totem to decrease armor or health and the damage output of hostile mobs around me. 

____

**#### Versions:**
- This mod: 1.12.2- 1.5.0 (1.5.0)
- Minecraft: 1.12.2
- Forge: 14.23.5.2816

**Comment by rubensworks** [comment]
Can you check what happens when you just use a Haste/Weakness potion directly? Because this mod does nothing more than just applying those potion effects to the player every so often.
