### ISSUE TITLE
Losing abilities upon death.

### ISSUE THREAD

**Issue by Danapel** [CyclopsMC/EverlastingAbilities#121]
#### Issue type:

- :bug: Bug

____

#### Short description:

 Abilities are not staying after death and disappear after dying in mod pack Project Ozone 3. 

#### Steps to reproduce the problem:

1. die
2. respawn

#### Expected behaviour:

I expect the abilities to stay on the character even after death as stated in the description of the mod, unless I misinterpreted something. 

#### Versions:

- This mod: 1.5.0
- Minecraft: 1.12.2
- Forge: unsure

#### Log file:

 (does not crash)

**Comment by rubensworks** [comment]
Please report this to the PO3 issue tracker, it's highly likely that they configured this mod to work like that.

**Comment by Danapel** [comment]
Just posted it, I for some reason didn't even consider that there's a possibility that PO3 has it set that way. I just sent a message on how to change it, thank you.

**Comment by Danapel** [comment]
It is part of the pack, thank you!
