### ISSUE TITLE
Losing Flight buff when someone other die/connect/disconnect

### ISSUE THREAD

**Issue by djwild** [CyclopsMC/EverlastingAbilities#123]
We're playing on a server, and whenever someone dies, log in to the server or logout we lose the flight buff for 10-20seconds.
(We're on a skyblock world, losing flight isnt very fun, can lead to more deaths and more time without fly buff, is like a chain reaction of ppl dying lol)

**Comment by rubensworks** [comment]
This mod is merely [enabling creative-mode flight.](https://github.com/CyclopsMC/EverlastingAbilities/blob/master-1.12/src/main/java/org/cyclops/everlastingabilities/ability/AbilityTypeFlight.java#L20) So if this breaks, this would mean that some other mod in your pack is disabling flight on death/(dis)connect. There's unfortunately not much I can do about that on my end.

The only thing you could do as far as I can see is going through your modlist, and disabling them one-by-one to find the offending mod.

**Comment by djwild** [comment]
Thanks for the fast reply rubensworks, not sure if i want to try that with 200+ mods, will take ages. We'll just keep enjoying our death chain reaction for now XD

**Comment by rubensworks** [comment]
Ok, should you be able to figure out what mod is causing it, be sure to let me know :-)
