### ISSUE TITLE
 Suggestions: Option to adjust the range of blocks the Buff/Debuff totems apply to mobs.

### ISSUE THREAD

**Issue by SirAron111** [CyclopsMC/EverlastingAbilities#125]
#### Issue type:

- :heavy_plus_sign: Feature request

____

#### Short description:

Currently I noticed that the range on the totems seems pretty close combat oriented. I mean for things like weakness that’s not a big problem as most mobs you need weakness applied to are melee anyway. But for some totems like wither, poison (or combustion, klutz etc from everlasting abilities potion core) I think being able to adjust the range they applied to would be good.

Also an option to change it so that things like wither and poison always tick the same speed on stacking the totems and instead up the damage they do to reduce tick spamming lag on high stacked effects! (Or is that not possible as that’s just the way dot dmg works in Minecraft)

**Comment by rubensworks** [comment]
I thought this was possible already, apparently not :-)

**Comment by rubensworks** [comment]
Should be possible now with the datapack functionality.
