### ISSUE TITLE
Bug: Not getting displayed resulting totem when combining totems together.

### ISSUE THREAD

**Issue by SirAron111** [CyclopsMC/EverlastingAbilities#126]
#### Issue type:

- :bug: Bug

____

#### Short description:

I recently noticed a small bug especially prominent on servers or when crafting totems together in tinker’s crafting station whose inventory can be accessed by multiple people at the same time.
If you add let’s say 4 random totems (made it 4 instead of 3 in my pack) of any tier to make a new random one, it will display the resulting totem at the crafting result slot but when taking it out into your inventory it changes into a completely random other totem.  (its sad when you combine like 4 tier 2 totems thinking great this makes a regeneration totem of tier 3 in the display but you take it out and bam its bonemealer)

Also if players watch the crafting of a new totem from old ones together in a let’s say Tinkers station or ME system etc any inventory where multiple people can see the same stuff happen, the resulting totem that gets displayed is different so one person would see strength and another one would see poison for example.

#### Steps to reproduce the problem:

1.Easiest way to reproduce would be testing it maybe on a server in a tinker station in creative should be the faster (also happens with everlasting abilities potion core making it even more of a random game of chance)

#### Expected behaviour:

____
1.	Expectation one bug free: Put totems in see resulting totem take it out get resulting totem.
2.	Expectation two true random with chance of better one: Expect totems to be totally random of same tier or higher just display a “???” totem instead of giving false hints

#### Versions:

- This mod: EverlastingAbilities-1.12.2-1.5.1.jar
- Minecraft: 1.12.2
- Forge: 14.23.5.2838

**Comment by rubensworks** [comment]
This does not happen with regular crafting tables, right?

The totem combination recipe expects that it is run server-side, with the result being sent back to the client. It sounds these other crafting tables fetch the crafting result client-side, which causes the conflicting outputs.

Not sure how easy this will be to fix on my end. I could somehow try to make the randomness more deterministic.

**Comment by SirAron111** [comment]
Ye it could be that it only happens on the tinker’s benches and ME etc. Since on servers 2 players would see different results and even if only one person looks inside it gives a random one instead when taking it out. …. I think for the feel of this mod it would make more sense to just make it display??? on the totem and gave a random one when it gets taken out that would also prevent players from keep changing the totems they put in hoping to get the best result. Just make it random (with the configured chance to get a higher tier one and never one of the ones used for crafting)

If you would hear my idea on this:
Simply make totems not craft into other totems make it so you need totems of the same tier to craft them together and output a loot box/totem box of that tier containing a chance to get a random totem of the same tier or by the in config set chance a one tier higher box. This would make it more random but also more clear on what you can expect from crafting them together.

I like the mod and use it as a key feature for my rpg like Modpack (only other problem I have is that they drop from grinders so I can’t say you only get totems from rare mobs or looting structures (I have loads of structures filled with these totems and other loot) at some point people just use fake players to get a big box of all the totems by afk farming)

Take your time just wanted to let you know.

**Comment by rubensworks** [comment]
> I think for the feel of this mod it would make more sense to just make it display???

It actually used to work like this. But with the 1.12 MC update, it was actually possible to be more exact. But apparently this breaks with other mods :-(

**Comment by SirAron111** [comment]
Ye i know that in 1.12.2 hidden stats or the like will get displayed especially if other mods add more info to items. That’s why I said craft them in an independent item (loot box like thingy) instead of getting the totem directly. (that way players would also be able to see the recipe and the item in jei and know of it (I made a little notice in a quest telling people about this hidden recipe especially since I changed it to needing 4 from 3 as you get lots of loot in my pack people didn’t know how to craft them together and people who know thought I disabled the 3 totems makes new one function))

**Comment by rubensworks** [comment]
This should not be an issue anymore in recent versions.
