### ISSUE TITLE
Minecraft 1.14.4 Totems does not show up in JEI but shows up in creative

### ISSUE THREAD

**Issue by raziel23x** [CyclopsMC/EverlastingAbilities#127]
#### Issue type:

- :bug: Bug

____

#### Short description:

When you type totem in the JEI to search for the totems to see what different abilities you can learn they do not show up but if you change your game mode into creative they show up there

#### Steps to reproduce the problem:
install the JEI type mods and search for totems to see the different tiers of the totems

#### Expected behaviour:
when searching with any of the jei type mods all the totems show up to tell you the different affects you can get

____

#### Versions:
Minecraft 1.14.4
Forge-1.14.4-28.0.105
CyclopsCore-1.14.4-1.5.0
EverlastingAbilities-1.14.4-1.5.1
jei-1.14.4-6.0.0.11

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
Seems like this is intended behaviour of JEI.
