### ISSUE TITLE
Bump to new Forge RB

### ISSUE THREAD

**Issue by WenXin20** [CyclopsMC/EverlastingAbilities#129]
#### Issue type:

- :bug: Bug

____

#### Short description:

 I recieved this crash upon loading up my world after updating Forge from v28.0.105 to v28.1.1

#### Steps to reproduce the problem:

1. Update Forge to v28.1.1
1. Load a world up.

#### Expected behaviour:

 For it to load a world without crashing.

____

#### Versions:

- Everlasting Abilities: v1.5.1
- Cyclops Core: v1.5.0
- Minecraft: v1.14.4
- Forge: v28.1.1

#### Log file:
[Crash Report](https://gist.github.com/WenXin20/6664921ebfe564843dd9a6132f27660e)

**Comment by marios-andr** [comment]
Happens to me too I love this mod so you can imagine how annoying this is for me :/

**Comment by rubensworks** [comment]
Forge had breaking changes, so it's normal that things broke. I suggest waiting to update until mods have had time to update.

**Comment by alphaexomega** [comment]
Afraid it still persists.
