### ISSUE TITLE
[Issue] Compat other mods (Actually Additions)

### ISSUE THREAD

**Issue by accessdenied0** [CyclopsMC/EverlastingAbilities#13]
Hello dear Cyclops Team, 

Installed lately your mod Everlasting Abilities but run into issues with Actually Additions. It made some of the machines stop and in addition if I tried to open a GUI (Coal Generator in my case) it immediately closed it and put this in my console: http://pastebin.com/mvH7Hykf 

Not sure if this is the fault of which mod, because of that it might be necessary to open an issue over Actually Additions (edit issue: https://github.com/Ellpeck/ActuallyAdditions/issues/223)

access_denied

**Comment by rubensworks** [comment]
I assume this will be something on @Ellpeck's side. Since that seems to be a tile entity crash, and this mod does not add any tile entities. I'll keep an eye on it.

**Comment by rubensworks** [comment]
Looking at the issue at https://github.com/Ellpeck/ActuallyAdditions/issues/223, it seems to be unrelated to this mod, closing.
