### ISSUE TITLE
Crash / incompatibility with CarryOn

### ISSUE THREAD

**Issue by MatthiasMann** [CyclopsMC/EverlastingAbilities#130]
#### Issue type:
Game crashes on world load / enters endless loop and needs to be killed
____

#### Short description:

Added CarryOn after it updated

#### Steps to reproduce the problem:

1) Have a world with EverlastingAbilities (created with EverlastingAbilities-1.14.4-1.5.1)
2) Update Forge to 28.1.1 and all mods including EverlastingAbilities to 1.5.2
3) add CarryOn
4) => crash on world load

#### Expected behaviour:

No crash and being bale to carry entities around
____

#### Versions:

EverlastingAbilities-1.14.4-1.5.2
CarryOn+MC1.14.4+v1.12.2

- This mod: 1.5.2
- Minecraft: 1.14.4
- Forge: 28.1.1

#### Log file:
[crash-2019-09-15_16.51.13-server.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/3613878/crash-2019-09-15_16.51.13-server.txt)

**Comment by rubensworks** [comment]
Could you report this to the CarryOn issue tracker as well? Since this works without any other mods installed, I assume that CarryOn may be doing something wrong with capability providers.
