### ISSUE TITLE
Crash w/ Public GUI Annoucement

### ISSUE THREAD

**Issue by WenXin20** [CyclopsMC/EverlastingAbilities#131]
#### Issue type:

- :bug: Bug

____

#### Short description:

 I received this crash after creating a new world and adding the mod Public GUI Announcement. If this needs to be reported elsewhere, I can also do that.

#### Steps to reproduce the problem:

1. Install Public GUI Announcement
2. Create a new world

#### Expected behaviour:

 No crashes and/or custom support for this mod.

____

#### Versions:

- [Public GUI Announcement](https://www.curseforge.com/minecraft/mc-mods/public-gui-announcement): v1.0.1.0
- Everlasting Abilities: v1.5.2
- Minecraft: v1.14.4
- Forge: v28.1.1

#### Log file:

[Crash Report](https://gist.github.com/WenXin20/3272d517e9f33bf45127154289f7e85b)

**Comment by rubensworks** [comment]
Please report this to the Public GUI Announcement author.
It looks like they are calling `player.getCapability()` with a `null` capability, which is not allowed.
CyclopsCore simply has a check in place to ensure that this capability is not null.
