### ISSUE TITLE
Game crashes when attacking zombies

### ISSUE THREAD

**Issue by raziel23x** [CyclopsMC/EverlastingAbilities#132]
#### Issue type:

- :bug: Bug

____

#### Short description:

I already gone through the mods in my modpack turning them off one at a time and the crash no longer happens when i disable this mod and reload the save file

when i attack a zombie the game crashes

#### Steps to reproduce the problem:

when i attack a zombie the game crashes does not do this with skeletons just zombies

#### Expected behavior:

not to crash when i attack zombies

____

#### Versions:

- This mod: EverlastingAbilities-1.14.4-1.5.2
- Minecraft: 1.14.4
- Forge: 28.1.6

#### Log file:

https://paste.dimdev.org/apehozuyij.pl

[crash-reports.zip](https://github.com/CyclopsMC/EverlastingAbilities/files/3622925/crash-reports.zip)

**Comment by rubensworks** [comment]
The first line mentions _RandomPatches Entity Transformer_, so that coremod is likely the cause of the problem.
Since it changes MC code, that mod is responsible for any conflicts with other mods. I suggest you report this to their issue tracker.

Please link back to this issue, so I keep updated on the process.

**Comment by raziel23x** [comment]
I have tried it without that enabled as well and still crashes
https://paste.dimdev.org/idejijayiw.pl

<blockquote><div><strong><a href="https://paste.dimdev.org/idejijayiw.pl">hastebin</a></strong></div></blockquote>

**Comment by rubensworks** [comment]
Have you already tried without any other mods installed?

**Comment by raziel23x** [comment]
as requested with just the mod loaded and it works fine so there is a conflict between this mod and another mod then because the modpack works just fine when i just disable this mod and works just fine if i disable everything but this mod so another mod is conflicting with what ever changes this mod is doing

**Comment by raziel23x** [comment]
[Raziel23x World.zip](https://github.com/CyclopsMC/EverlastingAbilities/files/3623014/Raziel23x.World.zip)

[Land of the Lost 1.14.4-1.0.0.zip](https://github.com/CyclopsMC/EverlastingAbilities/files/3623023/Land.of.the.Lost.1.14.4-1.0.0.zip)

Here is a cope of the save and the export for anyone who wants to test

**Comment by raziel23x** [comment]
I have asked around in the forge forums and gotten these suggestions 
https://www.minecraftforge.net/forum/topic/76145-forge-2816-causing-crash-when-killing-zombies/

<blockquote><img src="https://www.minecraftforge.net/forum/uploads/set_resources_2/247441864ab051a2bd22c960e8e7b8b5_favicon.ico" width="48" align="right"><div><img src="https://www.minecraftforge.net/forum/uploads/set_resources_2/247441864ab051a2bd22c960e8e7b8b5_favicon-16x16.png" height="14"> Minecraft Forge Forums</div><div><strong><a href="https://www.minecraftforge.net/forum/topic/76145-forge-2816-causing-crash-when-killing-zombies/">Forge 28.1.6 causing crash when killing zombies</a></strong></div><div>Here are 2 crash reports i gotten when i updated from 28.1.1 to 28.1.6 the crashes are not happening in 28.1.1 https://paste.dimdev.org/xijomefomo.pl https://paste.dimdev.org/gogubijure.pl</div></blockquote>

**Comment by raziel23x** [comment]
also reported it first here https://github.com/TheRandomLabs/RandomPatches/issues/59#issuecomment-532100716

**Comment by rubensworks** [comment]
As Lex has said on the forum, some mod in your pack is messing with revenge targets of zombies.
This mod does not touch that part of MC at all, so I suggest you follow Lex's advice and remove mods until you find the culprit.

**Comment by raziel23x** [comment]
but it does not explain why disabling this mod fixes the issue

**Comment by raziel23x** [comment]
https://www.minecraftforge.net/forum/topic/76145-forge-281x-causing-crash-when-killing-zombies/?tab=comments#comment-366371 @rubensworks 

<blockquote><img src="https://www.minecraftforge.net/forum/uploads/set_resources_2/247441864ab051a2bd22c960e8e7b8b5_favicon.ico" width="48" align="right"><div><img src="https://www.minecraftforge.net/forum/uploads/set_resources_2/247441864ab051a2bd22c960e8e7b8b5_favicon-16x16.png" height="14"> Minecraft Forge Forums</div><div><strong><a href="https://www.minecraftforge.net/forum/topic/76145-forge-281x-causing-crash-when-killing-zombies/">Forge 28.1.X causing crash when killing zombies</a></strong></div><div>Here are 2 crash reports i gotten when i updated from 28.1.1 to 28.1.6 the crashes are not happening in 28.1.1 https://paste.dimdev.org/xijomefomo.pl https://paste.dimdev.org/gogubijure.pl</div></blockquote>

**Comment by raziel23x** [comment]
with Animefan8888 and he said this could be the issue https://www.minecraftforge.net/forum/topic/76145-forge-281x-causing-crash-when-killing-zombies/?tab=comments#comment-366371
https://gitlab.com/Lycanite/LycanitesMobs/issues/582
MinecraftForge/MinecraftForge#6185 

it has to be a conflict with how you introduce invisibility as it only happens when invisibility is affecting the character i had this same thing reported to just about every tracker on the crash report isssue trackers and everyone keeps saying they are not the issue so i am not sure what you or LycanitesMobs are doing to the invisibility affect that is causing this issue

<blockquote><img src="https://www.minecraftforge.net/forum/uploads/set_resources_2/247441864ab051a2bd22c960e8e7b8b5_favicon.ico" width="48" align="right"><div><img src="https://www.minecraftforge.net/forum/uploads/set_resources_2/247441864ab051a2bd22c960e8e7b8b5_favicon-16x16.png" height="14"> Minecraft Forge Forums</div><div><strong><a href="https://www.minecraftforge.net/forum/topic/76145-forge-281x-causing-crash-when-killing-zombies-while-invisible/">Forge 28.1.X causing crash when killing zombies while invisible</a></strong></div><div>Here are 2 crash reports i gotten when i updated from 28.1.0 to 28.1.22 the crashes are not happening in 28.0.X https://paste.dimdev.org/xijomefomo.pl https://paste.dimdev.org/gogubijure.pl</div></blockquote>
<blockquote><img src="/uploads/-/system/project/avatar/6694860/_Argus_Preview_Square.jpg" width="48" align="right"><div>GitLab</div><div><strong><a href="https://gitlab.com/Lycanite/LycanitesMobs/issues/582">[1.14.4] java.lang.NullPointerException: Ticking entity when attacking a zombie while invisible (#582) · Issues · Richard Nicholson / LycanitesMobs</a></strong></div><div>Minecraft Version: 1.14.4 Forge Version: 28.1.0-28.1.0 - 28.1.22 Lycanites Mobs Version:all versions thus far even tested on most recent 2.1.0.1 Logs: https://paste.dimdev.org/akonuzitoh.mccrash Steps to Reproduce: 1. find or spawn in...</div></blockquote>

**Comment by rubensworks** [comment]
> it has to be a conflict with how you introduce invisibility

This mod just uses the vanilla invisibility potion effect.
I suggest you try giving yourself invisibility with a vanilla potion, and seeing if the problem persist.
