### ISSUE TITLE
Common_setup event phase Error 1.14.4

### ISSUE THREAD

**Issue by ShidouYuu** [CyclopsMC/EverlastingAbilities#133]
#### Issue type:

Game is crushing, not able to reach main menu.

____

#### Short description:

I tried to use this mod with CyclopsCore, but my game crash everytime.
I tried to downgrade forge, and i also tried 4 days old version of mod, and version from 11/09

![Screenshot_1](https://user-images.githubusercontent.com/40305162/65214449-4b0dc580-daaa-11e9-8df6-c982182f26ff.png)
![Screenshot_1](https://user-images.githubusercontent.com/40305162/65214468-519c3d00-daaa-11e9-90e0-8826947f421b.png)

#### Steps to reproduce the problem:

1. ... instal forge 
put  CyclopsCore and Everlasting abilites in mods folder in .minecraft
it happens :/

____

#### Versions:

- This mod: EverlastingAbilities-1.14.4-1.5.2 (all files from 15 and 11 of september )
- Minecraft: 1.14.4
- Forge: tried with 1.14.4 - 28.1.10
1.14.4 - 28.1.0
1.14.4 - 28.1.8

#### Log file:  (Same happens on clear version of mc)
 https://pastebin.com/B58KWbTP

**Comment by rubensworks** [comment]
That's weird... Have you tried without any other mods installed?

**Comment by ShidouYuu** [comment]
Yes, I left only cyclops core and everlasting in mod folder, and I get same error.

**Comment by ShidouYuu** [comment]
Just to be completely sure, i deleted .minecraft folder, downloaded 1.14.4, get lastest forge (1.14.4 - 28.1.10) and i got same error (https://pastebin.com/tCGZ13e1).
then i got 1.14.4 - 28.1.0 forge version, and i get same (https://pastebin.com/jFtV7J6w) 

<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/tCGZ13e1">Lastest log clear - Pastebin.com</a></strong></div></blockquote>
<blockquote><img src="https://pastebin.com/i/facebook.png" width="48" align="right"><div>Pastebin</div><div><strong><a href="https://pastebin.com/jFtV7J6w">1.14.4 - 28.1.0 - Pastebin.com</a></strong></div></blockquote>

**Comment by Jadedragon27** [comment]
I tested it out myself, and the issue only happens with Cyclops Core 1.5.2, but the game works fine with 1.5.1 CC.  I haven't actually gone into the game yet, I'll update you on that in a bit, but for now I know I can get to the main menu with 1.5.1.

**Comment by rubensworks** [comment]
That's even weirder then. Nothing in CC's JSON files was changed in the last update.

**Comment by rubensworks** [comment]
Fix in 1.5.3
