### ISSUE TITLE
1.14.4 not respecting config settings

### ISSUE THREAD

**Issue by krazzykid2006** [CyclopsMC/EverlastingAbilities#134]
#### Issue type:

- :bug: Bug

____

#### Short description:

Not respecting config file settings.
#### Steps to reproduce the problem:

Change the config file and then start the game. 

#### Expected behaviour:

Config files that work.

____

#### Versions:

- This mod: 1.5.3
- Minecraft: 1.14.4
- Forge: 28.1.1
- Cyclops: 1.5.2

I have modified the config file, such as disabling certain abilities or changing the required xp, and it's not using the changes at all. 
Doesn't matter what I change in the everlastingabilities-common.toml absolutely none if it is used in game. All the other config files generate completely empty, so those aren't the issue either.

I verified by running a pack with only forge, everlasting abilities, and cyclops core installed and the issue is still present.

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
