### ISSUE TITLE
The everlastingabilities folder not created in the config folder.

### ISSUE THREAD

**Issue by MakiTsuki** [CyclopsMC/EverlastingAbilities#139]
#### Issue type:

- :bug: No everlastingabilities folder in config folder.

____

#### Short description: 

I installed the mod and started the game, went into a world, mod is loaded. The everlastingabilities folder did not appear in my config folder, only config files.

#### Steps to reproduce the problem:

1. Install mod through twitch app(it should install all required mods that it needs aka library).

2. Start the game.

3. Load into an existing save.

4. Made a new world just in case (optinal)

5. Quit the game.

#### Expected behaviour: Have the everlastingabilities folder to be created inside the config folder.

____

#### Versions:

- This mod: 1.5.5
- Minecraft: 1.14.4
- Forge: 28.1.31

**Comment by rubensworks** [comment]
This sounds sounds like the intended functionality to me.

Why do you expect a folder to be created?

Does editing the config file not work for you?

**Comment by MakiTsuki** [comment]
it says in the wiki(Recipe XML) it was going to generated there

**Comment by rubensworks** [comment]
The Recipe XML system has been removed in 1.14 in favor of Vanilla recipe JSON files.
I'll update this in the wiki.
