### ISSUE TITLE
How to add crafting recipes for the different totems?

### ISSUE THREAD

**Issue by MakiTsuki** [CyclopsMC/EverlastingAbilities#140]
#### Issue type:

- :question: Question

____

#### Question:

how do you make a recipes for the diffrent totems?

ps: I tried do it with a datapack but that didn't work.

**Comment by rubensworks** [comment]
As far as I know, there's no way of doing that at the moment, since totems are capability-based.

I'll make this a feature request issue.

**Comment by rubensworks** [comment]
It looks like this was already possible!

I just documented this on https://github.com/CyclopsMC/EverlastingAbilities/wiki/Creating-recipes-for-totems-and-bottles

<blockquote><img src="https://opengraph.githubassets.com/bc188b8f69784738bc89a0cddad20852defa9729b73058daf293b5b57cbdf269/CyclopsMC/EverlastingAbilities" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities">Creating recipes for totems and bottles · CyclopsMC/EverlastingAbilities Wiki</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>
