### ISSUE TITLE
White Rarity Particles showing on all mobs at distance in fog

### ISSUE THREAD

**Issue by IdrisQe** [CyclopsMC/EverlastingAbilities#141]
For some reason, ever since installing EverlastingAbilities, nearly EVERY mob has shown white rarity particles when viewed from a distance. Sometimes it's more noticable, like in the video, while other times it's barely visible. In either case, when getting close to the mob, the particles disappear if the mob isn't actually carrying a totem. Mobs affected by this don't drop totems either. This seems to mainly be visible during foggy conditions- it may actually be only occuring when mobs are "within" the fog. Forge 14.23.5.2847, EA 1.5.1, and I am using Optifine (HD_U_E3).
(apologies for the terrible quality and cropping, apparently gifs can only be <10MB in github)
![Untitled](https://user-images.githubusercontent.com/40530630/66612589-18ba2a00-eb77-11e9-8cf4-ce7e1b2d9295.gif)

**Comment by rubensworks** [comment]
Could you try without any other mods installed?
