### ISSUE TITLE
Fly Ability is not Working

### ISSUE THREAD

**Issue by itsgelo** [CyclopsMC/EverlastingAbilities#142]
#### Issue type:

- :bug: Bug

____

#### Short description:

The Fly ability doesn't work when space bar is pressed twice

#### Steps to reproduce the problem:

I have no idea

1. ...

#### Expected behaviour:

Fix the problem if possible.

____

#### Versions:

- This mod: 1.14.4-1.5.5
- Minecraft: 1.14.4
- Forge: 28.1.39

**Comment by rubensworks** [comment]
Did you try without any other mods installed?

**Comment by itsgelo** [comment]
yes I tried, seems to be not working at all

**Comment by rubensworks** [comment]
I just tried this myself, and things seem to be working just fine.

I also have reports of other people where flight works without problems.

Can you think of any reason why your environment might be different and could cause flight to break?

**Comment by itsgelo** [comment]
it might be because I have too many mods installed, is their any mods that can conflict the flight ability so I can remove it?

**Comment by rubensworks** [comment]
I asked before if you had any other mods installed....

I have no idea what mod could be causing it, there are thousands of reasons why it could fail.

**Comment by itsgelo** [comment]
oh my bad, ill just delete every single mod until it works, thanks though

**Comment by Mithrilchu** [comment]
i had this problem and isolated one mod there cause it. the angel ring mod by denismasterherobrine  cause the flight ability to not work for me. when uninstalling it, the flight ability worked again.

**Comment by rubensworks** [comment]
@itsgelo Do you have this same angel ring mod installed?

**Comment by DropBear77** [comment]
Same here, with the Mod AngleRing from DenisMasterHerobrine flight is not working, after disabling the AngleRing mod the flight is working perfectly.
