### ISSUE TITLE
Add support for Demagnetize mod.

### ISSUE THREAD

**Issue by digitalseraphim** [CyclopsMC/EverlastingAbilities#144]
#### Issue type:

- :heavy_plus_sign: Feature request
Please add support for the Demagnetize mod, based on the description on their curseforge page (https://www.curseforge.com/minecraft/mc-mods/demagnetize).
____

#### Short description:

When you have any number of levels in "magnetize", items protected by the blocks from Demagnetize are not attracted to the player.

**Comment by rubensworks** [comment]
PRs for this are welcome.
