### ISSUE TITLE
Ability Totem only removes Main Hand item, even when used in Off Hand

### ISSUE THREAD

**Issue by Discomanco** [CyclopsMC/EverlastingAbilities#146]
#### Issue type:

- :bug:, semi-serious one?

____

#### Short description:

Found some totems in a loot chest, tried to figure out how they worked (wikis are boring). Put them in Off Hand, in case it was like a held-item buff. Right clicked it and figured out how it worked.
I learned the ability, and the sword in my Main Hand was gone, and I had an ability-less totem in my Off Hand (ability was still learned though)

#### Steps to reproduce the problem:

1. Equip something in Main Hand
2. Put a totem with an ability in your Off Hand
3. Right click in air, to open up the Ability GUI
4. Learn the Ability from the totem
5. Your Main Hand item is consumed, and you have a totem with no ability in your Off Hand

#### Expected behaviour:

The totem to be consumed when used, whether it is in Main Hand or Off Hand

____

#### Versions:

- This mod: 1.5.5
- Minecraft: 1.14.4
- Forge: 28.1.74

#### Log file:

No crash, latest.log prints no event of this

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!
