### ISSUE TITLE
Certain abilities are not working with every mob

### ISSUE THREAD

**Issue by Wxrlds** [CyclopsMC/EverlastingAbilities#147]
#### Issue type: Fertility Ability not working correctly

- :bug: Bug

____

#### Short description:

Donkeys, Horses, Llamas do not breed when using the Fertility Ability

#### Steps to reproduce the problem:

1. Give yourself the Fertility Ability
2. Spawn in listed mobs
3. Observe how they do not breed even though they get the heart particles

#### Expected behaviour:

These mobs should breed
___

#### Versions:

- This mod: EverlastingAbilities-1.12.2-1.5.1
- Minecraft: 1.12.2
- Forge: forge-14.23.5.2847

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
This seems to work fine for me.
I assume you did not tame these animals first, which is a vanilla requirement for breeding.
