### ISSUE TITLE
Compatabilty issue with Corail Tombstone Mod

### ISSUE THREAD

**Issue by Anuuviem** [CyclopsMC/EverlastingAbilities#148]
#### Issue type:

NPE when used in conjunction with Corail Tombstone Mod

Loot in dungeons and abandoned mines will not spawn. Mod itself seems to function normally. Access gui assign effects
____

#### Short description:

Null Pointer exception in regard to loot tables

#### Steps to reproduce the problem:

1. Minecraft 1.14.4 Forge 28.1.90
Install Corail Tombstone, Everlasting Abilities and Cyclops Core together

#### Expected behaviour:

Everybody to integrate and behave nicely

____

#### Versions:

- This mod: Recommended 1.0.2
- Minecraft: 1.14.4
- Forge: 28.1.90

#### Log file:

https://pastebin.com/E558ejYk

**Comment by rubensworks** [comment]
It looks like some other mod in your pack (possibly Corail Tombstone Mod) is adding invalid (null name) loot pools to loot tables, which causes a crash when other (valid) loot pools are added to loot tables.

I suggest you report this to the mod author of Corail Tombstone Mod (or the other mod in your pack that is causing this).
