### ISSUE TITLE
flight doesnt work

### ISSUE THREAD

**Issue by adrwa** [CyclopsMC/EverlastingAbilities#15]
kroe, fix plz.. flight ability doesnt work..

**Comment by rubensworks** [comment]
Works fine in the standalong mod, so there must be a mod messing with it.
Someone should to a binary search removal of mods through the MMD pack mods to figure out what mod is causing it.
I'll can do it, but that won't be for today :-)

**Comment by rubensworks** [comment]
Ok, I finally figured out the conflicting mod: p455w0rdsThings.

Can be reproduced with:
  CyclopsCore-1.9.4-0.7.7.jar
  EverlastingAbilities-1.9.4-1.1.1.jar
  p455w0rdsThings-1.9.4-0.0.17a.jar

@p455w0rd Any idea what may be causing this?
Creative flight can not be enabled anymore with your mod when double-tapping space.
Tested with p455w0rdsThings-1.9.4-0.0.17a.

**Comment by p455w0rd** [comment]
let me look into it

**Comment by p455w0rd** [comment]
Just tested in p455w0rdsThings-1.10.2-0.0.18a, applied the flight ability totem and had no issues flying :)

**Comment by rubensworks** [comment]
Ok great, thanks :-)
