### ISSUE TITLE
[1.14.4] From Discord: CyclopsCore 1.6.1 is an API-breaking change

### ISSUE THREAD

**Issue by GreyMario** [CyclopsMC/EverlastingAbilities#152]
#### Issue type:

- :bug: Bug

____

#### Short description:

According to a conversation started [early December 26, 2019](https://discordapp.com/channels/386052815128100865/386054303137136651/659713946252476426) on the CyclopsMC Discord, CyclopsCore version `1.14.4-1.6.1` is an API-breaking change that EverlastingAbilities `1.14.4-1.6.0` is not happy with.

____

#### Log excerpt

According to the user, no crash log was generated. [This Pastebin](https://pastebin.com/SrvkmEHD) contains an excerpt from the normal log which appears to be relevant.

**Comment by rubensworks** [comment]
This looks relevant:

> Type 'org/cyclops/everlastingabilities/inventory/container/ContainerAbilityContainer' (current frame, stack[1]) is not assignable to 'org/cyclops/cyclopscore/inventory/container/InventoryContainer'
