### ISSUE TITLE
Everlasting Abilities Respawn Issue

### ISSUE THREAD

**Issue by dreckz** [CyclopsMC/EverlastingAbilities#154]
#### Issue type:
- :bug: Bug

____

#### Short description:

Upon dying and attempting to respawn, the button shows it was presesed, but doesn't respawn the player.

#### Steps to reproduce the problem:

1. Player death
2. Attempt to respawn

#### Expected behaviour:

Supposed to respawn normally
____

#### Versions:

- This mod: 1.6.0.  
- Cyclops Core: 1.6.0
- Minecraft: 1.14.4
- Forge: 28.1.107

#### Log file:

Main error block:
https://pastebin.com/703URvXz
Entire log:
[2020-01-16-6.log.gz](https://github.com/CyclopsMC/EverlastingAbilities/files/4075085/2020-01-16-6.log.gz)

Using the modpack [Treasures of Altera](https://www.curseforge.com/minecraft/modpacks/treasures-of-altera)

**Comment by rubensworks** [comment]
Thanks for reporting!
