### ISSUE TITLE
Absorption effect's timer

### ISSUE THREAD

**Issue by Briezyy** [CyclopsMC/EverlastingAbilities#158]
Issue type:

- :bug: Bug

Short description:

The absorption effect's timer is counting down unlike other effects where the timer is frozen. Up until lvl 3/5 and above the effect is not constant and due to the timer the effect is removed and re- allied after a few seconds.

Steps to reproduce the problem:

1. Apply absorption to player via the ability bottle, open inventory to see effect's timer counting down

Expected behaviour:

For the absorption effect to be persistent

____

#### Versions:

- This mod: 1.6.0
- Minecraft: 1.14.4
- Forge: 28.1.39

**Comment by rubensworks** [comment]
This is intentional, because the absorbtion effect would be too OP otherwise.
