### ISSUE TITLE
[1.14.4] Crash Upon Opening Ability Bottle

### ISSUE THREAD

**Issue by Areorah** [CyclopsMC/EverlastingAbilities#159]
#### Issue type:

- :bug: Bug

____

#### Short description:
Crash upon opening ability bottle.

#### Steps to reproduce the problem:

1. Open your ability bottle.

#### Expected behaviour:
To show the UI in order to change your abilities, and not crash.

____

#### Versions:

- This mod: EverlastingAbilities-1.14.4-1.6.1
- Minecraft: 1.14.4
- Forge: Forge / 1.14.4 / 28.2.0

#### Log file:
https://pastebin.com/mde7x0x6

**Comment by tnmII** [comment]
Same, also tested with only EverlastingAbilities and Cyclopscore loaded with same results.  Happens also with totems, not just bottle.

[crash-2020-02-13_14.47.38-server.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/4200756/crash-2020-02-13_14.47.38-server.txt)

**Comment by rubensworks** [comment]
I've pulled EA 1.6.1. It requires a big CC update. I suggest to downgrade EA to 1.6.0 for now.
