### ISSUE TITLE
Issues with several potion effects

### ISSUE THREAD

**Issue by Darkhax** [CyclopsMC/EverlastingAbilities#16]
When using the Speed effect, there is a flicker in FOV which is caused by the potion being applied and wearing off so frequently. While the 1.1.1 update seems to have made it better, I am still experiencing the issue with Speed V. 
![animation](https://cloud.githubusercontent.com/assets/2250798/18310077/d6d65898-74b9-11e6-88f6-a4db9b2fd0ad.gif)

Additionally, the Night Vision effect seems to be applied so infrequently at tier 1, that it has no actual impact on the brightness levels.

**Comment by rubensworks** [comment]
The first issue should have been resolved in d3436c7272bff3c2539e630184e1facb99294bf8, which is not part of a new release yet. Are you testing it on the MMD server? If so, I'll see if the latest dev build can be pushed on there.

For the second issue; I'll look into it.

**Comment by rubensworks** [comment]
@darkhax I forgot to follow up on this, but do you still encounter this issue with the latest version?
