### ISSUE TITLE
Issue when using shaders

### ISSUE THREAD

**Issue by Stellarvideo588** [CyclopsMC/EverlastingAbilities#161]
When using OptiFine shaders with this mod installed, the particles that usually surround mobs that would drop a totem become present on all mobs, despite not dropping a totem.

**Comment by rubensworks** [comment]
Optifine is drastically messing with MC internals, so if something breaks because of the usage of Optifine, then this is something that should be fixed on their end.
So there's not much I can do on my end unfortunately.
