### ISSUE TITLE
[1.12.2] Stacking Haste Above 2 Breaks Punching/Interacting Animations

### ISSUE THREAD

**Issue by KangaliaV** [CyclopsMC/EverlastingAbilities#165]
#### Issue type:

- :bug: Bug

____

#### Short description:

Stacking haste above 2 breaks the punching/interacting animation. The arm will move up and down when punching, but not forward like it should, and the interacting animations (such as entering chests and furnaces) will not play at all. The same thing occurs with both an empty hand and while holding an item, and while mining/breaking blocks with any tool.

#### Steps to reproduce the problem:

1. Add haste 3 or above to yourself
2. Punch the air or blocks, interact with chests and other inventories, and break blocks with or without tools.

#### Expected behaviour:

The punching, mining and interaction animations should play as normal with haste higher than 2.

____

#### Versions:

- This mod: EverlastingAbilities-1.12.2-1.5.2
- Minecraft: 1.12.2
- Forge: 1.12.2-14.23.5.2847

#### Log file:

**Comment by rubensworks** [comment]
Unfortunately, there is nothing I can do about this, as this is a Vanilla quirk.
This behaviour is consistent with applying Haste 3 via Vanilla mechanics.
