### ISSUE TITLE
Ability timers refresh erratically or run out when day cycle length is extended by OpticManager

### ISSUE THREAD

**Issue by Sardav** [CyclopsMC/EverlastingAbilities#166]
#### Issue type:

- :bug: Bug

____

#### Short description:

When using the Optic Manager mod to extend the length of the day/night cycle, the timers of active abilities tick down erratically or disappear and reappear instead of staying fixed and active. This results in these abilities malfunctioning.

#### Steps to reproduce the problem:

1. Install the 4 relevant mods (Everlasting Abilities and dependency, Optic Manager and dependency).
2. Configure Optic Manager to have an extended day/night cycle duration. The config file used in these tests has the following inside opticmanager.json, for triple the day and night duration:
```
{
  "overrideDayNightBrightness": true,
  "dayBrightness": 1.0,
  "nightBrightness": 0.0,
  "dayDuration": 36000,
  "nightDuration": 36000
}
```
3. Start the game and create a new world.
4. Apply one or more abilities that manifests as a potion effect, such as Speed, Haste, Water Breathing, Strength, etc. (the bug affects others such as Bonemealer too, but they aren't easy to see for lack of an effect timer).
5. Do anything that affects the normal passage of in-game time, such as:
    set doDaylightCycle to False then to True again
    sleep on a bed to pass through the night or a thunderstorm
    change the in-game time
6. Open the inventory to see the ability/effect timer(s) ticking down erratically or disappearing/reappearing.

Notes: Using OpticManager with out-of-the-box configuration which does not extend the day/night cycle does not manifest this bug. The larger day/night cycle times are, the more prevalent the issue becomes. 
Another manifestation of the bug is that an active ability doesn't apply correctly even when their timers seem to be active and ticking down.
When doDaylightCycle is false, the bug does not manifest.

#### Expected behaviour:

Ability durations should refresh quickly enough to ensure they work as intended and don't run out erratically, regardless of day/night cycle length and/or doDaylightCycle setting.

____

#### Versions:

- This mod: 1.12.2-1.5.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2852

- Other mods involved:
   CyclopsCore 1.12.2-1.6.3
   CreativeCore 1.10.12_mc1.12.2
   OpticManager 1.1.9_mc1.12.2

**Comment by rubensworks** [comment]
Can you check if this problem also occurs when using vanilla potion bottles?
If so, then this would be a bug fully caused by OpticManager.

**Comment by Sardav** [comment]
Not sure if i understand completely what you mean, but I tested some vanilla potions from the creative mode tabs, namely Jump Boost II and Speed II, both of which last 1m 30s, they seem to be working fully as expected: their durations are correct as verified with a chronometer, and their effects apply correctly (Jump Boost II lets the player jump up 2 blocks and Speed II increases the speed beyond Speed I).

**Comment by rubensworks** [comment]
Ok, thanks for the additional information. Then it must be a conflict with this mod and OpticManager.

**Comment by rubensworks** [comment]
Appears to be an issue with OpticManager, reported https://github.com/CreativeMD/OpticManager/issues/13.
