### ISSUE TITLE
Some vanilla passive mobs missing from default config

### ISSUE THREAD

**Issue by TheOldOne822** [CyclopsMC/EverlastingAbilities#168]
#### Issue type:

- :bug: Default config change

____

#### Short description:
Many of the new passive mobs that shouldn't be effected by hostel abilities are not in the config list of passive mobs by default. This includes the Wandering trader (minecraft:wandering_trader), the Wandering trader lamas (minecraft:trader_llama), the turtle (minecraft:turtle), the fox (minecraft:fox), the dolphin (minecraft:dolphin), and the cat (minecraft:cat) that has been separated from the ocelot, Possibly the panda (minecraft:panda) as it's passive unless attacked and most remain passive after being attacked.

Also the golem ID has changed from "minecraft:villager_golem" to "minecraft:iron_golem"

The fish also are not in the list but neither was the squid so could be classed the same.

#### Steps to reproduce the problem:

1. give yourself an ability that is suppose to only effect hostel mobs

2. spawn one of the listed passive mobs

#### Expected behaviour:

Passive mobs shouldn't be effected by abilities that target hostel mobs
____

#### Versions:

- This mod: EverlastingAbilities-1.15.2-1.6.1
- Minecraft: 1.15.2
- Forge: forge-31.2.5

**Comment by rubensworks** [comment]
Thanks for reporting!
