### ISSUE TITLE
Totems don't take actual levels into account

### ISSUE THREAD

**Issue by p455w0rd** [CyclopsMC/EverlastingAbilities#17]
Ok so while i was testing the flight bug, I had the hardest time get your mod to recognise that I had 10k+ experience levels. I did /xp +10000L @p, which gave me the levels, but your mod didn't interpret this as such. It seems that you track XP Orbs or something rather than doing the easy thing and just checking levels. If this is intended, please give developers/admins a creative option for all the totems that would allow any totem to be applied regardless of experience level so long as the user is in Creative Mode.

**Comment by rubensworks** [comment]
Ah, I always tested with `\xp +1000 &p`, I wasn't aware the `L` parameter existed.
I'll look into it.

It should work eitherway though, MC probably does something funky there.
