### ISSUE TITLE
Am I using the wrong wildcard for friendly filtering?

### ISSUE THREAD

**Issue by PurpleHel** [CyclopsMC/EverlastingAbilities#170]
#### Issue type:

- :question: Question

____

#### Question:

When filtering for friendlies to not be affected by damaging abilities like poison, wildcards don't seem to work. For example, I have an entry for animania:*, but animania mobs still get poison and weakness and such. I'm on 1.12.2. Is * the wrong wildcard, or am I doing something else wrong?

**Comment by rubensworks** [comment]
Regex filtering is possible though, but you seem to have an invalid regex, it should be `animania:.*,`.

**Comment by PurpleHel** [comment]
Thanks!
