### ISSUE TITLE
EARLIER CONFIGURATIONS USED TO WORK

### ISSUE THREAD

**Issue by RyoStonewell** [CyclopsMC/EverlastingAbilities#171]
#### Issue type:

- :bug: Bug

____

#### Steps to reproduce the problem:

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge: 

#### Log file:

Ok, huge problem. I used to be able to set up everlasting abilities, before I knew about the potions version, so that chests and mobs do not give totems. That was... I believe last year. Now, on the same game version file, 1.12.2, btw, I did it again today, and now whenever I try to load the game with the mods, it crashes before forge finishes loading, even after I reset my computer and redownloaded the mods, all four of them. Is there another folder where I can get rid of the changes I made, or is the mod now busted forever?

**Comment by rubensworks** [comment]
Please fill in the proper issue template and share your crashlog.

**Comment by RyoStonewell** [comment]
Here's the crash report, but I'm not sure if it's the forge loading crash one.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Quark Plugin (Quark-r1.6-178.jar)
  offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 6/23/20 9:56 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at org.cyclops.everlastingabilities.EverlastingAbilities$1.loadPredefineds(EverlastingAbilities.java:130)
	at org.cyclops.cyclopscore.init.RecipeHandler.registerRecipes(RecipeHandler.java:129)
	at org.cyclops.cyclopscore.config.ConfigHandler.onRegistryEvent(ConfigHandler.java:352)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_ConfigHandler_onRegistryEvent_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.cyclops.everlastingabilities.EverlastingAbilities$1.loadPredefineds(EverlastingAbilities.java:130)
	at org.cyclops.cyclopscore.init.RecipeHandler.registerRecipes(RecipeHandler.java:129)
	at org.cyclops.cyclopscore.config.ConfigHandler.onRegistryEvent(ConfigHandler.java:352)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_70_ConfigHandler_onRegistryEvent_Register.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857)
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:636)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:747)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 844984296 bytes (805 MB) / 2684354560 bytes (2560 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_F5 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version         | Source                                           | Signature                                |
	|:----- |:-------------------- |:--------------- |:------------------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2          | minecraft.jar                                    | None                                     |
	| LCH   | mcp                  | 9.42            | minecraft.jar                                    | None                                     |
	| LCH   | FML                  | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | creativecoredummy    | 1.0.0           | minecraft.jar                                    | None                                     |
	| LCH   | srm-hooks            | 1.12.2-1.0.0    | minecraft.jar                                    | None                                     |
	| LCH   | timeoverhaul         | 0.0.4 Beta      | [1.12.2]+TimeOverhaul-'V_0.0.4+Beta'.jar         | None                                     |
	| LCH   | rpghud               | 3.6.7.1         | [1.12]+RPG-HUD-3.6.7.1.jar                       | None                                     |
	| LCH   | movillages           | 1.5.4           | [1.12]MoVillages-1.5.4.jar                       | None                                     |
	| LCH   | ram                  | 1.1             | [1.12]RealAdventureMode-1.1.jar                  | None                                     |
	| LCH   | ambientsounds        | 3.0             | AmbientSounds_v3.0.12_mc1.12.2.jar               | None                                     |
	| LCH   | antiqueatlas         | 4.5.1           | antiqueatlas-1.12.2-4.5.1.jar                    | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCH   | antiqueatlasoverlay  | 1.2             | antiqueatlas-1.12.2-4.5.1.jar                    | e631d7254e451d0360d0148cb21407d5511d45e9 |
	| LCH   | carrots              | 1.0.0b1         | carrotslib-mc1.12.2-1.0.0b1.jar                  | None                                     |
	| LCH   | armorunder           | 1.0.0           | armorunder-mc1.12.2-1.0.0.jar                    | None                                     |
	| LCH   | jei                  | 4.15.0.291      | jei_1.12.2-4.15.0.291.jar                        | None                                     |
	| LCH   | quark                | r1.6-178        | Quark-r1.6-178.jar                               | None                                     |
	| LCH   | autoreglib           | 1.3-32          | AutoRegLib-1.3-32.jar                            | None                                     |
	| LCH   | backpack             | 3.0.2           | backpack-3.0.2-1.12.2.jar                        | None                                     |
	| LCH   | baubles              | 1.5.2           | Baubles-1.12-1.5.2.jar                           | None                                     |
	| LCH   | biomesoplenty        | 7.0.1.2444      | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar    | None                                     |
	| LCH   | chinjufumod          | [1.12.2]5.1.3   | ChinjufuMod[1.12.2]5.1.3.jar                     | None                                     |
	| LCH   | toughasnails         | 3.1.0.139       | ToughAsNails-1.12.2-3.1.0.139-universal.jar      | None                                     |
	| LCH   | comforts             | 1.4.1.2         | comforts-1.12.2-1.4.1.2.jar                      | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | craftelytra          | 1.2             | CraftableElytra-1.1.jar                          | None                                     |
	| LCH   | creativecore         | 1.10.0          | CreativeCore_v1.10.16_mc1.12.2.jar               | None                                     |
	| LCH   | cucumber             | 1.1.3           | Cucumber-1.12.2-1.1.3.jar                        | None                                     |
	| LCH   | cyclopscore          | 1.6.4           | CyclopsCore-1.12.2-1.6.4.jar                     | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | enablecheats         | @MODVERSION@    | EnableCheats-1.12.2-1.0.0.jar                    | None                                     |
	| LCH   | everlastingabilities | 1.5.0           | EverlastingAbilities-1.12.2-1.5.0.jar            | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | potioncore           | 1.9_for_1.12.2  | PotionCore-1.9_for_1.12.2.jar                    | None                                     |
	| LCH   | eapotioncore         | 1.0.2           | EverlastingAbilities-PotionCore-1.12.2-1.0.2.jar | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | farmingforblockheads | 3.1.28          | FarmingForBlockheads_1.12.2-3.1.28.jar           | None                                     |
	| LCH   | fastleafdecay        | v14             | FastLeafDecay-v14.jar                            | None                                     |
	| LCH   | grapplemod           | 1.12.2-v11.1    | grapplemod-v11.1-1.12.2.jar                      | None                                     |
	| LCH   | happylandings        | 1.1.1           | HappyLandings-1.1.1.jar                          | None                                     |
	| LCH   | harvest              | 1.12-1.2.8-25   | Harvest-1.12-1.2.8-25.jar                        | None                                     |
	| LCH   | inventorysorter      | 1.13.3+57       | inventorysorter-1.12.2-1.13.3+57.jar             | None                                     |
	| LCH   | jarm                 | 1.1.1           | Just+A+Raft+Mod-1.1.1.jar                        | None                                     |
	| LCH   | lostquiver           | 1.0 - MC 1.12.2 | lostquiver-1.0.jar                               | None                                     |
	| LCH   | mca                  | 6.1.0           | MCA-1.12.2-6.1.0-universal.jar                   | None                                     |
	| LCH   | multitools           | 1.0             | multitools-1.0.jar                               | None                                     |
	| LCH   | mysticalagriculture  | 1.7.5           | MysticalAgriculture-1.12.2-1.7.5.jar             | None                                     |
	| LCH   | naturescompass       | 1.5.1           | NaturesCompass-1.12.2-1.5.1.jar                  | None                                     |
	| LCH   | recipehandler        | 0.13            | NoMoreRecipeConflict-0.13(1.12.2).jar            | None                                     |
	| LCH   | offlineskins         | 1.12.2-v6       | OfflineSkins-1.12.2-v6.jar                       | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
	| LCH   | oreexcavation        | 1.4.150         | OreExcavation-1.4.150.jar                        | None                                     |
	| LCH   | subcommonlib         | 1.2.0.1         | subcommonlib-sublib-1.12.2-1.2.0.4.jar           | None                                     |
	| LCH   | petbuddy             | $version        | petbuddy-petbuddy-1.12.2-2.4.1.0.jar             | None                                     |
	| LCH   | pixelmon             | 7.3.1           | Pixelmon-1.12.2-7.3.1-universal.jar              | None                                     |
	| LCH   | pixelextras          | 2.5.7           | PixelExtras-1.12.2-2.5.7-universal.jar           | None                                     |
	| LCH   | ptrmodellib          | 1.0.4           | PTRLib-1.0.4.jar                                 | None                                     |
	| LCH   | realistictorches     | 2.1.1           | RealisticTorches-1.12.2-2.1.1.jar                | None                                     |
	| LCH   | rmh                  | 1.0             | RemoveMouseoverHighlight-1.0.jar                 | None                                     |
	| LCH   | corerm               | 1.3.3           | RikMuldsCore_1.3.3.jar                           | None                                     |
	| LCH   | rustic               | 1.1.4           | rustic-1.1.4.jar                                 | None                                     |
	| LCH   | secretroomsmod       | 5.6.4           | secretroomsmod-1.12.2-5.6.4.jar                  | None                                     |
	| LCH   | sit                  | v1.3            | sit-1.12.2-v1.3.jar                              | None                                     |
	| LCH   | speedyhoppers        | 1.1.19          | speedyhoppers-1.1.19.jar                         | None                                     |
	| LCH   | sm                   | 1.1             | Sunglasses+and+more+1.1.jar                      | None                                     |
	| LCH   | camping              | 2.4.3           | TheCampingMod_2.4.3.jar                          | None                                     |
	| LCH   | treechopper          | 1.2.4           | TreeChopper-1.12.2-1.2.4.jar                     | None                                     |
	| LCH   | uppers               | 0.0.6           | Uppers-0.0.6.jar                                 | None                                     |
	| LCH   | villagermarket       | 1.0.1           | villager-market-1.12.2-1.0.1.jar                 | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | whopper              | 1.0.2           | whopper-1.0.2.jar                                | None                                     |
	| LCH   | vt                   | 1.12.2-1.5.6    | VanillaTweaks-1.12.2-1.5.6.jar                   | None                                     |

	Loaded coremods (and transformers): 
Quark Plugin (Quark-r1.6-178.jar)
  vazkii.quark.base.asm.ClassTransformer
offlineskins (OfflineSkins-1.12.2-v6-core.jar)
  lain.mods.skins.init.forge.asm.ASMTransformer
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
CreativePatchingLoader (CreativeCore_v1.10.16_mc1.12.2.jar)
  
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13559 Compatibility Profile Context 26.20.12028.2' Renderer: 'AMD 15D8:C8'
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: AMD 15D8:C8 GL version 4.6.13559 Compatibility Profile Context 26.20.12028.2, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Winthor+Medieval+v3.7+MC+1.12.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 3400G with Radeon Vega Graphics 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.13559 Compatibility Profile Context 26.20.12028.2
	OpenGlRenderer: AMD 15D8:C8
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 8


So what's the verdict?

**Comment by rubensworks** [comment]
Can you try without any other mods installed? Looks like another mod messing with things.

**Comment by RyoStonewell** [comment]
Dude, there are so many other mods, you don't even know. And that still doesn't explain why it worked earlier on the same day. At least... not to me.

**Comment by RyoStonewell** [comment]
Oh, hey, not sure if I was clear with this, but the problems started the second I disabled all totem loot in the mod.

**Comment by rubensworks** [comment]
That definitely sounds like the cause of the problem then. Why do you want to disable the totem item?

**Comment by RyoStonewell** [comment]
I like to cheat and give myself the abilities and two or three other things before using a mod to disable cheats. Anyway, how do I reset the default settings in the mods without actually loading minecraft?

**Comment by rubensworks** [comment]
Just remove the everlasting abilities config file from your config folder to revert to default settings.

**Comment by RyoStonewell** [comment]
Ok, uh... What if it's not in the usual place?

**Comment by rubensworks** [comment]
No idea to be honest. You may have other mods in your pack messing with things.

**Comment by RyoStonewell** [comment]
IT'S WORKIN'!!! Thanks a crap ton, I could hug you!!! The everlasting stuff is one of my most important mod sets.

**Comment by rubensworks** [comment]
No problem
