### ISSUE TITLE
Particle effects issues

### ISSUE THREAD

**Issue by Tearlow** [CyclopsMC/EverlastingAbilities#173]
Right off the bat, this is what the mist/fog that is generated from either Corail tombstone or Treasrure2!'s gravestones. When EverlastingAbilities is loaded. I am not sure if this is related to #160 but particles from using a teleportation key from Corail's result in opaque sprites as well.

![image](https://user-images.githubusercontent.com/786246/86679943-5bbe0680-bffe-11ea-9a3f-f1c5fd82832b.png)

...And this is what it looks like without.

![image](https://user-images.githubusercontent.com/786246/86680658-15b57280-bfff-11ea-8c34-80f8f78ab343.png)

I should point out I load one or the other (Corail or Treasure2) but results in the same issue when you spot a grave of any type. I don't know what else to add so just hola what I could add.

forge-14.23.5.2854
CyclopsCore-1.12.2-1.6.4.jar
EverlastingAbilities-1.12.2-1.5.3.jar
tombstone-4.0.0-1.12.2.jar.jar
GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar
Treasure2-mc1.12.2-f14.23.5.2768-v1.12.0.jar

**Comment by rubensworks** [comment]
Yep, appears to be similar to #160.
