### ISSUE TITLE
Fresh config not breaking haste?

### ISSUE THREAD

**Issue by Tearlow** [CyclopsMC/EverlastingAbilities#174]
Since going past Haste 2 breaks most things why not generate a config file that only allows 2 levels instead?

Currently it allows 5 if im not wrong according to https://github.com/CyclopsMC/EverlastingAbilities/blob/aaf4f200c4f07a19cc021e7118ea560dbb283f94/src/main/java/org/cyclops/everlastingabilities/ability/config/AbilityHasteConfig.java#L27

**Comment by rubensworks** [comment]
Haste higher than 2 still increases mining and attack speed, so may be valuable to have.

**Comment by Tearlow** [comment]
This issue was never meant to be have sent. I must've accidentally clicked send at some point. I was a bit quick to assume it was EverlastingAbilities but after loading it in a single mod environment showed otherwise. I'm still in the process of finding what mod causes the issue. Going past haste 2 literally disables the ability to use right click and thus breaks the character since you cannot use the ability bottle. I can't think of anything but using a NBT tool to strip/edit the character to make it playable again.

So again, sorry about that!
