### ISSUE TITLE
Server Config not working

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/EverlastingAbilities#175]
#### Issue type:

- :bug: Bug

____

#### Short description:

If I edit the Server Config it's not effected. Instead my client side settings are working on the Server.

So if I chance the Xp cost from exp: flight to just 300 instead of 150 in the Server Config file, it's not changing, I can still buy the flight for 1500 XP. Changing it to 300 instead of 150 in my Config file, changes the value on the server as well, but only for me, so its client side.

What could be mentioned, im not playing EverAbil only, its in the Modpack FTB Horizon III, so I dont know if there is a new version, but as I searched about that in the internet and nowhere was an answer, i guess that its still unfixed.

#### Steps to reproduce the problem:

1. Change value from Xp cost in Server Config from EverAbil

2. Join server and nothing should have changed

3. Changing Value from XP cost in Client Config from EverAbil

4. Join server and it should have changed to what youve set

#### Expected behaviour:

The Server Config should overwrite the Client side one, so that every Player has the same settings even if their client sides are different.

____

#### Versions:

- This mod: 1.12.2-1.3.16 (1.3.16)
- Minecraft: 1.12.2
- Forge: 14.23.4.2705

#### Log file:

Nothing to see here

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
The only thing you would be causing with changing the client configs is a client-server desync. Your client may appear to activate an ability, this this ability will actually never really be on your player, and its effects will not take place. Relogging should confirm this.

It's the responsibility of the mod pack maker (and player) to make sure that the client-server configs are in sync. AFAIK this has changed in 1.15 though, where Forge will automatically send configs to clients.
