### ISSUE TITLE
Fire Resistance underwater blindness

### ISSUE THREAD

**Issue by EightBlade** [CyclopsMC/EverlastingAbilities#177]
#### Issue type:

- :bug: Bug 

____

#### Short description:
When I attempt to go underwater while having the fire resist ability the screen will constantly flicker and fog will make things impossible to see.

#### Steps to reproduce the problem:

1. Install mod
2. Install clear water mod
3. Add fire resist ability
4. Go underwater

#### Expected behaviour:
To be able to see

____

#### Versions:

- This mod:  EverlastingAbilities-1.15.2-1.6.3.jar
- Minecraft:  1.15.2
- Forge: 31.2.45

**Comment by rubensworks** [comment]
Thanks for reporting!



<div align="right"><a href="https://github.com/CyclopsMC/EverlastingAbilities/actions/runs/389311250">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>

**Comment by rubensworks** [comment]
> Install clear water mod

That's probably the culprit.
I just tested this in vanilla, and no flickering occurs.
So this clear water mod must be changing things.
