### ISSUE TITLE
Everlasting Abilities crashes immediatedly

### ISSUE THREAD

**Issue by Ncarauj012** [CyclopsMC/EverlastingAbilities#178]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If i try to use the ability bottle / totem the game instantly crashes

#### Steps to reproduce the problem:

1 - Open World
2 - Use Ability Bottle
3 - Minecraft Dies

#### Expected behaviour:

1 - Open World
2 - Use Ability Bottle
3 - Play Normally
____

#### Versions:

- This mod: 1.4.0
- Minecraft: 1.12.2
- Forge: 1.12.2-forge-14.23.5.2854

#### Log file:

https://pastebin.com/9MgnMbGw

**Comment by rubensworks** [comment]
Thanks for reporting!



<div align="right"><a href="https://github.com/CyclopsMC/EverlastingAbilities/actions/runs/413297642">Log</a> | <a href="https://github.com/peaceiris/actions-label-commenter#readme">Bot Usage</a></div>

**Comment by rubensworks** [comment]
You seem to be running several versions behind. Updating to the latest will probably fix your problem.
