### ISSUE TITLE
Crash with Electroblobs Wizardry.

### ISSUE THREAD

**Issue by PercyJames** [CyclopsMC/EverlastingAbilities#179]
#### Issue type: Crash

- :bug: Bug 

____

#### Short description:

when i click the ability bottle my game crashes.

#### Steps to reproduce the problem: 
Step 1: download Cyclops Core 1.12.2- 1.6.0, Electroblobs Wizardry 1.12.2- 4.3.1, and Everlasting Abilities 1.12.2- 1.5.2. 

Step 2: create a new world

Step three: click ability bottle. 

1. ...

#### Expected behaviour:

i expected the bottle to open normally.

____

#### Versions:

- This mod: 1.12.2- 1.5.2
- Minecraft: 1.12.2
- Forge: 14.23.5.2847

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> java.lang.NullPointerException
    at electroblob.wizardry.client.animation.PlayerAnimator.onRenderPlayerPostEvent(PlayerAnimator.java:234)

This looks like a bug in Electroblobs Wizardry, as this mod works just fine in vanilla.
I suggest to open an issue in their tracker.
