### ISSUE TITLE
Client crash

### ISSUE THREAD

**Issue by K4N0** [CyclopsMC/EverlastingAbilities#18]
http://pastebin.com/2vWxvb92

I right clicked the ability totem and it opened the gui.
I clicked on the water breathing ability and then clicked on the tranfer button and it caused the client to crash. I was able to use other abilites so far with no issues.

**Comment by rubensworks** [comment]
Did this happen only this once? Or does it happen every time you try this?

**Comment by K4N0** [comment]
I did receive the ability after the crash. I also attempted to get a haste buff but crashed again. i don't think that crash was related to your mod. It had something to do with creepers and i fixed that. I'll do some more testing and let you know what i find.
