### ISSUE TITLE
Bug with equipped abilities and ability bottle

### ISSUE THREAD

**Issue by Neb2566** [CyclopsMC/EverlastingAbilities#180]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Used abilities dont show up when trying to remove them with ability bottle after relogging the game with optifine installed.

#### Steps to reproduce the problem:

1. Install optiforge and optifine

#### Expected behaviour:

Expected to be able to remove abilities with ability bottle

https://imgur.com/a/zcIKw27

____

#### Versions:

- This mod: 
- EverlastingAbilities-1.16.4-1.6.3
- OptiForge-MC1.16.4-0.4.6
- preview_OptiFine_1.16.4_HD_U_G6_pre12
- Minecraft:  1.16.4
- Forge: 35.1.37

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Install optiforge and optifine

Optifine is known to make very invasive changes that break mods. Unfortunately, I can not make workarounds for this myself. Feel free to report this at the optifine issue tracker.
