### ISSUE TITLE
Custom

### ISSUE THREAD

**Issue by drugpup** [CyclopsMC/EverlastingAbilities#181]
#### Issue type:

- :question: Question 

____

#### Question:

Can You add a feature to add custom abilities from other mods?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
There's an API through which you can add custom abilities, but this requires coding.
