### ISSUE TITLE
How to backup players abilities?

### ISSUE THREAD

**Issue by sawyerfeng** [CyclopsMC/EverlastingAbilities#182]
#### Issue type:

- :question: Question 

____

#### Question:
These abilities are to powerful,and I want to organize an activity, I have to forbidden this mod. I edit false at some of the abilities at config, but when activity was over, I return the config back to normal, players abilities all disappear. I don't know how to fix. I really like this mod, I will be appreciate if you provide me with useful advice. Thanks

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Other than removing the mod, this is not possible by default. Shouldn't be too hard to add a config option to disable all abilities from ticking though.

For reference, this is where abilities tick: https://github.com/CyclopsMC/EverlastingAbilities/blob/master-1.16/src/main/java/org/cyclops/everlastingabilities/EverlastingAbilities.java#L335-L348

<blockquote><img src="https://avatars.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities">CyclopsMC/EverlastingAbilities</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by sawyerfeng** [comment]
Thank you for answer my question!
I tried to remove this mod or disable all abilities.
But when I add or change enable back to normal ,all player's abilities seems disappear.
