### ISSUE TITLE
[Bug] Black particles could been seen around animals without abilities while using SEUS shaders

### ISSUE THREAD

**Issue by Jaywang1999** [CyclopsMC/EverlastingAbilities#183]
While using SEUS-Renewed or especially SEUS PTGI shaders , there would be black particles around animals without abilities. Maybe some shaders couldn't render transparent particle textures correctly, is it possible to fix that by disabling particles instead of set the texture of particles to transparent? I would really appreciate it.

**Comment by rubensworks** [comment]
We already have a config option to disable particles: https://github.com/CyclopsMC/EverlastingAbilities/blob/master-1.16/src/main/java/org/cyclops/everlastingabilities/GeneralConfig.java#L57-L58

<blockquote><img src="https://avatars.githubusercontent.com/u/11808375?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities">CyclopsMC/EverlastingAbilities</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>
