### ISSUE TITLE
Became an Android, now all abilities constantly flash on/off.

### ISSUE THREAD

**Issue by AefRal** [CyclopsMC/EverlastingAbilities#184]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Became android, everlasting abilities started flashing on and off.

While having a bunch of abilities, I became an Android through Matter Overdrive mod.
Immediately I noticed it, namely because it was night and night vision was the most obvious visual effect.
Upon opening my inventory, I saw that all abilities were flashing on and off repeatedly. 
Night-vision turned dark caves into a stop motion film, or rave.

#### Steps to reproduce the problem:

1. Have some abilities,
2. Become an Android(Matter Overdrive).

#### Expected behaviour:

____The abilities to be stable.

#### Versions:

**- This mod:** EverlastingAbilities-1.12.2-1.5.3
- EverlastingAbilities-PotionCore-1.12.2-1.0.2
- CyclopsCore-1.12.2-1.6.6
- MatterOverdrive-1.12.2-0.7.1.0-universal
**- Minecraft:** 1.12.2
**- Forge:** 14.23.5.2847

https://imgur.com/a/8f6gwlI

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can't reproduce without other mods.

If this only occurs for you with MO, then I would suggest reporting this on their issue tracker, it's possible that they are not invoking `LivingEvent.LivingUpdateEvent` correctly.

If this also occurs without other mods for you, please report back here with a reproducible setup.
