### ISSUE TITLE
Crash when putting Bonemealer on with totem

### ISSUE THREAD

**Issue by hjpoe** [CyclopsMC/EverlastingAbilities#185]
#### Issue type:

- :bug: Bug 

____

#### Short description:
I found a Bonemealer totem in a chest, tried to put it on, and my game crashed.

#### Steps to reproduce the problem:

1. Find Bonemealer totem
2. Have enough XP, and try to put it on
3. Game crashes, and cannot be logged back into

#### Expected behaviour:

I expected the game not to crash. 

____

#### Versions:

- This mod: 1.6.3
- Minecraft: 1.15.2
- Forge: 31.2.48

#### Log file:
https://pastebin.com/csQht1dM

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
> Minecraft: 1.15.2

This MC version is not being maintained unfortunately.
I recommend updating to 1.16.x.
