### ISSUE TITLE
Suggestion: Remove or Reapply all command

### ISSUE THREAD

**Issue by Iashar** [CyclopsMC/EverlastingAbilities#186]
So I've noticed that when adding and removing some mods, the abilities appear to de-sync in a manner making them not available to place back into an ability bottle. I figured that's fine, I'll just remove them all and reacquire them. But there is no option for that or re-applying them, making it far more difficult to fix the glitch. I figure reapplying them would work as well, since I seem to lose my step assist regularly when altering mods as well, but reapplying it seems to fix it, since I've got that one in a bottle. 

When I list my abilities with the command, it brings them all up, (aside from the step assist) but there's some kind of disconnect between that and what the totems/bottles read, meaning no putting it back in the bottle. 

Let me know if I can assist with this in any way!

**Comment by rubensworks** [comment]
I'm not sure if I understand the issue. But I suspect everything to be working as intended.

> the abilities appear to de-sync in a manner making them not available to place back into an ability bottle.

Are you sure that the max level of certain abilities is not exceeded? You may have to create additional bottles in that case.

> I seem to lose my step assist regularly when altering mods as well

This may be because of some mod in your pack messing with step height in an incorrect manner. Which is not something I can fix on my end.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by Iashar** [comment]
Even with an empty ability bottle, they're not moveable, though they're active according to the effects screen in the inventory,
and the list abilities command.
It's almost as if they've been added to the player permanently, as I could add them -again- with a totem of the same type.
But what I was suggesting was a command to remove all abilities, or to refresh them, like stopping them and then reapplying them to the player, so that they're recognized by the rest of the mod again.

**Comment by rubensworks** [comment]
> But what I was suggesting was a command to remove all abilities, or to refresh them, like stopping them and then reapplying them to the player, so that they're recognized by the rest of the mod again.

That's what should be happening upon every game restart. If that's not working, then a command to force it won't either.

If this only occurs with other mods, I suspect some mod in your pack is breaking player capabilities somehow. AFAICS, there's nothing I can do about that on my end. I would suggest adding/removing mods from your pack to determine the mod that causes it.

**Comment by Iashar** [comment]
It's not any one mod, it happens if I add or remove -any- mod. As if to say, a reconfiguration of the configuration of the game alters how the abilities work. 
For now the only real reliable way to keep it from happening is to bottle all my abilities if I alter the game.
Also, thank you for explaining that. I'll keep it in mind.
Adding abilities using commands acts in the same manner, they aren't bottle-able.
