### ISSUE TITLE
Game crashed after using abilities

### ISSUE THREAD

**Issue by iShadowFrost** [CyclopsMC/EverlastingAbilities#187]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I recently started a world and everything was working fine until i use the bonemealer abilities, for some reason my game crashed and i can't manage to launch this world again. So i tried with a new world and the same happened. I also tried to remove all the mods but with only this mods it still crash the game.

#### Steps to reproduce the problem:

Take the bonemealer abilities and try to use it to get the effect.

#### Expected behaviour:

I expected to have a bonemeal effect around me.

____

#### Versions:

- This mod: EverlastingAbilities-1.15.2-1.6.3
- Minecraft: 1.15.2
- Forge: 31.2.47

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
So what's the crash?...

**Comment by rubensworks** [comment]
Ah, I see you're using MC 1.15, which is not supported anymore. Please update to 1.16 and try again.
