### ISSUE TITLE
When combining totems it seems to always give me the same outcomes

### ISSUE THREAD

**Issue by OHQSaucey** [CyclopsMC/EverlastingAbilities#189]
#### Issue type:

- :question: Question 

____

#### Question:

I am not sure if it's just my config being too heavily customized and something isn't working properly with how I have it, or if this is actually a bug.

So I love this mod but I wanted to make it more of a gamble to obtain the higher tier totems on my server. I started off by choosing which totems I wanted enabled and disabled, afterwards I adjusted some of the rarities of certain totems and their availability. I didn't edit any of the totems "xpPerLevel" or "maxLevel".

So how I have it set up is like this:

```
| Key |

C - Can be obtained by combining any 5 totems in a crafting grid.
L - Can be obtained in loot chests.
S - Can be obtained by spawning mobs.
1/50 chance for mobs to have abilities.
When combining totems, you have a 25% chance of getting a higher rarity totem.
```

```
| Enabled |

Absorbtion      - Rarity: 3 | Max Level: 5 | Availability: C
Bonemealer      - Rarity: 2 | Max Level: 5 | Availability: C L S
Fertility       - Rarity: 1 | Max Level: 3 | Availability: C L S
Fire_Resistance - Rarity: 2 | Max Level: 1 | Availability: C
Flight          - Rarity: 3 | Max Level: 1 | Availability: C
Haste           - Rarity: 0 | Max Level: 5 | Availability: C L S
Invisibility    - Rarity: 3 | Max Level: 1 | Availability: C
Jump_Boost      - Rarity: 0 | Max Level: 5 | Availability: C L S
Luck            - Rarity: 2 | Max Level: 3 | Availability: C L S
Magnetize       - Rarity: 1 | Max Level: 5 | Availability: C L S
Night_Vision    - Rarity: 3 | Max Level: 1 | Availability: C
Regeneration    - Rarity: 3 | Max Level: 3 | Availability: C
Resistance      - Rarity: 3 | Max Level: 3 | Availability: C
Saturation      - Rarity: 3 | Max Level: 3 | Availability: C
Speed           - Rarity: 0 | Max Level: 5 | Availability: C L S
Step_Assist     - Rarity: 0 | Max Level: 3 | Availability: C L S
Strength        - Rarity: 2 | Max Level: 5 | Availability: C L S
Water_Breathing - Rarity: 2 | Max Level: 1 | Availability: C
Weakness        - Rarity: 2 | Max Level: 3 | Availability: C L S
```

```
| Disabled |

Blindness
Glowing
Hunger
Levitation
Mining_Fatigue
Nausea
Poison
Power_Stare
Slowness
Unluck
Wither
```

Below are some of the combinations I've done, no matter if you do a mixture of jump boost, step assist, speed or haste it always gives me the same outcomes. Same goes with the higher tier totems, they always give me water breathing/absorbtion and nothing else.

- 5 bonemealer totems always gives me water breathing.
- 5 water breathing totems always give me water breathing.
- 1 bonemealer, 1 luck, 1 strength, 1 weakness and 1 water breathing combined always gives me water breathing.
- 5 jump boost totems always gives me step assist.
- 5 step assist totems always gives me step assist.
- 5 speed totems always give me step assist.
- 5 haste totems always gives me step assist.
- 5 magnetize totems always gives me magnetize.
- 5 luck totems always gives me water breathing.
- 5 strength totems always gives me water breathing.

Basically the totems I am able to obtain from drops and the only one I am able to combine up to is all I am able to get. All of the other totems are not able to be obtained. You are able to advance up in rarities, but it's always going to be the same ones no matter what you do. 

5 Haste (rarity 0) > 5 Magnetize (rarity 1) > 5 Water Breathing (rarity 2) > 5 Absorbtion (rarity 3) > 1 Absorbtion (always)

The only rarity 2 I can obtain through crafting is water breathing and the only rarity 3 I can obtain through crafting is absorbtion. I've never been able to get fire resistance as an outcome or any other rarity 3 totem on the list. I've used multiple different crafting grids from a couple of different mods, including the normal crafting table obviously. Still no change in the outcome.

Server/Client: Minecraft 1.16.5 | Forge Version 36.0.43
(If any more information is needed I will be happy to provide more.)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Could you check without any other mods installed?
Might very well be a bug.

**Comment by OHQSaucey** [comment]
Booted up a fresh instance with just this mod on there with my config. It is still doing it, although this time it's giving me invisibility instead of absorbtion as the only rarity 3. When I combine 5 of those it still only gives me invisibility.
