### ISSUE TITLE
Bonemealer crashes game

### ISSUE THREAD

**Issue by hypercanetornado** [CyclopsMC/EverlastingAbilities#190]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Whenever the "Bonemealer" Ability is added to a character, the game crashes and the world is inaccessible.

#### Steps to reproduce the problem:

Open new world→Get bonemealer totem→get levels→apply bonemealer totem→Watch as the game descends into oblivion.

1. ...

#### Expected behaviour:

The bonemealer effect should be activated, bonemealing surrounding crops.

____

#### Versions:

- This mod: EverlastingAbilities-1.15.2-1.6.3.jar
- Minecraft: 1.15.2
- Forge: 1.15.2-forge-31.2.49
Mod List: 
		tetra-1.15.2-2.18.1.jar Tetra {tetra@1.15.2-2.18.1 DONE}
		CyclopsCore-1.15.2-1.9.0.jar Cyclops Core {cyclopscore@1.9.0 DONE}
		QuarkOddities-1.15.2.jar Quark Oddities {quarkoddities@1.15.2 DONE}
		inventorysorter-1.15.2-17.0.0.jar Simple Inventory Sorter {inventorysorter@17.0.0 DONE}
		jei-1.15.2-6.0.0.4.jar Just Enough Items {jei@6.0.0.4 DONE}
		OptiForge-MC1.15.2-0.1.32.jar OptiForge {optiforge@0.1.32 DONE}
		Metal-Barrels-Mod-1.15.2.jar Metal Barrels {metalbarrels@2.1 DONE}
		EverlastingAbilities-1.15.2-1.6.3.jar EverlastingAbilities {everlastingabilities@1.6.3 DONE}
		Abnormals-Core-1.15.2-1.0.6.jar Abnormals Core {abnormals_core@1.0.6 DONE}
		Uppers-0.2.12.jar Uppers {uppers@0.2.12 DONE}
		Mekanism-Mod-Core-1.15.2.jar Mekanism {mekanism@9.10.9 DONE}
		Essentials-Mod-1.15.2.jar Essentials {essentials@1.15.2-2.7.3 DONE}
		create-mc1.15.2_v0.3e.jar Create {create@mc1.15.2_v0.3e DONE}
		Waystones_1.15.2-6.0.2.jar Waystones {waystones@6.0.2 DONE}
		ForgeEndertech-1.15.2-6.0.3.2-build.0042.jar Forge Endertech {forgeendertech@6.0.3.2 DONE}
		AdFinders-1.15.2-4.0.5.0-build.0020.jar Advanced Finders {adfinders@4.0.5.0 DONE}
		mgui-1.15.2-2.1.1.jar mgui {mgui@2.1.1 DONE}
		light-overlay-4.7.2.jar Light Overlay Forge {lightoverlay-forge@NONE DONE}
		journeymap-1.15.2-5.7.0b3.jar Journeymap {journeymap@5.7.0b3 DONE}
		Controlling-6.1.5.6.jar Controlling {controlling@6.1.5.6 DONE}
		Placebo-1.15.2-3.1.0.jar Placebo {placebo@3.1.0 DONE}
		comforts-FORGE-1.15.2-2.0.0.4.jar Comforts {comforts@FORGE-1.15.2-2.0.0.4 DONE}
		NaturesCompass-1.15.2-1.8.5.jar Nature's Compass {naturescompass@1.15.2-1.8.5 DONE}
		Powah-1.15.2-1.1.14.jar Powah {powah@1.1.14 DONE}
		Potions-Master-Mod-1.15.2.jar Potions Master {potionsmaster@0.1.8 DONE}
		Bookshelf-1.15.2-5.6.40.jar Bookshelf {bookshelf@5.6.40 DONE}
		u_team_core-1.15.2-3.0.2.169.jar U Team Core {uteamcore@3.0.2.169 DONE}
		mcjtylib-1.15-4.1.11.jar McJtyLib {mcjtylib@1.15-4.1.11 DONE}
		Apotheosis-1.15.2-3.3.8.jar Apotheosis {apotheosis@3.3.8 DONE}
		Mekanism-Mod-Generators-1.15.2.jar Mekanism: Generators {mekanismgenerators@9.10.9 DONE}
		Hwyla-Mod-1.15.2.jar Waila {waila@version DONE}
		JEITweaker-1.15.2-1.0.1.3.jar JEI Tweaker {jeitweaker@1.0.1.3 DONE}
		inventorypets-2.0.12.jar Inventory Pets {inventorypets@2.0.12 DONE}
		forge-1.15.2-31.2.49-universal.jar Forge {forge@31.2.49 DONE}
		ironchest-1.15.2-10.0.3.jar Iron Chests {ironchest@1.15.2-10.0.1 DONE}
		forge-1.15.2-31.2.49-client.jar Minecraft {minecraft@1.15.2 DONE}
		The-Endergetic-Expansion-1.15.2-v1.3.2.jar The Endergetic Expansion {endergetic@1.3.2 DONE}
		repurposedstructures-1.15.2-1.7.2.jar Repurposed Structures {repurposed_structures@1.15.2-1.7.2 DONE}
		EnchantmentDescriptions-1.15.2-2.0.9.jar EnchantmentDescriptions {enchdesc@2.0.9 DONE}
		swingthroughgrass-1.15.2-1.4.1.jar SwingThroughGrass {swingthroughgrass@1.15.2-1.4.1 DONE}
		titanium-1.15.2-2.4.0.jar Titanium {titanium@2.4.0 DONE}
		useful_railroads-1.15.2-1.4.2.29.jar Useful Railroads {usefulrailroads@1.4.2.29 DONE}
		phosphor-forge-mc1.15.2-0.5.2+build.4.jar Phosphor {phosphor@0.5.2+build.4 DONE}
		Mekanism-Mod-Additions-1.15.2.jar Mekanism: Additions {mekanismadditions@9.10.9 DONE}
		valhelsia_structures-15.0.3a.jar Valhelsia Structures {valhelsia_structures@15.0.3a DONE}
		Lollipop-1.15.2-1.0.15.jar Lollipop {lollipop@1.0.15 DONE}
		Iron-Furnaces-Mod-1.15.2.jar Iron Furnaces {ironfurnaces@2.0.3 DONE}
		AdLods-1.15.2-3.0.3.0-build.0035.jar Large Ore Deposits {adlods@3.0.3.0 DONE}
		portality-1.15.2-2.1.2-aaa257f.jar Portality {portality@2.1.2 DONE}
		FastWorkbench-1.15.2-3.1.1.jar FastWorkbench {fastbench@3.1.1 DONE}
		config-2-3.0.jar Cloth Config v2 API {cloth-config2@3.0 DONE}
		AutoRegLib-1.5-40.jar AutoRegLib {autoreglib@1.5-40 DONE}
		Torcherino-Mod-1.15.2.jar Torcherino {torcherino@10.0.1 DONE}
		StorageDrawers-1.15.2-7.0.3.jar Storage Drawers {storagedrawers@1.15.2-7.0.3 DONE}
		OreExcavation-1.7.151.jar Ore Excavation {oreexcavation@NONE DONE}
		FluxNetworks-1.15.2-5.0.1-2.jar Flux Networks {fluxnetworks@1.15.2-5.0.1-2 DONE}
		tombstone-4.4.1-1.15.2.jar Corail Tombstone {tombstone@4.4.1 DONE}
		Quark-r2.1-245.jar Quark {quark@r2.1-245 DONE}
		Expanded-Storage-Mod-1.15.2.jar Expanded Storage {expandedstorage@2.0.0 DONE}
		noRecipeBook_v1.5.4formc1.15.2.jar No Recipe Book {norecipebook@1.5.4 DONE}
		Mekanism-Mod-Tools-1.15.2.jar Mekanism: Tools {mekanismtools@9.10.9 DONE}
		FastFurnace-1.15.1-3.0.0.jar FastFurnace {fastfurnace@3.0.0 DONE}
		AppleSkin-mc1.15.2-forge-1.0.14.jar AppleSkin {appleskin@1.0.14 DONE}
		FastLeafDecay-v22.1.jar FastLeafDecay {fastleafdecay@v22.1 DONE}
		tinyprogressions-1.15.2-4.0.8.jar Tiny Progressions {tp@4.0.8 DONE}

#### Log file:

https://pastebin.com/MPq3WHDt

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by hypercanetornado** [comment]
Of course

**Comment by rubensworks** [comment]
> Minecraft: 1.15.2

There's your problem.
You should update to 1.16.
1.15 is not being maintained anymore.

**Comment by hypercanetornado** [comment]
Darn it. The mudpack I’ve created doesn’t support 1.16… thank for checking on it though.

Sincerely-
David B. Shields
