### ISSUE TITLE
Flight not working with Create : Stuff Additions installed

### ISSUE THREAD

**Issue by ZEROX7** [CyclopsMC/EverlastingAbilities#192]
minecraft 1.16.5
forge 36.1.24
EverlastingAbilities-1.16.5-1.7.1.jar
CyclopsCore-1.16.5-1.11.6.jar
create-stuff-additions1.16.5_v1.0.3.jar
if create addiotns is installed flight ability stops working

**Comment by rubensworks** [comment]
Could you report this to their issue tracker? Sounds like an issue on their end.
