### ISSUE TITLE
Waterbreathing Ability Not Working

### ISSUE THREAD

**Issue by PhoenixExitium** [CyclopsMC/EverlastingAbilities#193]
The Waterbreathing Totem ability isnt working for me, it was working but stopped randomly. Im hoping it is a mod compatability issue.

**Comment by rubensworks** [comment]
@PhoenixExitium Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by rubensworks** [comment]
Can you try reproducing without other mods installed?
