### ISSUE TITLE
Weakness ability (from lv 1) makes some mobs (zombie, spider and enderman f.e.) deal no damage at all

### ISSUE THREAD

**Issue by LitChocoDonut** [CyclopsMC/EverlastingAbilities#194]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Adding weakness to abilities makes some aggressive mobs deal 0 damage.  Any attacks are made.

#### Steps to reproduce the problem:

Adding level 1 weakness and try to be hit by zombie, spider or enderman. (Skeletons deal damage because of projectile attacks, same goes to creepers and witch)

#### Expected behaviour:

Though it will only reduce the amount of damage some mobs could deal to player.

____

#### Versions:

- This mod: EverlastingAbilities-1.16.5-1.7.1
- Minecraft: 1.16.5
- Forge: 36.1.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I would guess this aligns with Vanilla behaviour of weakness potions? Can you confirm?

**Comment by LitChocoDonut** [comment]
In fact, weakness potion makes the same with those mobs

**Comment by rubensworks** [comment]
Then this seems like intended behaviour to me, as this mod just applies Vanilla potion effects.
