### ISSUE TITLE
Bonemeal Totem

### ISSUE THREAD

**Issue by imeangay** [CyclopsMC/EverlastingAbilities#195]
#### Issue type:

- :bug: Bug 

____

#### Short description:

It doesn't seem to work.

#### Steps to reproduce the problem:

Just try to use it on crops, or anything.. nothing really happens even on level 5, I even have my game open right as I'm writing this, and no progress really happens besides the normal tick rate

#### Expected behaviour:

The totem should be bonemealing crops near me.

____

#### Versions:

- This mod: EverlastingAbilities-1.16.5-1.7.1
- Minecraft: 1.16.5
- Forge: 36.2.0 G7

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Are you holding shift?...

**Comment by imeangay** [comment]
Was unaware you needed to hold shift, please update your description to say so.

However, this doesn't change anything, plants still don't grow.

**Comment by rubensworks** [comment]
Are you using any other mods? If so, could you try reproducing without them?

**Comment by imeangay** [comment]
Yes, i am using mods, I went ahead and took out all my mods that are not required to make this one work, and.. nothing happens, holding shift does nothing, they don't advance any stages or change growth or anything.

**Comment by rubensworks** [comment]
Thanks for checking!
