### ISSUE TITLE
Nerf ot customize Regeneration

### ISSUE THREAD

**Issue by imeangay** [CyclopsMC/EverlastingAbilities#196]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

Hi! Love your mod, lot of fun things to mix and match, on the more combat side of things, regeneration makes you insanely tanky even with no armor.. 

i.e : Normal regeneration level 1 takes approx 0:45 seconds to heal 9 total hearts, or 18 health out of 20

The totem regeneration heals approx 1.5 hearts per second, approx. just under 8 seconds for a full heal, it even out heals poison II !

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
Should be possible to reconfigure now with the datapack functionality.
