### ISSUE TITLE
Unable to Remove Abilities From Character

### ISSUE THREAD

**Issue by Erabior** [CyclopsMC/EverlastingAbilities#199]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I found several abilities from dungeons and mobs that I used the totems to apply to myself. I am now unable to move them to the ability bottle. This is resolved after a re-log

#### Steps to reproduce the problem:

1. get an ability totem
2. apply the totem
3. open the ability bottle
4. only able to move a few abilities and cannot move more than one level of abilities that I have a few levels in.
5. re-log
6. everything functions as normal

#### Expected behaviour:

the inability to move abilities from the character to the ability bottle for certain abilities until after a re-log

____

#### Versions:

- This mod: EverlastingAbilities-1.18.1-1.7.2
- Minecraft: 1.18.1
- Forge: 39.0.6

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Each ability has a stack limit, so the bottle can not take more than that amount per ability. Are you sure you're not running into that?

**Comment by rubensworks** [comment]
Can't reproduce this myself. In case anyone has any additional information, feel free to comment.
