### ISSUE TITLE
Every single equipped ability is lost on death

### ISSUE THREAD

**Issue by Erabior** [CyclopsMC/EverlastingAbilities#200]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Every single equipped ability is lost(deleted) on death

#### Steps to reproduce the problem:

1.equip any number of abilities
2.die

#### Expected behaviour:

every equipped ability will be dropped and destroyed even though the config is set to only lose one ability

____

#### Versions:

- This mod: EverlastingAbilities-1.18.1-1.7.2
- Minecraft: Minecraft: 1.18.1
- Forge: Forge: 39.0.6

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by EddyBuhler** [comment]
I'm experiencing the same. I do have a good few other mods installed, too, though.

Versions:
This mod: EverlastingAbilities-1.18.1-1.7.2
Minecraft: Minecraft: 1.18.1
Forge: Forge: 39.0.9
