### ISSUE TITLE
Chance config

### ISSUE THREAD

**Issue by Eltigueur** [CyclopsMC/EverlastingAbilities#201]
#### Issue type:
I want to change the config file so I use notepad ++ but when I chose it I got many dark "null" or "esc" ... Don't know how to make it so I can see everything, i know nothing in codding and computer :s
- :question: Question 
____

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
This is not really the proper place for these kinds of questions. I suggest to ask support in the Forge or Cyclops Discord channels, they will be able to help you.
