### ISSUE TITLE
Loot iD

### ISSUE THREAD

**Issue by DB-alfa** [CyclopsMC/EverlastingAbilities#202]
#### Issue type:

- :question: Question 

____

#### Question:
i want to make the totems drop as the loot of another mod called infernal mobs 
the thing is that i'm not sure what name of the totems to put in the config 
since i want different rarities for different ranks of infernal mobs 

still testing if i messed something up but putting in the loot pool: "everlastingabilities:abilityTotem_speed_1" didn't seem to work..

What item name should i try to insert there?

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
This is not easily possible at the moment.
However, you should be able to inspect the NBT contents of each totem using external mods, and use that in the loot table.

Related to #140 and #124.
