### ISSUE TITLE
invisibility blinks

### ISSUE THREAD

**Issue by krjencik** [CyclopsMC/EverlastingAbilities#203]
#### Issue type:

- :bug: Bug 

____

#### Short description:
when using invisibility my skin blinks

#### Steps to reproduce the problem:
take invisibility totem and put the ability onto your character

1. ...

#### Expected behaviour:
be invisible (i dont know if its intended be invisible all the time or just only when not wearing armor)

____

#### Versions:

- This mod: 1.7.3
- Minecraft: 1.18.1
- Forge:  39.0.66

#### Log file:
Im not skilled enough to know if the file is needed also just for bugs that arent crashes - like this one

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Can't reproduce this myself unfortunately.

The only reason I can think of this happens, is if your server is skipping many ticks, which would also cause many other things to break.

Otherwise, another mod in your pack may be breaking things.
