### ISSUE TITLE
Any way to disable players spawning with an Ability Bottle?

### ISSUE THREAD

**Issue by Z4RM** [CyclopsMC/EverlastingAbilities#204]
#### Issue type:

- :question: Question 

____

#### Question:

All is in the title 😅 : **Any way to disable players spawning with an Ability Bottle?**
Thank you in advance !

Cordially,
Z4RM

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
This issue was resolved in Discord:

> max rarity, set to -1
