### ISSUE TITLE
mod conflict with Dark Paintings

### ISSUE THREAD

**Issue by MoonMoonShark** [CyclopsMC/EverlastingAbilities#205]
#### Issue type:

- :bug: Bug 

____

#### Short description:

this is one of the most unexpected bugs i've seen. when running Everlasting Abilities alongside Dark Paintings, there is some kind of problem with the configs where loot chests try to add totems, even when disabled in config files. if any totem is not individually listed as obtainableOnLoot = false, that totem appears in loot chests. when all totems are set to false, as well as #If totems should spawn in loot chests. lootChests = false, the chest can't open, and an error appears in the log. if you keep trying to open it, it will eventually reroll without a totem and open.

`java.lang.IllegalStateException: No abilities were registered, at least one ability must be enabled for this mod to function correctly.`

admittedly, i'm not sure if this problem is with Everlasting Abilities or Dark Paintings.

#### Steps to reproduce the problem:

1. Make new game with only Everlasting Abilities. 
2. Set `lootChests = false` globally, as well as `obtainableOnLoot = false` for every individual totem
3. Find dungeon, and open chests to verify mod is working correctly: no totems spawn and no errors are recorded.
4. Add Dark Paintings to world.
5. Find dungeon and try to open chests. Some will open correctly, but most throw errors and don't open until several tries.

alternately, if lootChests is set to false but any individual totems are set to loot = true, that totem will appear in chests, even though the global setting says not to. i set "Speed" to "true" as a test, and got 16 copies of that totem in 3 chests.

#### Expected behaviour:

when config is set to not allow totems in loot chests, they shouldn't spawn in loot chests, or cause errors.

____

#### Versions:

- Everlasting Abilities: EverlastingAbilities-1.18.2-1.8.0.jar
- Cyclops Core: CyclopsCore-1.18.2-1.15.1.jar
- Dark Paintings: DarkPaintings-Forge-1.18.2-10.0.3.jar
- Minecraft: 1.18.2
- Forge: 40.1.60
- Modpack: https://www.curseforge.com/minecraft/modpacks/the-lighthouse/files/3874929

#### Log file:

Latest Log: [latest.log](https://github.com/CyclopsMC/EverlastingAbilities/files/9119178/latest.log) (error repeats 3 times, as i opened 4 chests and got errors with 3 of them)
Config: https://pastebin.com/DTQJXSmz

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by MoonMoonShark** [comment]
happy to help! i'm really excited to get to use this mod in our modpack. i'm using the abilities as rewards for FTB Quests, so i don't want them to load into chests, but only be acquired as rewards.

**Comment by rubensworks** [comment]
The newly released version should fix the problem. Let me know if it would still fail on your end.

**Comment by MoonMoonShark** [comment]
excellent! thank you so very much! tested and so far have had no errors on chest opening.
