### ISSUE TITLE
has failed to load correctly

### ISSUE THREAD

**Issue by krjencik** [CyclopsMC/EverlastingAbilities#206]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Minecraft wont load

#### Steps to reproduce the problem:
download forge 41.0.98
download this mod 
run Minecraft

1. ...

#### Expected behaviour:
See the main menu

____

#### Versions:

- This mod: 1.8.0
- Minecraft: 1.19
- Forge: 41.0.98

#### Log file:
https://gist.github.com/krjencik/8d8b3f57560b364701d2913ba22fd637#file-everlastingabilitieswontload-log

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
This is due to some breaking changes that Forge did.
Basically all mods have to be rebuilt for 1.19 with these recent Forge changes, so best to downgrade Forge for now until all mods have been ported.

**Comment by rubensworks** [comment]
Fixed in the latest release.
