### ISSUE TITLE
Add new Effects via datapacks

### ISSUE THREAD

**Issue by Firemaster640** [CyclopsMC/EverlastingAbilities#207]
Hallo,
is it possible to add more effects ( various Effects from other Mods) as a data pack? Unfortunately I don't really know java, so I couldn't write a complex mod either.
:-)

**Comment by rubensworks** [comment]
Not possible at the moment unfortunately, this would require a rewrite of the mod.

**Comment by Firemaster640** [comment]
One quick Idea: Not a rewrite from this mod, a creation of an Addon that makes it possible.

**Comment by rubensworks** [comment]
This is now possible in the 2.x version of this mod.
