### ISSUE TITLE
How do I limit the amount of abilities someone can have equipped at a time?

### ISSUE THREAD

**Issue by KhojinKurusu** [CyclopsMC/EverlastingAbilities#208]
My friend and I recently made our own modpack, and purchased a server that we want to go public with, but we think we should nerf how many abilities people can have equipped at a time. Is there any way to do that in the config files? and if so, where in the config files do we look?

**Comment by rubensworks** [comment]
Yes, this can be edited in the config files. (don't remember which key exactly, but it should be in the descriptions)
