### ISSUE TITLE
Can i add other mobs from alexsmobs to the config?

### ISSUE THREAD

**Issue by Minecing** [CyclopsMC/EverlastingAbilities#209]
#### Issue type:

- :question: Question 

____

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Best to ask this to the alex mobs developers, as I don't know what their entity names are either.
