### ISSUE TITLE
Changing config maxlevel to less than default does not work

### ISSUE THREAD

**Issue by Phonavis** [CyclopsMC/EverlastingAbilities#211]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Config Maxlevels don't actually work, only tested in SP, only tested going below the default level
Tested with Resistance, Saturation, Regeneration, and Invisibility

#### Steps to reproduce the problem:
Change maxlevel for something in the config, only tested going below the default level

#### Expected behaviour:
The ability to cap the level below the default

#### Versions:
Minecraft 1.19.2
Forge 43.1.64
Everlasting Abilities 1.19.2-1.8.2
CyclopsCore 1.19.2-1.17.2

#### Log file:

https://gist.github.com/Scarlet-Phonavis/56405782855b54cec300f31573637b5a

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Aenye** [comment]
Also have had this bug, it seems that the newer versions of forge for some reason do not use the mod config.

Details:
MC 1.19.2
Forge 43.2.2
CyclopsCore-1.19.2-1.17.2 (also tried with CyclopsCore-1.19.2-1.17.0)
EverlastingAbilities-1.19.2-1.8.2

Tried deleting the config file. A new one is generated and while changes can be saved to it, they do not takeeffect. Increasing/decreasing max levels, totem drop rate, etc. does not work. Not sure if that helps, but I have not had this issue with Forge 43.1.43 or earlier versions and am only experiencing it after updating. Configs for other mods seem to be working properly.

**Comment by rubensworks** [comment]
Can you both try this without any other mods installed?

**Comment by Aenye** [comment]
Tried with only CyclopsCore and EverlastingAbilities, but the issue persists.
