### ISSUE TITLE
Booted by world/server when given operator permissions (cheats are enabled)

### ISSUE THREAD

**Issue by Xman102003** [CyclopsMC/EverlastingAbilities#213]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem: 

1. Join while having operator permissions or be given operator permissions while already in the server/world.

#### Expected behaviour:

It's expected to not get booted off the server when given operator permissions.

#### Versions:

- This mod: 1.19-1.8.2
- Minecraft: 1.19
- Forge: 1.19-forge-41.1.0

#### Log file:

![Error thingy](https://user-images.githubusercontent.com/63612943/212432788-8e2bcde7-0b54-45bb-8ecb-2a0cbbcbc51c.png)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
What indication do you have that this issue is caused by this mod?
Do you have any other mods installed?
If so, can you reproduce it with just this mod installed?
