### ISSUE TITLE
[1.16.5]]]]]]]]]

### ISSUE THREAD

**Issue by Sailorboi99** [CyclopsMC/EverlastingAbilities#214]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I attempted to launch up my dedicated server, when after a few seconds Everlasting Abilities will cause it to shutdown. It didn't have issues before

#### Steps to reproduce the problem:

1. Run

#### Expected behaviour:

____

#### Versions:

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Sailorboi99** [comment]
Oops, wasn't finished, the ] key ended up hitting my enter key at the same time, sorry

**Comment by Sailorboi99** [comment]
[crash-2023-01-22_02.16.15-fml.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/10473909/crash-2023-01-22_02.16.15-fml.txt)


I am running:
EverlastingAbilities 1.8.0
Minecraft 1.16.5
Forge 36.2.34

**Comment by rubensworks** [comment]
Can you try without any other mods installed. Looks like something is severely broken in your setup, since the `org/cyclops/everlastingabilities/capability/AbilityStoreConfig` class is unavailable.

Are you sure you've downloaded this mod from either curseforge or modrinth?

**Comment by Sailorboi99** [comment]
If downloading it through the Curseforge launcher counts, then yes.

I've backed up the server files and attempted to run it on a new world, it failed to launch.

[crash-2023-01-23_04.35.44-fml.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/10478416/crash-2023-01-23_04.35.44-fml.txt)

**Comment by Sailorboi99** [comment]
I decided to see if copying and replacing the mod file from Curseforge into my server mods folder would fix it, it did for some reason. I have no idea how. But if needed in the future I have a copy of the server folder with the broken mod file still in it.

**Comment by rubensworks** [comment]
Ok, then it was just a corrupted mod jar.
