### ISSUE TITLE
crashing during startup

### ISSUE THREAD

**Issue by tony2013fl** [CyclopsMC/EverlastingAbilities#215]
#### Issue type:

- :bug: Bug 

____

#### Short description:

tried to add it to 15 other 1.19.3 modpacks and it crashed every one of them on startup
#### Steps to reproduce the problem:

1. just add your mods to another pack and start

#### Expected behaviour:

____

#### Versions: latest 1.19.3

- This mod: 
- Minecraft: 
- Forge:

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Please share the crashlog.

**Comment by tony2013fl** [comment]
this was the last time i tried
[crash-2023-01-25_05.54.08-fml.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/10500567/crash-2023-01-25_05.54.08-fml.txt)

**Comment by tony2013fl** [comment]
sorry i hit the close comment just ment to send the log

**Comment by rubensworks** [comment]
> Mod everlastingabilities requires cyclopscore 1.17.3 or above

There's your problem.
