### ISSUE TITLE
some effects disappeared

### ISSUE THREAD

**Issue by 5uuiram** [CyclopsMC/EverlastingAbilities#216]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

IDK

#### Expected behaviour:

The effects have disappeared from my active effects list, and some effects are gone. I can't say what happened to make it occur. I noticed it when I logged into my server.

____

#### Versions:

- This mod: 1.8.2
- Minecraft: 1.19.2
- Forge: 1.19.2 .43.2.3

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
If there's no way to reproduce the problem, there's nothing I can do on my end unfortunately.
If you would gain more information in the future, please share it here, and we can re-open the issue.
