### ISSUE TITLE
night vision flicker timing issue

### ISSUE THREAD

**Issue by violetkitty87** [CyclopsMC/EverlastingAbilities#217]
Issue type:
🐛 Bug
Short description:
Night Vision Flicker

Steps to reproduce the problem:
Just equip the totem and it times out after 13 seconds and goes black for a second.

...
Expected behavior:
Fix the problem if possible.

Versions:
This mod: 1.19.2-1.8.2
Minecraft: 1.19.2
Forge: 43.2.6
Mod pack: TNP Limitless 6 v. 1.19.2 - 1.18.0

Longer Description:
So I find that since the Night Vision totem doesn't give infinite time for the potion effect it gets kind of annoying on the eyes, it goes for me for about 13 seconds then stops for a second and starts back up even in a pitch dark room. I would suggest making it work infinite instead of on a timer, so this issue doesn't happen.

**Comment by rubensworks** [comment]
@violetkitty87 Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by violetkitty87** [comment]
im sorry i couldnt find a proper template
i will fix it
