### ISSUE TITLE
Problems with online play

### ISSUE THREAD

**Issue by Stllcn233** [CyclopsMC/EverlastingAbilities#218]
#### Issue type:

- :question: Question 

____

#### Question:
Excuse me, how can I make the effect of the negative surroundings not affect the players who play with me
(adding minecraft:player to the config text) works?
English is not my native language, I use a translation software to input, please forgive me if there are any word order mistakes.

**Comment by rubensworks** [comment]
Adding those players to the same Minecraft team should fix the problem.

**Comment by Stllcn233** [comment]
Do you mean the FTB mod? I don't have this mod installed.

**Comment by rubensworks** [comment]
No, just vanilla Minecraft: https://minecraft.fandom.com/wiki/Commands/team

<blockquote><img src="https://static.wikia.nocookie.net/minecraft_gamepedia/images/e/e6/Site-logo.png/revision/latest?cb=20211226202153" width="48" align="right"><div>Minecraft Wiki</div><div><strong><a href="https://minecraft.fandom.com/wiki/Commands/team">Commands/team</a></strong></div><div>Controls teams. team list [<team>] Lists all teams, with their display names and the amount of entities in them. The optional <team> can be used to specify a particular team. team add <team> [<displayName>] Creates a team with the given name and optional display name. <displayName> defaults to <team> when unspecified. team remove <team> Deletes the specified team. team empty <team> Removes all members from the named team. team join <team> [<members>] Assigns the specified entities to the specifi</div></blockquote>

**Comment by Stllcn233** [comment]
Ok thank you so much for the tutorial!
