### ISSUE TITLE
 Player disconnect while creating single player world

### ISSUE THREAD

**Issue by SmallSansSerif** [CyclopsMC/EverlastingAbilities#219]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Created a new normal world in single player with cheats enabled and I get a disconnect message that leads me to the multiplayer menu. It appears the world is created though. Error in log points to Cyclops/Everlasting error.

#### Expected behaviour:

Launch game in single player with ability bottle on join.
____

#### Versions:

- This mod: EverlastingAbilities-1.19.2-2.0.0
- Minecraft: 1.19.2
- Forge: 43.2.8

#### Log file:

https://pastebin.com/hVLug43i

**Comment by rubensworks** [comment]
Thanks for reporting!
