### ISSUE TITLE
Default datapack path

### ISSUE THREAD

**Issue by theolike** [CyclopsMC/EverlastingAbilities#220]
I'm trying to understand this statement in the [ability datapacks documentation](https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks):

> All default abilities are created at data/everlastingabilities/everlastingabilities/abilities/, and can therefore be overridden at this location.

That path does not exist in my instances.

I'm using the 1.19.2-2.0.1 jar from Curseforge (in a 1.19.2 forge 43.2.8 instance).  I've tried it on my server and a single player instance with only this mod but that directory does not exist.  Should I interpret this to mean I need to create that directory and place a datapack for the default abilities there?  If so, the way the documentation is phrased, it seems to imply I should find a datapack already exists in that path.

Would you help me understand what that means and the correct way to alter the default abilities?

**Comment by rubensworks** [comment]
You'll have to create your own datapack, see https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack

<blockquote><img src="https://static.wikia.nocookie.net/minecraft_gamepedia/images/c/cc/FileExtensions.png/revision/latest?cb=20191218034727" width="48" align="right"><div>Minecraft Wiki</div><div><strong><a href="https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack">Tutorials/Creating a data pack</a></strong></div><div>This tutorial shows how to create a data pack. Data packs can be used to add or modify functions, loot tables, world structures, advancements, recipes, tags, dimensions, predicates and world generation. There are some things that you should not do while creating a data pack. Here is a list of "don'ts": Release Minecraft versions or modifications that allow players to play without having bought Minecraft from Mojang. Release the decompiled source code of Minecraft in any way. To create a data pac</div></blockquote>
