### ISSUE TITLE
Can't join world after updating: net.minecraft.ReportedException: Loading entity NBT

### ISSUE THREAD

**Issue by aaronhowser1** [CyclopsMC/EverlastingAbilities#222]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I updated the mod from 2.0.1 to 2.0.2 and now I can't join my old world. Downgrading back to 2.0.1 fixes the problems.

#### Steps to reproduce the problem:

1. In 2.0.1, make a world
2. Update to 2.0.2
3. Join the world
4. Crash

#### Expected behaviour:

For it to not crash

____

#### Versions:

- This mod: 2.0.2
- Minecraft: 1.19.2
- Forge: 43.2.8

#### Log file:

latest.log: https://gist.github.com/aaronhowser1/ffb1700c018257cc9e7f6350c0d4077f
Important bit:
`Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.Level.m_5962_()" because the return value of "org.cyclops.everlastingabilities.core.helper.WorldHelpers.getActiveLevel()" is null`

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Does this happen in singleplayer, or when connecting to a multiplayer server?

Note to self: we may have to refactor `WorldHelpersServer.getActiveLevel()` to `WorldHelpersServer.getActiveRegistryAccess()`, to avoid a world dependency.

**Comment by rubensworks** [comment]
Ok, looks like I didn't do enough testing before the last release. New update will be out in a bit.
