### ISSUE TITLE
Datapack path

### ISSUE THREAD

**Issue by theolike** [CyclopsMC/EverlastingAbilities#223]
I really do like your mod.  Thank you for your work!
#### Issue type:

- :question: Question 

____

#### Question:
I'm adding another question related to my previous #220.
Clear and concise question:  what is the exact path starting in the datapack directory including file name to place an updated config file for a default effect? 

I know you probably get a lot of useless questions and I am still learning about data packs, but I think there is something wrong with the documentation.  I've tried several times now to modify an effect configuration and I cannot make any progress.  I've tried placing the updated JSON in more than a few variations of the paths in the documentation but there is no change in game.  If you can provide an explicit example of updating an attribute of a default effect, I would be happy to try to clarify the documentation.

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Never tried overriding datapack entries myself before yet tbh. If you find how to do it, please let me know :)

**Comment by theolike** [comment]
Ok, now I'm really confused... The Wiki page literally shows that's the new way to override the default effect abilities.  Maybe I'm not explaining myself well...

If I want to override the maximum like I did using the toml config prior to v2, how exactly do I do that?

The wiki indicates using a data pack and gives an example of the JSON for absorption.  I can't make it work based on the [information provided](https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks).

**Comment by rubensworks** [comment]
Making a new datapack in the same namespace with the exact same path and filenames to override them should work according to the general datapack system.
It should work the same way as overriding vanilla datapack entries.

Perhaps you could try overriding other vanilla datapack entries. If that doesn't work either, then there's probably something wrong in the way you create or load your datapack.

**Comment by theolike** [comment]
Then I think that's my question.  Using the example in the documentation, what would be the exact path to implement the absorption JSON shown?

**Comment by theolike** [comment]
Damn.  I got it and I think the issue was the mod version I had loaded.

\<world root\>/datapacks/\<data pack name\>/data/everlastingabilities/everlastingabilities/abilities/absorption.json

**Comment by rubensworks** [comment]
@theolike Great to hear that it's working now for you.
Is there any information on this topic that you would think would be good to add to the wiki? (given that this documentation has only been created quite recently)

**Comment by theolike** [comment]
After banging on it for a bit and finally noticing I had the wrong version of the mod loaded in my test instance, I can understand the phrasing of the documentation now.  I still think it would be more clear to provide the path to the example effect JSON in the format I gave in my last comment (starting at world root going all the way to a file name).

Also, now that I have a working test environment I'll build out the customized JSON for each default effect.  I wouldn't mind turning over that data pack for inclusion in your repository to save others the work later when I'm done.

**Comment by rubensworks** [comment]
>  I still think it would be more clear to provide the path to the example effect JSON in the format I gave in my last comment (starting at world root going all the way to a file name).

Good idea; done!
