### ISSUE TITLE
DataPack Special Abilities

### ISSUE THREAD

**Issue by theolike** [CyclopsMC/EverlastingAbilities#224]
Once again, thanks for all the hard work.

#### Issue type:

- :question: Question 

____

#### Question:

For a special ability, what are the "type", "name", and "effect" attributes in the data pack JSON?  I've been walking the source and I think it would be something like this, but I would like to confirm.  

```

{
  "type": "everlastingabilities:special_step_assist",
  "target": "self",
  "name": "ability.everlastingabilities.step_assist",
  "rarity": "rare",
   "effect": "everlastingabilities:stepAssist",
   "force_default_step_height": true
}

```

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by theolike** [comment]
I'll probably have the same question for the other special abilities as well.

**Comment by rubensworks** [comment]
All of those should be explained on the wiki: https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks
Is the description there insufficient?

<blockquote><img src="https://opengraph.githubassets.com/2be617a3895f20652323908f2eaa6500948639eef401bdc31563e2e62e84dda1/CyclopsMC/EverlastingAbilities" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks">Ability datapacks</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>
