### ISSUE TITLE
[1.19.2] Crash when using ender lead on bee

### ISSUE THREAD

**Issue by JaisDK** [CyclopsMC/EverlastingAbilities#225]
Reposting an issue because the crash seems to be caused by your mod

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3150

**Comment by rubensworks** [comment]
@JaisDK Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.

**Comment by JaisDK** [comment]
Please read the issue using your human eyes
