### ISSUE TITLE
Modified effect for the 'bad omen' ability

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/EverlastingAbilities#226]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

From [this conversation in #everlastingabilities](https://discord.com/channels/386052815128100865/386054303137136651/1098642503944654908), the 'bad omen' ability can be misinterpreted to allow the user to start raids as if they had the 'bad omen' effect. The bad omen ability currently is a radius-ability that applies the bad omen effect to nearby players other than the user, and does not currently allow the user to initiate raids on their own.

It was suggested in that conversation that the ability be modified to a self-ability (to allow the user to initiate raids). As both abilities are useful (even if giving it to others is mostly for comic effect :) ), would it be reasonable to have two abilities - 'bad omen (self)', and 'bad omen (others)'? The designated 'self' version could cost more xp as it is more mechanically useful, but ultimately having both versions doesn't restrict the ability from one use or the other.

If having two versions of a similar/identical ability would be adding too much to the core Everlasting Abilities mod, then this feature request would instead be to modify the 'bad omen' ability to be a self-ability instead of a radius-ability.

**Comment by rubensworks** [comment]
Thanks for the suggestion!
