### ISSUE TITLE
Crash with IC2???

### ISSUE THREAD

**Issue by DragonMaster14545** [CyclopsMC/EverlastingAbilities#227]
#### Issue type: Crash

- :bug: Bug 

____

#### Short description:

When launching the game with just everlasting abilitys and IC2:classic it crashes

#### Steps to reproduce the problem:

Install the two mods and their dependencys and launch the game
#### Expected behaviour:

It should load

____

#### Versions:

- This mod: 2.0.4
- Minecraft: 1.19.2
- Forge: 43.2.0

#### Log file:
[crash-2023-05-11_17.38.14-fml.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/11454017/crash-2023-05-11_17.38.14-fml.txt)
[latest.log](https://github.com/CyclopsMC/EverlastingAbilities/files/11454018/latest.log)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Xplodin** [comment]
getting this crash on latest versions
