### ISSUE TITLE
1.12 Incompatibility with UntouchedNature mod; disables flying upon being added to server

### ISSUE THREAD

**Issue by Arriochh** [CyclopsMC/EverlastingAbilities#228]
#### Issue type: Game-breaking mod incompatibility

- :bug: Bug

____

I did a thorough breakdown of what is causing me to stop flying when I equip that ability, and narrowed it down to the UntouchedNature mod.

Link: https://www.curseforge.com/minecraft/mc-mods/untouched-nature
Optional dependency: https://legacy.curseforge.com/minecraft/mc-mods/ctm

I'm unaware if you still support 1.12 but I will write one anyway.

1. Add EverlastingAbilities, EverlastingAbilities-PotionCore, CyclopsCore, and UntouchedNature together.
2. Start the server
3. Go into creative and give yourself a fly ability totem
4. You will notice that you can do a small extra jump but you cannot fly, and are still immune to fall damage.

____

#### Versions:

- EverlastingAbilities-1.12.2-1.5.3
- EverlastingAbilities-PotionCore-1.12.2-1.0.2
- PotionCore-1.9_for_1.12.2
- CyclopsCore-1.12.2-1.6.7
- UntouchedNature---v.1.0.1---1.12.2

- Forge: 1.12.2 - 14.23.5.2859

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Arriochh** [comment]
If you need more information I'll be happy to provide it. I really want these two mods to work together otherwise I'll have to find another magical forest mod that competes with it.

As said before im unaware if you still do support for 1.12, I apologize if that's the case.

**Comment by rubensworks** [comment]
We don't support 1.12 anymore unfortunately.
