### ISSUE TITLE
I can't respawn

### ISSUE THREAD

**Issue by JorngHorse** [CyclopsMC/EverlastingAbilities#229]
#### Issue type: unable to respawn

- :bug: Bug 

____

#### Short description: The problem with them od is that when I have any mod that changes the ui like one probe, hywla, gokistats,
jei, project mmo, and more haven't been able to tested out more but never the less I'm not able to respawn with this mod and these other mods

#### Steps to reproduce the problem: step 1 have any mod that changes the default screen step 2 die step 3 you are not able to respawn unless you uninstall everlasting mod or any of the mod that changes the default screen 

1. ...

#### Expected behaviour: you can't respawn no matter how hard you try I know I have spend a whole minutes with a auto clicker trying to respawn

____

#### Versions: 1.16.5  

- This mod: everlasting 1.16.5 I tried all of the everlasting for 1.16.5 they all don't let me respawn cyclopsCore 1.16.5-1.12.4 and 1.13.0
- Minecraft: minecraft java 
- Forge: 36.2.39

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by JorngHorse** [comment]
I forgot to mention I tried a different version of forge 1.16.5 36.2.34 and it didn't fix the problem

**Comment by JorngHorse** [comment]
another update some api also ore whatever they are cause this problem as well factory api 1.80 or architectury has cause the no respawn

**Comment by rubensworks** [comment]
I'm sorry, but MC 1.16 is not supported anymore.

**Comment by JorngHorse** [comment]
bruh
