### ISSUE TITLE
Game crashes when I move the ability from the bottle to me

### ISSUE THREAD

**Issue by IskallDoe** [CyclopsMC/EverlastingAbilities#230]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Right click the bottle
2. Game crashes

#### Expected behaviour:

____

#### Versions:

- This mod: EverlastingAbilities-1.20.1-2.0.6.jar
- Minecraft: 1.20.1
- Forge: 47.0.43

#### Log file: 
https://paste.ee/p/LZ1pL

**Comment by rubensworks** [comment]
Thanks for reporting!
