### ISSUE TITLE
totems do not appear in minecraft 1.20.1

### ISSUE THREAD

**Issue by alezhito18** [CyclopsMC/EverlastingAbilities#232]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I use minecraft 1.20.1 and the skill totems do not appear, only the bottle

#### Steps to reproduce the problem:

simply add the mod, if you go to creative mode, you will only see the bottle where the abilities are stored, there are no totems, the chests are not generated either

1. ...

#### Expected behaviour:

____

#### Versions:

- This mod: EverlastingAbilities
- Minecraft: 1.20.1
- Forge:  47.0.35

**Comment by rubensworks** [comment]
Thanks for reporting!
