### ISSUE TITLE
[1.20.1] Crash upon joining a created world

### ISSUE THREAD

**Issue by MrKashew** [CyclopsMC/EverlastingAbilities#233]
#### Issue type:

- :bug: Bug 

____

Crash log:
[crash-2023-07-05_00.06.14-server.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/11954853/crash-2023-07-05_00.06.14-server.txt)

**Comment by rubensworks** [comment]
@MrKashew Your issue appears to be not following one of the allowed issue templates, which breaks our automation tools. Please update your issue to the proper template.
