### ISSUE TITLE
[1.20.1] Crash on server tick

### ISSUE THREAD

**Issue by MrKashew** [CyclopsMC/EverlastingAbilities#234]
#### Issue type:

- :bug: Bug 

____

Created world and flew around and crashed quickly
[crash-2023-07-05_20.25.02-server.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/11963867/crash-2023-07-05_20.25.02-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
