### ISSUE TITLE
Datapack path for default abilities

### ISSUE THREAD

**Issue by met4000** [CyclopsMC/EverlastingAbilities#235]
#### Issue type:

- :question: Question 

____

#### Question:

#223 asks a similar question, and provides the answer that is currently on the wiki - it claims the default 'absorption' ability is located at `<world-root>/datapacks/<datapack-name>/data/everlastingabilities/everlastingabilities/abilities/absorption.json` (also see [wiki/Ability-datapacks#registry](https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks#registry)). Testing in 1.19.2 with mod version 2.1.1, placing a json file at that location seems make a new ability, rather than overriding the current one. Looking at [master-1.20/src/main/resources/data/everlastingabilities/everlastingabilities/abilities](https://github.com/CyclopsMC/EverlastingAbilities/tree/master-1.20/src/main/resources/data/everlastingabilities/everlastingabilities/abilities) (1.19-lts is the same), the structure looks like it's `.../abilities/effect/absorption.json` rather than `.../abilities/absorption.json` - and making the file in the datapack at `.../abilities/effect/absorption.json` instead does seem to override the default absorption ability rather than making a second one. Likewise, special abilities appear to be at `.../abilities/special/bonemealer.json`.

Is this the intended path, and if so could the wiki be updated to use examples that use and distinguish between these two folder, e.g. `everlastingabilities:effect/absorption` is at `<world-root>/datapacks/<datapack-name>/data/everlastingabilities/everlastingabilities/abilities/effect/absorption.json`, and `everlastingabilities:special/bonemealer` is at `<world-root>/datapacks/<datapack-name>/data/everlastingabilities/everlastingabilities/abilities/special/bonemealer.json`?

Example datapacks with the file at these two locations:
[abilities_root_absorption.zip](https://github.com/CyclopsMC/EverlastingAbilities/files/12104904/abilities_root_absorption.zip) (seems to create a new ability without modifying the default one)
[abilities_effect_absorption.zip](https://github.com/CyclopsMC/EverlastingAbilities/files/12104902/abilities_effect_absorption.zip) (seems to overwrite the default ability)

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Aha, those were the old locations indeed. Fixed! :-)
