### ISSUE TITLE
Crash on spawning Nether Visage Portal (boss mob) from Astral Dimensions

### ISSUE THREAD

**Issue by arketec** [CyclopsMC/EverlastingAbilities#236]
#### Issue type:

- :bug: Bug 

____

#### Short description:

Minecraft client crashes upon spawning the end boss of the mod [Astral Dimension](https://www.curseforge.com/minecraft/mc-mods/astral-dimension)
Everything works fine if you then load Minecraft again, it just crashes when spawning the bosses in

#### Steps to reproduce the problem:

1. Install Astral Dimension and Everlasting Abilities
2. Kill Void Titan (first boss)
3. Find Infested Cathedral
4. Destroy all portal entities
5. Destroy Locked Vistage
6. Crash

#### Expected behaviour:

____

#### Versions:

- This mod: EverlastingAbilities-1.18.2-1.8.1.jar
- Minecraft: 1.18.2
- Forge: 40.2.9

I am the modpack author, I am working on a new progression expert pack

#### Log file:

https://pastebin.com/twMZf1Cn

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by arketec** [comment]
Oh one more note. I do have all the totem's disabled from mob drops, not sure if that could be related, but based on the error message, maybe it is?

**Comment by arketec** [comment]
actually, this bug is almost certainly fixed by this commit in the 1.20 branch:

https://github.com/CyclopsMC/EverlastingAbilities/commit/0a72c91b710ad880ed71e21eb1e9e6745eac9d04#diff-d4fc4f0b9bf72cd47673db0e9f4fe593b896a1bb6768232207b2d077fee765e5L274

is there anyway to get a backport?
