### ISSUE TITLE
[1.20.1] Totems found in loot chests are "empty", no ability on them.

### ISSUE THREAD

**Issue by Gbergz** [CyclopsMC/EverlastingAbilities#237]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Install mod
2. Find a totem in chest
3. Totem is empty, no effect on it.
4. Profit.

#### Expected behaviour:

That totems found in Chests have abilities on them.

____

#### Versions:

- This mod: 2.1.1
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:
None.

### Other:
Yes, I saw this issue https://github.com/CyclopsMC/EverlastingAbilities/issues/231, but apparently its not fixed still.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
There might be something wrong with your version (2.1.1), which is not the latest (2.0.8).
Can you double-check to see if you're using the latest version?

**Comment by Gbergz** [comment]
Apologies. I meant to put 2.0.8 there. Reported issues for other mods and got versions mixed up while writing.

**Comment by rubensworks** [comment]
Note to self: see https://github.com/CyclopsMC/EverlastingAbilities/commit/c3a87f8eb03d33fd8ebd63401a80d9ef84dc6d3e#diff-0be513a2362292630176ab094802789c3c3f2b7d585726911ccad27f2bc0c406

**Comment by Gbergz** [comment]
Not sure if there's a conflict in my modpack or something, but I tried the new update (v2.0.9) they still give no abilities in loot chests.
![pic](https://github.com/CyclopsMC/EverlastingAbilities/assets/26634554/2ec7397c-a8a8-4eea-ad3b-39fbef2d6813)

**Comment by Gbergz** [comment]
Ignore the last comment, I forgot to restart the game after updating the mod. It works now.
