### ISSUE TITLE
How I can change maximum abilities level

### ISSUE THREAD

**Issue by ghost** [CyclopsMC/EverlastingAbilities#238]
I have created a Minecraft server, and I would like to increase the maximum level of the abilities, by this I mean that instead of the speed being a maximum level 5, convert it to maximum level 25. I have been trying to change it to the .cfg file on the server, but I have not achieved anything

**Comment by rubensworks** [comment]
You can modify abilities (including max level) via datapacks, as explained here: https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks

<blockquote><img src="https://opengraph.githubassets.com/548f03d6de67616d02e15d80fb744ff1c6b886369d9208273de7f55935faa267/CyclopsMC/EverlastingAbilities" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks">Ability datapacks</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>
