### ISSUE TITLE
No abilities with Cyanide mod

### ISSUE THREAD

**Issue by Daltaxy** [CyclopsMC/EverlastingAbilities#239]
#### Issue type:

- :bug: Bug 

____

#### Short description:
Hello.
I hadn't played my world for quite some time; I come back and update everything, including forge to 47.2.1 (copied from another issue, as none happened before)
Anyways, I just updated everything, and now all my abilities are gone, including those in my ability bottle. They all say None (ability) :
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/111076631/a3f5a827-4e07-484d-9a90-82a29b0c7b04)
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/111076631/99d59408-8a51-4e42-93bb-999216ae8d52)
I'm sure they aren't gone forever though, as the log is spammed by this:
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/111076631/6905efd9-4e6d-4e61-90d4-49fcf4d43fe3)

#### Steps to reproduce the problem:

No steps sadly, seems to be a specific issue, I thought maybe someone will have an idea

#### Expected behaviour:

keeping my abilities...
____

#### Versions:

- This mod: EverlastingAbilities-1.20.1-2.0.9.jar
- Minecraft: 1.20.1
- Forge: 47.2.1

#### Log file:
[debug.log](https://github.com/CyclopsMC/EverlastingAbilities/files/12895245/debug.log)
very heavy, so I'll also post https://mclo.gs/XleKFNO but this one ends at 25000 lines.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Daltaxy** [comment]
sorry if this is incomplete, I just don't see any reason as nothing is mentioned in the log... if testing is required I'm here and in the cyclopscore server for faster responses (daltax)

**Comment by rubensworks** [comment]
It looks like your ability registry is somehow corrupted. If you open your creative tab, can you see any valid ability totems in there?

**Comment by Daltaxy** [comment]
> It looks like your ability registry is somehow corrupted. If you open your creative tab, can you see any valid ability totems in there?

![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/111076631/5741b2e2-fa07-49a3-b477-fc0bc4d4d255)
no totems in creative or jei for some reason

**Comment by rubensworks** [comment]
Ok, so your ability registry seems to be completely empty.

Can you check what happens if you create a new (client-side and/or server-side) world?

Are you certain you didn't modify the ability datapack? (https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks)

<blockquote><img src="https://opengraph.githubassets.com/548f03d6de67616d02e15d80fb744ff1c6b886369d9208273de7f55935faa267/CyclopsMC/EverlastingAbilities" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks">Ability datapacks</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>

**Comment by Daltaxy** [comment]
I'll try when i get home
never touched anything related to datapacks except for the advanced mining dimension, though many mods caused "error in datapacks prevented the world from loading" which was always fixed with updates or removing mods

**Comment by michelsciortino** [comment]
I have the same problem, there are no ability totems in the registry.
I haven't touched any mod config or datapack

also, my game log does not have any "skipped loading unknown ability...",  i have only these 4 lines containing everlasting
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/34399301/6df8306b-9565-498a-b07f-d45cec1b94a9)

**Comment by Daltaxy** [comment]
sorry I forgot about this because my modpack kept crashing on world gen and I still don't know why... I'll try again in a few hours, I'll set a reminder this time

**Comment by Daltaxy** [comment]
> Ok, so your ability registry seems to be completely empty.
> 
> Can you check what happens if you create a new (client-side and/or server-side) world?
> 
> Are you certain you didn't modify the ability datapack? (https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks)
> 
> > <img alt="" width="48" src="https://opengraph.githubassets.com/548f03d6de67616d02e15d80fb744ff1c6b886369d9208273de7f55935faa267/CyclopsMC/EverlastingAbilities"><img alt="" height="14" src="https://github.githubassets.com/favicons/favicon.svg"> GitHub**[Ability datapacks](https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks)**Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.

so I'm back.
after creating a world in creative, I wasn't even given an ability bottle (could be normal for creative)
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/111076631/543196a4-e333-4473-8958-ee7f0f30df87)
On top of that, the next picture is useless but there are NO ability totems in any loot chest whatsoever.
I probably looked through 20 loot chests in various structures, including the spiral like dungeon with floors going down, where I know for sure you can get some in chests usually
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/111076631/7a4ea87a-85d8-4902-9dd9-7928cb68b45f)


<blockquote><img src="https://opengraph.githubassets.com/548f03d6de67616d02e15d80fb744ff1c6b886369d9208273de7f55935faa267/CyclopsMC/EverlastingAbilities" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities/wiki/Ability-datapacks">Ability datapacks</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>

**Comment by Daltaxy** [comment]
forgot to mention that the ability bottle in creative also says None with nothing inside
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/111076631/06069f44-bbc3-48f1-bae9-05380da41232)
Finally, my log
(limited to 25k lines sadly, so I'll include the file as well)
https://mclo.gs/jzbLwIc
[debug.log](https://github.com/CyclopsMC/EverlastingAbilities/files/13060569/debug.log)


<blockquote><img src="img/favicon.ico" width="48" align="right"><div>mclo.gs</div><div><strong><a href="https://mclo.gs/jzbLwIc">Forge 1.20.1 Client Log [#jzbLwIc]</a></strong></div><div>25000 lines | 90 errors</div></blockquote>

**Comment by rubensworks** [comment]
@Daltaxy But what about the creative tab of this mod in your new world? Does it contain any ability totems? There should be a bunch (for all ability types).

**Comment by michelsciortino** [comment]
I confirm the problem affects also the creative tab panel.

I've done some checks and it seems there is an incompatibility with the [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) mod.

I need to check what happens creating a new world with just these mods on.

**Comment by Daltaxy** [comment]
> @Daltaxy But what about the creative tab of this mod in your new world? Does it contain any ability totems? There should be a bunch (for all ability types).

nope, not a single one anywhere. not in jei, nor in the minecrafy creative tab. (even tried @everlasting) but the bottles don't show up)

**Comment by Daltaxy** [comment]
> I confirm the problem affects also the creative tab panel.
> 
> I've done some checks and it seems there is an incompatibility with the [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) mod.
> 
> I need to check what happens creating a new world with just these mods on.

no way man this mod ruined my life (in game)
there's another incompatibility with Mekanism, where you can't open a single recipe in jei without crashing
but the author of terralith recommends that I keep it :(

**Comment by michelsciortino** [comment]
> > I confirm the problem affects also the creative tab panel.
> > I've done some checks and it seems there is an incompatibility with the [Cyanide](https://www.curseforge.com/minecraft/mc-mods/cyanide-forge) mod.
> > I need to check what happens creating a new world with just these mods on.
> 
> no way man this mod ruined my life (in game) there's another incompatibility with Mekanism, where you can't open a single recipe in jei without crashing but the author of terralith recommends that I keep it :(

I litterally installed it under his suggestion.... and it has broken so many other mods.
As soon I removed it many mods started working again.

**Comment by michelsciortino** [comment]
I've created a modpack just with Cyanide, Everlasting Abilities and its dependency
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/34399301/3e67f0bb-cbe2-4fbe-834a-d4bbdd475ef4)

I confirm the abilities are all broken
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/34399301/d05e1270-fec1-4abc-aa94-1e4d71b7a5f4)
![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/34399301/f44d83bc-0779-4cf6-a309-06fcb5d5aae8)

The ability totems are not present in the creative tab

**Comment by rubensworks** [comment]
Nice detective work @michelsciortino!

So it looks like Cyanide is breaking registries. Could you (or @Daltaxy) take this up with the mod author of Cyanide?

For now, better to not use Cyanide together with this mod.

**Comment by Daltaxy** [comment]
> Nice detective work @michelsciortino!
> 
> So it looks like Cyanide is breaking registries. Could you (or @Daltaxy) take this up with the mod author of Cyanide?
> 
> For now, better to not use Cyanide together with this mod.

the other issue with Mekanism has been open for weeks and no answer from the dev(s)
only thing we can do is remove Cyanide and advise others  to do likewise lol
