### ISSUE TITLE
Step-assist ability broken in all 4 1.20.1 versions.

### ISSUE THREAD

**Issue by Devestatio** [CyclopsMC/EverlastingAbilities#240]
#### Issue type:

- :bug: Bug The step assist ability doesn't work in any of the 4 available version for MC 1.20.1

____

#### Short description:

All abilities work fine except for step assist, at first I thought it was because I was in the All The mods 8 pack, so I made my own version of the pack, with no restrictions or custom recipes or interactions, but it still would not work. I made an entirely new pack with no Apotheosis or other mods that included their own types of steps assists, as I thought that might be breaking it, but still your step assist failed to do anything. I went on the Discord, and someone said to try the older versions, but none of the 4 available versions for 1.20.1 made step assist work. It is very odd as all other abilities work just fine, and there are no errors or warning in the logs regarding Everlasting abilities or step assist at all. in fact it loads with zero issues according to the log.

#### Expected behaviour:

Expect to be able to be able to step up to 1-3 blocks in height.

____

#### Versions:

- This mod: 
- Minecraft: 1.20.1
- Forge: 47.2.0
- Java: jdk-17

#### Log file:

Mt last sessions crashed for some unknown reason, with nothing in the log stating why, but I will include it here so you can see it ran fine for several hours, with no errors regarding Everlasting Abilities.

https://mclo.gs/ogE2SfY

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Devestatio** [comment]
Oh here is the last log as well, i forgot to include it with the crash log.

https://mclo.gs/6Xco0En

<blockquote><img src="img/favicon.ico" width="48" align="right"><div>mclo.gs</div><div><strong><a href="https://mclo.gs/6Xco0En">Forge Server Log [#6Xco0En]</a></strong></div><div>812 lines | 49 errors</div></blockquote>

**Comment by Devestatio** [comment]
looks like there is no step assist json file, maybe that's why it doesn't work?

nm it's in the special folder, and it looks formatted correctly.

![image](https://github.com/CyclopsMC/EverlastingAbilities/assets/4734339/74be39b1-dbf4-42be-a6f9-4c5f64e13be0)

**Comment by Devestatio** [comment]
Ok so update on trying to help you debug this issue. I made sure I took off step assist from my character, then completely removed the mod along with any configs that where attached to it. Then I played without the mod for a while and then saved. I then added version 1.20.1-2.0.6 and played for a bit, then as soon as I tried to add step assist to my character, the game immediately froze up and became unresponsive, and I had to end the task through Windows to close it. The log shows it's a clear issue with step assist, and it seems it was causing a ticking entity issue. I will rinse and repeat with the next version up, as you may have already solved that issue on the next version. (just checked and you did "* Fix crash when using step assist ability, Closes #230")

https://mclo.gs/bxeNbAu

"[03:19:28] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: class org.cyclops.everlastingabilities.ability.AbilityTypeSpecialStepAssist tried to access private field net.minecraft.world.entity.Entity.f_19793_ (org.cyclops.everlastingabilities.ability.AbilityTypeSpecialStepAssist is in module everlastingabilities@2.0.6 of loader 'TRANSFORMER' @77f4038c; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @77f4038c)
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class tallestegg.guardvillagers.HandlerEvents onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		2: ASM: everlastingabilities onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		3: ASM: atomicstryker.infernalmobs.common.EntityEventHandler@1f7d4640 onEntityLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		4: ASM: com.github.alexthe666.citadel.server.CitadelEvents@fd5da13 onEntityUpdateDebug(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		5: ASM: com.github.alexthe666.alexsmobs.event.ServerEvents@56b3212b onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		6: ASM: com.github.L_Ender.cataclysm.event.ServerEventHandler@4bbbbc34 onLivingUpdateEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$1646/0x0000028163707b38@62396a00
		8: net.minecraftforge.eventbus.EventBus$$Lambda$1646/0x0000028163707b38@2a09c120
		9: net.minecraftforge.eventbus.EventBus$$Lambda$1646/0x0000028163707b38@281921cc
		10: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@785944a9 tick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		11: ASM: squeek.appleskin.network.SyncHandler@884988c onLivingTickEvent(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		12: ASM: mekanism.common.lib.radiation.RadiationManager@7d42dc3a onLivingTick(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
		13: ASM: mob_grinding_utils.events.ChickenFuseEvent@4093e521 startChickenFuse(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		14: LOWEST
		15: ASM: class ovh.corail.tombstone.event.EventHandler onLivingUpdate(Lnet/minecraftforge/event/entity/living/LivingEvent$LivingTickEvent;)V
java.lang.IllegalAccessError: class org.cyclops.everlastingabilities.ability.AbilityTypeSpecialStepAssist tried to access private field net.minecraft.world.entity.Entity.f_19793_ (org.cyclops.everlastingabilities.ability.AbilityTypeSpecialStepAssist is in module everlastingabilities@2.0.6 of loader 'TRANSFORMER' @77f4038c; net.minecraft.world.entity.Entity is in module minecraft@1.20.1 of loader 'TRANSFORMER' @77f4038c)
	at TRANSFORMER/everlastingabilities@2.0.6/org.cyclops.everlastingabilities.ability.AbilityTypeSpecialStepAssist.onTick(AbilityTypeSpecialStepAssist.java:41)
	at TRANSFORMER/everlastingabilities@2.0.6/org.cyclops.everlastingabilities.EverlastingAbilities.lambda$onLivingUpdate$5(EverlastingAbilities.java:326)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.common.util.LazyOptional.ifPresent(LazyOptional.java:137)
	at TRANSFORMER/everlastingabilities@2.0.6/org.cyclops.everlastingabilities.EverlastingAbilities.onLivingUpdate(EverlastingAbilities.java:320)
	at TRANSFORMER/everlastingabilities@2.0.6/org.cyclops.everlastingabilities.__EverlastingAbilities_onLivingUpdate_LivingTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.2.0/net.minecraftforge.common.ForgeHooks.onLivingTick(ForgeHooks.java:264)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2258)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:241)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.network.Connection.m_129483_(Connection.java:263)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:833)"

<blockquote><img src="img/favicon.ico" width="48" align="right"><div>mclo.gs</div><div><strong><a href="https://mclo.gs/bxeNbAu">Forge 1.20.1 Client Log [#bxeNbAu]</a></strong></div><div>3671 lines | 206 errors</div></blockquote>

**Comment by rubensworks** [comment]
Just tried myself with EA 2.0.9 on Forge 47.2.1, and everything is working just fine here.

Note that you were using 2.0.6 in your last post, while the latest is 2.0.9.

> Expect to be able to be able to step up to 1-3 blocks in height.

Level 1 allows stepping up to block height 1, level 2 to block height 2, and so on.
Perhaps you were expecting something else?

**Comment by Devestatio** [comment]
Well I did just finish trying the other 3 versions, 2.0.7, 2.0.8, and ended on 2.0.9, and step assist doesn't work no matter how many ranks I take. So not sure what other mod could be causing it to stop working...

**Comment by Devestatio** [comment]
Hmmm. just had a friend tell me the relic mod in the pack has a step assist boot, but I tested those and they don't work either...

NM the boots work fine, you just have to be sprinting, so not quite what we want, as we want it all the time.

**Comment by rubensworks** [comment]
Sounds like a pack issue then. Might be better to take it up with your pack author.

**Comment by ImperialSky** [comment]
> looks like there is no step assist json file, maybe that's why it doesn't work?
> 
> nm it's in the special folder, and it looks formatted correctly.
> 
> ![image](https://user-images.githubusercontent.com/4734339/276964153-74be39b1-dbf4-42be-a6f9-4c5f64e13be0.png)

Maybe iam blind but i dont see a json.file for Step Assist?
