### ISSUE TITLE
[1.20.1 Forge Crash] Crash upon opening Everlasting Abilities bottle

### ISSUE THREAD

**Issue by MrKashew** [CyclopsMC/EverlastingAbilities#241]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Join world
2. Open bottle
3. Crash

#### Versions:

- This mod: EverlastingAbilities-1.20.1-2.0.9
- Minecraft: 1.20.1
- Forge: 47.1.3

#### Log file:

[crash-2023-10-30_09.50.55-client.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/13208631/crash-2023-10-30_09.50.55-client.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!
