### ISSUE TITLE
What's the syntax for the give command for a totem in 1.19.2?

### ISSUE THREAD

**Issue by PurpleHel** [CyclopsMC/EverlastingAbilities#242]
#### Issue type:

- :question: Question 

____

#### Question:

I can't figure out the syntax for the give command for 1.19.2. Like, if I wanted to give myself a magnetize totem. I tried the following and just got the 'your command syntax is confusing the computer' error.

`/give @s everlastingabilities:ability_totem{"everlastingabilities:abilityStoreStack": [name: "everlastingabilities:effect/magnetize". level: 1]}
`

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Your JSON syntax appears to be invalid.
Name/level can not be defined directly inside an array, they must be wrapped in an object, e.g. `[{name: "everlastingabilities:effect/magnetize". level: 1}]`

You can find examples of the contents of valid NBT tags here: https://github.com/CyclopsMC/EverlastingAbilities/wiki/Creating-recipes-for-totems-and-bottles

<blockquote><img src="https://opengraph.githubassets.com/548f03d6de67616d02e15d80fb744ff1c6b886369d9208273de7f55935faa267/CyclopsMC/EverlastingAbilities" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities/wiki/Creating-recipes-for-totems-and-bottles">Creating recipes for totems and bottles</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>
