### ISSUE TITLE
Only one ability totem showing in the creative menu.

### ISSUE THREAD

**Issue by WordStormRose** [CyclopsMC/EverlastingAbilities#244]
#### Issue type:

- :bug: Bug 

____

#### Short description:

I'm a modpack developer, and I just stumbled upon this problem and I cannot for the life of me figure it out. In short, as the title says, I'm getting only one totem showing when I search 'ability totem' in the creative menu. So far in survival worlds it's been Speed 1 and in creative worlds it's been Absorption 1. I've narrowed it down to ModernFix _specifically in the context of my pack_ (Duad Beruzhaldan), but having only Everlasting Abilities, ModernFix, and the respective requirements/strong recommendations in a profile doesn't reproduce the problem. Everything's worked fine until my most recent pair of updates yesterday and today (mostly to do with troubleshooting things that I missed previously), so I know none of the _other_ mods in my pack are a problem.
I'm going to keep trying to figure this out, but I'm utterly baffled and if there's any way that you guys can help that would be wonderful.

#### Steps to reproduce the problem:

1. Load versions 1.2.81 or 1.2.82 of the modpack Duad Beruzhaldan. The suspected culprit was added in 1.2.81.
2. Load the game and go into creative or otherwise search for 'ability totem'.

#### Expected behaviour:

Usually I'm able to search and select specific totems to use at the start of a game (often for roleplaying a character but usually because I'm quite fond of step assist). Usually, when I search 'ability totem' (or just 'ability') a selection of all available totems appears in the creative menu, and when I search for a specific one - ie step assist - it shows up.

____

#### Versions:

- This mod: 1.8.2
- Minecraft: 1.18.2
- Forge: 40.2.10

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I've noticed that optimization mods such as ModernFix usually cause more problems than they offer improvements. So I recommend against using such mods in general.
I suspect this mod probably collapses items inside the creative tab by item type, and incorrectly ignores NBT tags.

Besides this information, there's not much I can do to fix this problem on my end though unfortunately :/

**Comment by WordStormRose** [comment]
Is there a command in 1.18.2 to get a specific totem?

**Comment by rubensworks** [comment]
Yep: https://github.com/CyclopsMC/EverlastingAbilities/issues/242
