### ISSUE TITLE
Non-randomized recycling.

### ISSUE THREAD

**Issue by NoNameISNoMan** [CyclopsMC/EverlastingAbilities#245]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The totem recycling gives the same totem.

#### Steps to reproduce the problem:

Put 3 totems into the crafting table, the resulting totem is always weakness one.

#### Expected behaviour:

Put 3 totems into the crafting table, the resulting totem is randomly selected.

____

#### Versions:

- This mod: 1.5.3
- Minecraft: 1.12.2
- Forge: 1.90g

#### Extra:

I unfortunately don't know how to cut the mods from the modpack, but I will try if it is absolutely required, and I can't ask the modpack author, as I added the mod myself. The pack in question is E2E using the Prism Launcher 8.0.

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Unfortunately, MC 1.12 is not maintained anymore. I recommend updating to a more modern version of MC.

**Comment by NoNameISNoMan** [comment]
> I recommend updating to a more modern version of MC.

Not really an option for a modpack... Is there no quick hack-job that you can do? No need to fix anything, just for example, jam the randomization table into a console command to randomly give out a totem? It doesn't have to be pretty, it just hast to somehow work.

**Comment by markygnlg** [comment]
Since this is 'Closed' I do not know if you'll get this message ... but, when this was happening to me I changed these 2 options:

1.) totemCraftingCount = 1 ( initially I set it to 2 );
2.) totemCraftingRarityIncreasePercent = 1 ( to counteract the change of #1 above )

[EDIT: but I don't know if these options are in the 1.12 version]
