### ISSUE TITLE
Step Assist Not Working With Apotheosis Installed

### ISSUE THREAD

**Issue by ravendm5** [CyclopsMC/EverlastingAbilities#246]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Activate the step assist ability while Apotheosis is installed.  

#### Expected behaviour: Step assist should work

____

#### Versions:

- This mod: 1.20.1-2.0.10
- Minecraft: 1.20.1
- Forge: 47.2.18 and 47.2.19

**Comment by rubensworks** [comment]
Thanks for reporting!
