### ISSUE TITLE
Max Abilitys per Player config doesn't update

### ISSUE THREAD

**Issue by JanKlett** [CyclopsMC/EverlastingAbilities#247]
#### Issue type:

- :bug: Bug 

____

#### Short description:

No matter if you change it per command in game or per editor in the config file, the change isn't reflected in game. 
It doesn't matter if you close the world and reopen it, even creating a new world or restarting the game doesn't apply the config.

#### Steps to reproduce the problem:

1. In the Config change the general attribute maxPlayerAbilities

#### Expected behaviour:

The change in config should be reflected in game.

____

#### Versions:

- This mod: 2.0.10
- Minecraft: 1.20.1
- Forge: 47.2.0

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
It's working fine here on my end.
I suspect you may have tried this without restarting the game, while this is required here.
I've marked the config option as such for the next update.
