### ISSUE TITLE
Crash on dedicated server (1.19.2)

### ISSUE THREAD

**Issue by mcadventurecity** [CyclopsMC/EverlastingAbilities#248]
#### Issue type:

- :bug: Bug 

____

#### Short description:

The mod does not work on a dedicated server for 1.19.2. This seems to be due to [this class file ](https://github.com/CyclopsMC/EverlastingAbilities/blob/master-1.19-lts/src/main/java/org/cyclops/everlastingabilities/item/ItemAbilityTotem.java) accessing the Minecraft client class (net.minecraft.client.Minecraft), which causes a crash on the dedicated server upon world load.

#### Steps to reproduce the problem:

1. Install Forge Server 43.3.7
2. Add EverlastingAbilities 2.1.1 to mods folder.
3. Server crashes upon world load.

#### Expected behaviour:

The Server should load the world properly.

____

#### Versions:

- This mod: EverlastingAbilities-1.19.2-2.1.1.jar
- Minecraft: 1.19.2
- Forge: 43.3.7

#### Log file:
[crash report](https://pastebin.com/h8vp7fW0)
[log](https://mclo.gs/IDKfsDD)

**Comment by rubensworks** [comment]
Thanks for reporting!
