### ISSUE TITLE
Step Assist not working in 1.19.2 with Apotheosis

### ISSUE THREAD

**Issue by MoonMoonShark** [CyclopsMC/EverlastingAbilities#250]
#### Issue type:

- :bug: Bug 

____

#### Short description:

hey there! i know this was reported before for 1.20, and i know you were able to fix that, but we're having the same problem in 1.19.2. hopefully it's an easy fix? i appreciate all of your work on this! please let me know if there is anything i can do to help.

https://github.com/CyclopsMC/EverlastingAbilities/issues/246

#### Steps to reproduce the problem:

1. start game with Everlasting Abilities and Apotheosis
2. apply Step Assist ability
3. walk into block and not step up
4. have a sad

#### Expected behaviour:

when we used this in 1.18, Step Assist made it so that you could walk up blocks instead of having to jump up to get over them.

____

#### Versions:

- This mod: EverlastingAbilities-1.19.2-2.1.1
- Minecraft: 1.19.2
- Forge: 43.3.0
- Apotheosis: Apotheosis-1.19.2-6.4.1

(this is in a modpack called The Lighthouse, which is a custom pack i made for a private server.)
https://legacy.curseforge.com/minecraft/modpacks/the-lighthouse

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by MoonMoonShark** [comment]
you're my hero! <3
