### ISSUE TITLE
Multiple Step-assists stuck on character

### ISSUE THREAD

**Issue by ravendm5** [CyclopsMC/EverlastingAbilities#253]
#### Issue type:

- :question: Question 

____

#### Question:
Hi, I seem to have managed to get two instances of step assist stuck on my character.  Now I have a 6 block step height permanently, and while cool, its not ideal.  I wouldn't even know where to begin replicating this issue as a bug, but I was wondering if there is a command I could use to manually reset the height?  I think I could use the attribute command but I don't know the UUID to make the adjustment.  Any help with this issue would be appreciated.
Cary

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by rubensworks** [comment]
Sounds like a bug, could you open a bug report with a mention of all versions you use?
