### ISSUE TITLE
Everlasting Crashed with IC2 installed.

### ISSUE THREAD

**Issue by Periam** [CyclopsMC/EverlastingAbilities#254]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After installed latest version of both mod, IC2 and Everlasting, with their dependencies, the game crash in single player.

#### Steps to reproduce the problem:

1. Install IC2
2. Install Everlasting
3. Launch Game

#### Expected behaviour:

Before latest build the game worked fine. expected to launch.

____

#### Versions:

- This mod:  EverlastingAbilities-1.19.2-2.1.2

Rest of the  mods
curios-forge-1.19.2-5.1.6.1
CyclopsCore-1.19.2-1.19.0
IC2Classic-1.19.2-2.0.9.2
theoneprobe-1.19-6.2.2.

- Minecraft: 1.192.2

- Forge: 43.3.9

### Log file:

[crash-2024-04-04_11.24.16-fml.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/14874019/crash-2024-04-04_11.24.16-fml.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Looks like f01ed0c482c11364630eafa3c34634ae4d15f41c broke some things.
