### ISSUE TITLE
Step Assist stackable

### ISSUE THREAD

**Issue by 401256** [CyclopsMC/EverlastingAbilities#255]
#### Issue type:

- :bug: Bug 

____

#### Short description:

If you equip the ability "step assist" and leave the world you are playing in, the ability's effect will still be active after reentering the world and unequiping the ability "step assist", this effect is stackable and can as far as i know only be removed after death, the abillity is not conted as equiped but the effect is still active.

#### Steps to reproduce the problem:

1. join a world
2. equio the ability "step assist"
3. leave the world
4. remove the ability

#### Expected behaviour:

the effect of the ability "step assist" should not be active after the ability "step assist" is removed

____

#### Versions:

- This mod: EverlastingAbilities-1.19.2-2.1.3.jar
- Minecraft: 1.19.2
- Forge: Forge - 43.3.5 (tried different versions too, same problem)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Is this with only EA installed? Or are other mods involved?

**Comment by 401256** [comment]
I found the problem wile adding it to a mod-pack, however i also tried it with only the Everlasting Ability and Cyclops Core and the bug still exists, i didn't try different game versions.
