### ISSUE TITLE
Crashed with Just Enough Professions

### ISSUE THREAD

**Issue by dnk1234567** [CyclopsMC/EverlastingAbilities#256]
#### Issue type:

- :bug: Bug 

____

#### Steps to reproduce the problem:

1. Create a world with mods
2. Enter the Just Enough Professions catalogue in JEI
![2024-05-01_22 43 34](https://github.com/CyclopsMC/EverlastingAbilities/assets/86105014/f0aa6d61-8718-44c7-af95-33100cc3f0d9)
3. Wait until the game crashes (I tested three times,it lasts 1min10s,1min30s,1min40s)
4. Remove this mod and CyclopsCore
5. Repeat the sequence above, but the game will not crash(I tested 3min)

#### Expected behaviour:

The game will not crash.

____

#### Versions:

- This mod: 2.0.14
- CyclopsCore: 1.19.1
- JEI: 15.3.0.4
- Just Enough Professions: 3.0.1
- Minecraft: 1.20.1
- Forge: 47.2.6

#### Log file:

[crash-2024-05-01_22.35.33-client.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/15178138/crash-2024-05-01_22.35.33-client.txt)
[crash-2024-05-01_22.27.32-server.txt](https://github.com/CyclopsMC/EverlastingAbilities/files/15178148/crash-2024-05-01_22.27.32-server.txt)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
I suspect this is a bug in Just Enough Professions where the `random` field of the `Level` from a non-render thread.
Could you report it to their issue tracker? Feel free to link back here.

Somewhat related to https://github.com/CyclopsMC/EvilCraft/issues/961

**Comment by dnk1234567** [comment]
> I suspect this is a bug in Just Enough Professions where the `random` field of the `Level` from a non-render thread. Could you report it to their issue tracker? Feel free to link back here.
> 
> Somewhat related to [CyclopsMC/EvilCraft#961](https://github.com/CyclopsMC/EvilCraft/issues/961)

OK.
Thank you very much.
I'll try to report it to the JEP issue tracker.
