### ISSUE TITLE
[1.21.1-Neo] A config to disable spawning with ability bottle & xp that comes along with it

### ISSUE THREAD

**Issue by Gbergz** [CyclopsMC/EverlastingAbilities#265]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

A config to disable spawning with ability bottle & xp that comes along with it

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
`totemMaximumSpawnRarity` should do exactly what you need.

**Comment by Gbergz** [comment]
Where is this located at? The `everlastingabilities-common.toml` config doesn't have this.
![ss](https://github.com/user-attachments/assets/35f25e0d-8f3f-4874-b3cb-52bf2271948b)

**Comment by rubensworks** [comment]
That looks like a CyclopsCore bug...
Will push out a fix in a bit.

**Comment by Gbergz** [comment]
All fixed with latest CyclopsCore, thanks!
