### ISSUE TITLE
No one able to join server due to packet issue

### ISSUE THREAD

**Issue by Jermain6066** [CyclopsMC/EverlastingAbilities#267]
#### Issue type: 

- :bug: Bug 

____

#### Short description:

Moment someone joins they get auto disconnected with a packet message from 

#### Steps to reproduce the problem:

1. Join server
2. GET DISCONNECTED

#### Expected behaviour:

____

#### Versions: 1.20.1

- This mod:  2.1.2
- Minecraft: 1.20.1
- Mod loader version: Forge 47.2.20

#### Log file:

[
](https://pastebin.com/pVL5BZrd)

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by Jermain6066** [comment]
I would also like to add that this issue was not yet present untill 2 mods were installed (I need confirmation that this mod is root cause from you guys for it to get fixed)

SimpleDiscordLink-Universal version 3.1.5
CraterLib-Forge 2.0.3

It was fine at first I restarted the server after finishing all the webhooks thats when it started to present itself

**Comment by Jermain6066** [comment]
To add on to the issue I have contacted the devs of Simple Discord Link so they are also looking into this issue. Somehow after their mod establishes a active discord connection and you restart the server your mod throws out some packet error which they find confusing since this is a server side mod so it shouldn't even be sending your mod any client side packets.

**Comment by rubensworks** [comment]
Can you find a stacktrace for this error message?
There should be one in your logs.

**Comment by Jermain6066** [comment]
I will have a look when I get home. From my memory I haven’t seen one but I’ll look through the debug and normal logs.

**Comment by Jermain6066** [comment]
There is no such error checked all the logs I have none are there

**Comment by rubensworks** [comment]
Can you check your client logs?
Something went wrong when decoding the packet client-side.
So there should be a stacktrace in the client logs, but none in the server logs.

**Comment by Jermain6066** [comment]
I tried to recreate it but atm for some reason the issue is gone I removed the mod for a bit so I could keep Simple Discord Link and I just re added it tried to cause it to happen again but it won't so I will keep a eye on it. Most likely will come back after tomorrow restart as it did before.

**Comment by rubensworks** [comment]
Ok, thanks for checking. Should it occur again, please let me know here.
