### ISSUE TITLE
Using any item related to this mod freezes the game

### ISSUE THREAD

**Issue by Mythrrinthael** [CyclopsMC/EverlastingAbilities#27]
The log is too big to copy to pastebin in one go, so here's [part 1](http://pastebin.com/JGWfQjET) and here's [part 2](http://pastebin.com/8u4BjPYf).

**Comment by rubensworks** [comment]
Could you also send the crashlog that is produced by the client when the game actually crashes?

**Comment by Mythrrinthael** [comment]
Where would it be located? I can't find any other one.

**Comment by rubensworks** [comment]
When your game crashes, you always get a window with a crashlog after the window of the game has closed.

**Comment by Mythrrinthael** [comment]
Not with these crashes. Windows tells me Java has frozen and has to be terminated. I do so and no other window appears. I do realize which log you're talking about; the log is supposed to parse in the MC launcher itself, right?

**Comment by rubensworks** [comment]
Oh, Java freezes, that's quite an essential piece of information to know about.
This could mean there is an infinite loop somwhere.

So this always (and only) happens when there is a gui supposed to open.

**Comment by rubensworks** [comment]
@Mythrrinthael How much xp did you have when trying this?

When using an item, do you see the gui open? Or does it freeze before that?

Do you also experience the problem when _only_ using this mod? Because I can't reproduce this myself.

**Comment by Mythrrinthael** [comment]
1) A LOT of XP, as my experiments with a different mod (days before I found yours) led to an issue where a specific mob didn't stop dropping XP until I terminated Minecraft (the particle lag was pure hell) and removed the offending mod.
I have just under 50000 levels.

2) I can use the Ability potion, and its GUI seems to work fine, as do all the GUIs before _and_ after using the Ability potion GUI. The problem is when I use a **totem**, at which point no GUI shows up, nothing else happens except MC's internal server freezing (I can still walk around, but the game doesn't render anything new). If I try to leave the world, the whole game freezes.

3) Yes. Using just your mod (and CyclopsCore, of course) causes the same internal server freeze and game freeze.

EDIT: I did some more testing with just CyclopsCore and your mode, and found that this doesn't happen if I make a new Curse Minecraft profile (I use the curse launcher) rather than removing all other mods and make a new world in my old one. This seems inconsistent.

**Comment by rubensworks** [comment]
Ok, the problem was caused by your high level, which resulted in an xp overflow. Apparently vanilla doesn't handle this properly, so I've added a check for that.

**Comment by Mythrrinthael** [comment]
That's great. What's the schedule for pushing a new release? I'd like to use this mod as soon as possible, because now I'm using a motley patchwork of mods that don't do half as good a good job as you have of making a decent self-enhancement system.

**Comment by rubensworks** [comment]
I hope to release somewhere next week.
But in the meantime, feel free to use the lastest dev build: https://dl.bintray.com/cyclopsmc/dev/org/cyclops/everlastingabilities/EverlastingAbilities/1.9.4-1.2.2-44/EverlastingAbilities-1.9.4-1.2.2-44.jar

**Comment by Mythrrinthael** [comment]
Thanks, I really appreciate it.
