### ISSUE TITLE
Flight permanently disables magnetism. 

### ISSUE THREAD

**Issue by JasonDayspring** [CyclopsMC/EverlastingAbilities#270]
#### Issue type:

- :bug: Bug 

____

#### Short description:

After flying for the first time, all magnetism effects are ineffective.  Whether from this mod or similar effects from other mods.  As if you are always crouching.  Landing or even removing the flight ability does NOT restore the magnetism effect.  Using a magnetism totem does not restore the effect.   One more save gone.

#### Steps to reproduce the problem:

1. Fly

#### Expected behaviour:

Magnetism works properly regardless of whether you or not you have ever flown.
____

#### Versions:

- This mod: everlastingabilities-1.21.1-neoforge-2.3.0-222
- Minecraft: 1.21.1
- Mod loader version: NeoForge 21.1.65

**Comment by rubensworks** [comment]
Thanks for reporting!

**Comment by rubensworks** [comment]
Just tried this out myself, and this seems to be working just fine here.
Tested with the Flight and Magnetism abilities enabled.

Could you try without any other mods installed?
There may be another mod in your pack breaking things.
