### ISSUE TITLE
Add config option to disable spawning with Ability Bottle

### ISSUE THREAD

**Issue by ClintonOrdonez** [CyclopsMC/EverlastingAbilities#271]
#### Issue type:

- :heavy_plus_sign: Feature request 

____

#### Short description:

I would just like the option to not spawn with the Ability Bottle. There is already a recipe for crafting the Ability Bottle, which nicely gates when the player should be able to obtain it. Depending on the random ability it contains, spawning with the Ability Bottle can be a little OP, annoying, or useless. I'm putting together a modpack and I believe it would best for potential players to choose whether or not to engage with Everlasting Abilities.

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
This can be done by setting `totemMaximumSpawnRarity` to `-1`.
