### ISSUE TITLE
Make loot tables configurable in Fabric

### ISSUE THREAD

**Issue by Shibward** [CyclopsMC/EverlastingAbilities#273]
If possible, it'd be great if compatibility could be added for the mod 'When Dungeons Arise' as well as 'When Dungeons Arise - Seven Seas' so that the ability totems could spawn naturally in the mod's loot tables.
Tried teaching myself datapacks to see if i could add it myself, but not sure what function to call in order to get the totems to appear with an ability instead of empty.

If native compatibility cant be added, i'd appreciate if i could get some information so that i can try to add them via datapack.

I'm trying to get this working in Fabric 1.21.1.

Thanks.

Link to the mods below: 
https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise-fabric
https://modrinth.com/mod/when-dungeons-arise-seven-seas

- :heavy_plus_sign: Feature request

**Comment by rubensworks** [comment]
Thanks for the suggestion!

**Comment by rubensworks** [comment]
In Forge/NeoForge, this would be possible via a datapack, but not in Fabric unfortunately.

We need to add an extension point for this: https://github.com/CyclopsMC/EverlastingAbilities/blob/master-1.21/loader-fabric/src/main/java/org/cyclops/everlastingabilities/item/ItemAbilityTotemConfigFabric.java#L37C50-L47
We can probably convert that field into a string list, and add the `@ConfigurablePropertyCommon` annotation to make it easily configurable.

<blockquote><img src="https://opengraph.githubassets.com/4d910a9ce0e77a7a43d40c69ac924df851ddfa326e81632700088f535d822861/CyclopsMC/EverlastingAbilities" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/CyclopsMC/EverlastingAbilities/blob/master-1.21/loader-fabric/src/main/java/org/cyclops/everlastingabilities/item/ItemAbilityTotemConfigFabric.java">EverlastingAbilities/loader-fabric/src/main/java/org/cyclops/everlastingabilities/item/ItemAbilityTotemConfigFabric.java at master-1.21 · CyclopsMC/EverlastingAbilities</a></strong></div><div>Entry for The Modding Trials 2016. Contribute to CyclopsMC/EverlastingAbilities development by creating an account on GitHub.</div></blockquote>
