### ISSUE TITLE
everlasting abilities compat with loot bags

### ISSUE THREAD

**Issue by SDUBZ** [CyclopsMC/EverlastingAbilities#28]
when my users open a loot bag with a ability in it, it comes up with ability:none just wondering if we could get some compat between your mod and lootbags if possible?

**Comment by rubensworks** [comment]
This should already work.
The only thing I can think of is that this lootbags mod is somehow stripping NBT from itemstacks, which empties the ability totems from their abilities. Perhaps you should open an issue in their issue tracker.

**Comment by DoomSquirter** [comment]
sorry to tag onto this issue but I've also experienced this, but also with woot, which has acknowledged the nbt issue there.  aren't enchanted books defined by their nbt tho?  If that's the case, lootbags is definately not stripping the nbt then.  It's also dropping forestry bees, which I also think have nbt as well, so maybe there is an issue with your mod?  

Another mod (enchanting plus) and this mod both are dropping invalid items from woot (again, as above, woot author has already acknowledged that this is an nbt issue), but lootbags is dropping correct scrolls for enchanting plus. 

posted issue on lootbags github to see if they make an exception:
https://github.com/Malorolam/LootBags/issues/43

**Comment by DoomSquirter** [comment]
malorolam responded to my issue and I think I agree.  If lootbags can properly return, for example, enchanting plus scrolls, which definately do contain nbt (I verified this), then something is amiss with the everlasting abilities totems, and why they don't drop properly.  
https://github.com/Malorolam/LootBags/issues/43

Thanks in advance!
