### ISSUE TITLE
Allow only some abitilies available at first spawn 

### ISSUE THREAD

**Issue by rubensworks** [CyclopsMC/EverlastingAbilities#31]
(maybe only common abilities)

source: https://minecraft.curseforge.com/projects/everlastingabilities?comment=25

**Comment by forReason** [comment]
isnt this already possible in the config:

```
# The maximum rarity of totems to spawn when a player first logs in. [0-3], -1 disables totem spawning.
    I:general.totemMaximumSpawnRarity=1
```

**Comment by rubensworks** [comment]
@forReason Yes, but that only allows selecting abilities by rarity, while in some cases more fine-grained selection of spawn-abilities could be useful.

**Comment by rubensworks** [comment]
Possible via `obtainableOnPlayerSpawn`
