### ISSUE TITLE
Regen perk bug

### ISSUE THREAD

**Issue by apotsepko** [CyclopsMC/EverlastingAbilities#32]
With "CyclopsCore-1.9.4-0.9.0" and "EverlastingAbilities-1.9.4-1.2.4" only
Java Version: 1.8.0_111
MinecraftForge v12.18.3.2221

Regeneration 1 and 2 are dont work at all. Only regeneration wave animation and not a single HP regeneration for a 30 minutes. With this 2 levels of regeneration you can die from hunger.

**Comment by rubensworks** [comment]
Nothing seems to be wrong here. These are just vanilla's regen mechanics, which consume the hunger value.

**Comment by apotsepko** [comment]
Why every else ability in 1st and 2nd level work normal, but Regeneration is wasted. If you cant fix this, then skip first 2 levels of regeneration and start from Regeneration 3.

**Comment by rubensworks** [comment]
This is vanilla behaviour, if you're not satisfied with that, please report it to Mojang.
