### ISSUE TITLE
Feature: Combine three totems in a crafting grid to get a new random totem

### ISSUE THREAD

**Issue by CplPibald** [CyclopsMC/EverlastingAbilities#37]
Feature request: Combine any three totems in a crafting grid produces a new totem with a random ability.

This gives players something to do with the unwanted totems other than throwing them in lava, as well as a way to improve chance of getting the ones they want.

PS: I have written a working prototype.  If you think this is a good feature, I can send a PR.

**Comment by rubensworks** [comment]
Sounds like a good idea.
Feel free to send the PR, I'll check the implementation then :)
Be sure to make it configurable though, so that you could for example say that you need `5` totems to produce a new one. Setting that value to `-1` could completely disable that feature.
