### ISSUE TITLE
Using more than one ability totem

### ISSUE THREAD

**Issue by JonaBrackenwood** [CyclopsMC/EverlastingAbilities#4]
If you have more than one of the same kind of ability totem in a stack and if you use one bottle, 
the whole stack is consumed.

Eg. I have 2 speed totems and only have speed 1 activated already.
If I add it, I loose both speed totems and I only have speed 2 activated. 1 was lost.

**Comment by rubensworks** [comment]
Yes, that's not supposed to happen. The totems are not supposed to be stackable.
