### ISSUE TITLE
Power Stare is more trouble than it's worth

### ISSUE THREAD

**Issue by CplPibald** [CyclopsMC/EverlastingAbilities#40]
Power Stare makes melee combat extremely difficult.  Attempting to attack a mob simply pushes it out of reach of your weapons, often before you can even swing a sword.  With something like a zombie this is an annoyance because they'll just keep coming back.  For a ranged attacker like a skeleton or blaze it's actively detrimental because you're still in their range but they've been pushed out of yours.

Power Stare needs a way to be turned on and off during combat depending on the situation.

**Comment by rubensworks** [comment]
Also related to #39

**Comment by CplPibald** [comment]
I wrote a fix for this that makes a check for `player.isSneaking()` before applying knockback.  That way you only power stare when crouching down.  It seems to work pretty well.
