### ISSUE TITLE
Ability sort method

### ISSUE THREAD

**Issue by wilsondgonzales** [CyclopsMC/EverlastingAbilities#44]
love the mod! Just a minor enhancement request to sort the abilities alphabetically or rarirty.

**Comment by rubensworks** [comment]
Sort them where?
I don't think a list of them is provided anywhere except for JEI?

**Comment by wilsondgonzales** [comment]
when you open the ability bottle & having all abilities, the sequence of effects goes like :
absorption
glowning
...
...
speed
bonemealer
etc
