### ISSUE TITLE
[1.11.2] Abilities as Potion Effect Disable?

### ISSUE THREAD

**Issue by MokahTGS** [CyclopsMC/EverlastingAbilities#47]
We are seeing all of the abilities displayed on screen as potion effects and really want a way to disable this.  Is this being done by this mod and how do we disable it.  I don't see anything in the config for this.

Here's what it looks like:
https://www.dropbox.com/s/6a5hjf5vhr22c90/2017-07-17_13.57.00.png?dl=0

**Comment by rubensworks** [comment]
This is just vanilla behaviour, but I guess I can add an option to make all potion effects passive which will make them hidden.

**Comment by rubensworks** [comment]
I finally looked into this a bit, and it looks like it is not possible to add a config option for this, without changing behaviour for _all_ potion effects.
So I won't be doing that for this mod.

If you want to remove all potion status effects, I suggest you use a mod like this: https://minecraft.curseforge.com/projects/potion-icon-remover

<blockquote><img src="https://media.forgecdn.net/avatars/thumbnails/39/485/120/120/635981807014911759.png" width="48" align="right"><div>Minecraft CurseForge</div><div><strong><a href="https://minecraft.curseforge.com/projects/potion-icon-remover">Potion Icon Remover</a></strong></div><div>Disable Potion Icons in the top right of screen.</div></blockquote>
