### ISSUE TITLE
Player stuck with step assist ability

### ISSUE THREAD

**Issue by JonaBrackenwood** [CyclopsMC/EverlastingAbilities#5]
Sometimes a player can't deactive his abilities.
It show correctly in the client that the abilities have been deactivated (back in the bottle),
but the player still has the effects and they actually aren't deactivated.

If another player looks at the ability bottle, the buggy "activated" abilities aren't there.

**bug found by mak3231**

**Comment by rubensworks** [comment]
What happens after relogging?

"this is with step assist"

**Comment by rubensworks** [comment]
Can't reproduce, must be caused by some other mod.

**Comment by rubensworks** [comment]
Invalid, this is caused by overlapping jump boost ability.
