### ISSUE TITLE
Regeneration Ability Totem Doesn't Work

### ISSUE THREAD

**Issue by Flashfyre** [CyclopsMC/EverlastingAbilities#51]
The regeneration effect doesn't heal if you keep applying an effect every second and therefore the ability totem for it has no effect. There may be more effects like this.

**Comment by rubensworks** [comment]
I just tried the regeneration ability, and it seems to work just fine for me.

What exactly is the problem. As I may be misunderstanding you.

**Comment by Flashfyre** [comment]
My problem is that it doesn't heal me. When I gave my mod's regeneration a constantly refreshing potion effect it didn't work either.

**Comment by rubensworks** [comment]
Sounds like a mod conflict then, can you reproduce it with just EA (and CC) installed? Because I can't.

Btw, what MC/mod version are you using?

**Comment by Flashfyre** [comment]
I was using 1.12.1 with EA 1.3.2. I was using the MMD Dev mod pack.

**Comment by rubensworks** [comment]
Must be another mod conflicting with that potion effect then.

**Comment by Flashfyre** [comment]
Must be. I'll let you know if I find what mod is causing it. I hope it's not mine lol.
