### ISSUE TITLE
Server time out in Single player

### ISSUE THREAD

**Issue by AmazingTriangle** [CyclopsMC/EverlastingAbilities#59]
#### Issue type:
Bug

____
#### Short description:
Using 1.12.2
Forge 14.23.0.2540
CyclopsCore 1.12.2-0.10.22
EverlastingAbilities 1.12.2-1.3.6

Single player world loops to multiplayer load.  Server time out is error screen.

#### Expected behaviour:
Upon world load seeing world

#### Actual behaviour:
The load stops and disconnects from server.  Taking you to the multiplayer menu on a single player load.

#### Steps to reproduce the problem:

1. Removed all other mods.
2. Ran with the below listed mods
3. Error
4. Disabled Everlasting Abilities (cyclops only)
5. World loads

____
#### Versions:
- This mod: EverlastingAbilities 1.12.2-1.3.6
- CyclopsCore: 1.12.2-0.10.22
- Minecraft: 1.12.2
- Forge: 14.23.0.2540

**Comment by rubensworks** [comment]
Probably related to https://github.com/CyclopsMC/CyclopsCore/pull/94

**Comment by josephcsible** [comment]
Until this is fixed, you can downgrade to Forge 2537 as a workaround.
