### ISSUE TITLE
I can't craft added flight totem, I can craft other totems though.

### ISSUE THREAD

**Issue by puresmurfing** [CyclopsMC/EverlastingAbilities#63]
Please fill in the following template and make sure your title clear and concisely summarizes the issue.~~

#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:

I'm trying to add recipes (Through method mentioned at ) for certain Ability Totems (specifically Flight, Saturation, Wither & Poison). All recipes work except for Flight Totem. My crafting xml : https://pastebin.com/uMfSxh6G

#### Expected behaviour:

I can craft the flight totem

#### Actual behaviour:

I cant craft the flight totem

#### Steps to reproduce the problem:

1. Add a crafting recipe for flight totem

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.12.2-1.3.6
- CyclopsCore: 1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2555 & 14.23.1.2556 (Tried both versions

#### Log file:

https://pastebin.com/hyb7AZYH

I think this is important :
[22:27:12] [main/ERROR] [EverlastingAbilities]: Could not find the predefined item for key 'everlastingabilities:abilityTotem_flight_1'.

**Comment by rubensworks** [comment]
Can you try `everlastingabilities:abilityTotem_flight_0`? It's possible that the wiki is incorrect and the levels actually start counting from 0 (would have to check that to make sure).

**Comment by puresmurfing** [comment]
I just tried it and it provides a crafting recipe, however the totem crafted is empty.

**Comment by puresmurfing** [comment]
I've realised that my other 3 totems were all effect totems, so I'm going to try and create recipe for totems that don't simply provide effects.

**Comment by puresmurfing** [comment]
I've been able to craft a recipe for a Magnetize Totem.

**Comment by puresmurfing** [comment]
A work around that I am using is through Minetweaker.

**Comment by rubensworks** [comment]
Will be fixed in the new update. Note that levels really do start counting from level 1, there just was a bug in the implementation.
