### ISSUE TITLE
[Request] Config option to show levels required instead of exp

### ISSUE THREAD

**Issue by Shahelion** [CyclopsMC/EverlastingAbilities#64]
#### Issue type:

- :heavy_plus_sign: Feature request

I have no idea what the numbers correspond to as it is, and even after looking up exp values on the minecraft wiki it's still complicated, would be simpler if it just showed how many levels I need to have to equip it, counting from level 0 to account for the increasing costs.

**Comment by rubensworks** [comment]
Sure, I could add that to the tooltip.
