### ISSUE TITLE
Hit XP cap before getting Capstone Defender. 

### ISSUE THREAD

**Issue by RubikMonat** [CyclopsMC/EverlastingAbilities#65]
#### Issue type:
- :bug: Bug
____
#### Short description:
Playing the Defender branch in Grimco R&D modpack. 
I am at level 15  "Max Experience Achieved."
But I haven't unlocked all abilities for defender branch.

#### Expected behaviour:
Should be able to select everything when at XP Cap. 
"Stalwart Pact" "Invoke Mass" and "Capstone Defender"

#### Actual behaviour:
The three items listed in " " above remain red. Skill Points 0, spent 15 of 15, Level 15. 

#### Steps to reproduce the problem:
1. Level up to 14 and select all of the options except listed above. 
2: Reach level 15, try to select the remaining items. 

____
#### Versions:
- This mod:  0.8.1
- CyclopsCore:  1.12.2-0.10.23
- Minecraft: 1.12.2
- Forge: 8.0.99.99

#### Log file:
Didn't crash, no log file.

**Comment by rubensworks** [comment]
I don't know what you are talking about, so I assume you've reported this to the wrong mod. If you're not sure about which mod to report it to, report it to the issue tracker of the modpack.

**Comment by RubikMonat** [comment]
Sorry, I put it in the wrong tab! Your mod is awesome, really enjoying it. Will post the bug for yours in a new thread (related to crafting three unwanted ones together does not give a random result, but the same result every time.)
