### ISSUE TITLE
Crafting three unwanted does not give random result. 

### ISSUE THREAD

**Issue by RubikMonat** [CyclopsMC/EverlastingAbilities#66]
#### Issue type:
- :bug: Bug

____
#### Short description:
Crafting unwanted Ability Totems into a new one does not give random result. 

#### Expected behaviour:
Crafting three unwanted Ability Totems of a given tier (white, yellow etc) should give a random new Totem.  
(Desirable: Result should not equal any of the inputs.) 
(New feature request: crafting three of the same totem should yield the next tier of the same totem if available eg: luck)

#### Actual behaviour:
Crafting three white tier totems always yields "Water Breathing 1"
Yesterday three yellow tier always made Fertility 1, today they make Glowing 1

____
#### Versions:
- This mod:  1.3.6
- Minecraft: 1.12.2
- Forge: 8.0.99.99
- Mopdpack: Grimco R&D 1.0.3

**Comment by rubensworks** [comment]
Not really a bug, that's just how it works at the moment.
(After you craft one, you'll get something different next)
But I agree, the output should be different for different inputs.

**Comment by RubikMonat** [comment]
I see, thanks, I have three chests full to process now. :)
