### ISSUE TITLE
Wrong abilities are transferred in the gui

### ISSUE THREAD

**Issue by Charismara** [CyclopsMC/EverlastingAbilities#68]
#### Bugg:
[https://youtu.be/1-iqf37yPb4](https://youtu.be/1-iqf37yPb4)

#### Versions:

- This mod: 1.3.8
- CyclopsCore: 0.10.24
- Minecraft: 1.12.2
- Forge: 14.23.1.2566

**Comment by rubensworks** [comment]
Ok, so the wrong abilities are transferred in the gui. Please add a textual description next time, saves me a lot of time.
