### ISSUE TITLE
Regeneration too strong

### ISSUE THREAD

**Issue by Akitori** [CyclopsMC/EverlastingAbilities#69]
🐛 Bug

Short Description: Regeneration 1-3 seem far too powerful, healing faster than most mobs can even damage me. 

Expected Behavior: Put regen on, slowly heals me over time, like a long duration regen 1 effect.

Actual behavior: Hearts heal rapidly no matter what level of regen i put on. 

___
Steps:
1. Get regen ability.
2. Take damage, via instant, poison, mobs, etc
3. Put on regen ability.
4. Watch health heal absurdly fast. 
____

 Versions:
- Everlasting abilities 1.3.8 for 1.12
- CyclopsCore 0.10.24 1.12
- Minecraft 1,12
- Forge 14.23.1.2555

Note: I am aware a new version came out just now, if my testing reveals it doesn't have the bug i will close this report.

**Comment by Akitori** [comment]
Tested on newest version, bug still exist. Video proof is below in case needed clarification.

https://youtu.be/mPqD1qVYc5A

<blockquote><img src="https://i.ytimg.com/vi/mPqD1qVYc5A/hqdefault.jpg" width="48" align="right"><div><img src="/yts/img/favicon_144-vfliLAfaB.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=mPqD1qVYc5A">Regen Bug</a></strong></div><div>None needed.</div></blockquote>

**Comment by rubensworks** [comment]
That's simply how Vanilla's regen works. I did some balancing work in the past, and this seemed the best IMO.
(You can disable the ability if you think it's too OP)

Related: #62

**Comment by Akitori** [comment]
You could make the Regen effect tick down instead but alright
