### ISSUE TITLE
Freeze on Forge Loading

### ISSUE THREAD

**Issue by Ferrocn** [CyclopsMC/EverlastingAbilities#70]
#### Description: 
Changing the config "ability_totem.totemCraftingCount" to 4, on reopen of the game Forge freezes while loading relating to: Forge Recipe registry.

#### Expected behaviour:
Relating to dynamic shapeless recipe for combining 3 (default) Ability Totems together.
Setting the config to 4 should allow four Ability Totems to be combined.

#### Actual behaviour:
Forge freezes while loading.

#### Steps to reproduce the problem:
1. Change the config file in game or out at: "ability_totem.totemCraftingCount" = 3
2. Change 3 to 4 - ( only value I have tested)
3. Close down Minecraft and Reopen
4. Observe Forge loading freeze near the end of its cycle
5. Consult the /logs/latest.log

____
#### Versions: 

- This mod: Everlasting Abilities 1.3.2 for MC 1.11.2
- CyclopsCore: 0.10.9 for 1.11.2
- Minecraft: 1.11.2
- Forge: 13.201.2516

**Comment by rubensworks** [comment]
Please include the crashlog.

**Comment by Ferrocn** [comment]
No problem. I didn't before because the 'latest.log' shows nothing to do with Everlasting Abilities..

[https://pastebin.com/5P21qV2d](url)

**Comment by rubensworks** [comment]
So it's not a crash, but a freeze.

I just tried it myself, and it loads just fine when I put this value on 4 (or any other value).
Another mod in your pack must be causing the problem.
Please let me know if you can reproduce it with any other mods installed.
