### ISSUE TITLE
Totem Crafting Bug

### ISSUE THREAD

**Issue by Jkosio23** [CyclopsMC/EverlastingAbilities#73]
#### Issue type:

- :bug: Bug
____
#### Short description:
AE2's Autocrafting doesn't trip the randomization feature

Here's a video of me replicating the bug.
https://vimeo.com/251077772

#### Versions:

- This mod: 1.3.6
- CyclopsCore: 0.10.23
- Minecraft: 1.12.2
- Forge: 14.23.1.2559

#### Log file:

https://pastebin.com/LKpmgVme

**Comment by rubensworks** [comment]
Everything looks fine on my end, reported it to the AE2 issue tracker. Let's follow the issue there.

**Comment by josephcsible** [comment]
Perhaps we could make recycling a totem deterministically make it into a "blank" one, then have the "blank" one set itself up and increment the seed when you try to use it.

**Comment by Jkosio23** [comment]
There would have to be different sets of seeds for the different totems having the chance to make a totem of a higher tier

**Comment by rubensworks** [comment]
@josephcsible I have no intention to make this recipe deterministic, plenty of mods out there that have non-deterministic recipe outputs (EvilCraft's Entangled Chalice to give one example). This is a bug in AE2, and if the authors don't acknowledge that, then I would advise players simply not to use AE2 for recycling totems.
