### ISSUE TITLE
Absorption duration bug

### ISSUE THREAD

**Issue by Fransango** [CyclopsMC/EverlastingAbilities#74]
#### Issue type: Bug

____
Absorption effect have a duration of 2s and a reuse of like 5s (3s without effect)

Please flix the duration time.

____
#### Versions:

Texted on curse version 1.10.2 and 1.12

____

If you can, please fix on all minecraft versions.

**Comment by brisingraerowing** [comment]
I just came here to report this as well.

**Comment by rubensworks** [comment]
I don't see a problem with the duration, the non-continuous effect is intended. In the past, this used to be too OP. (#20)
