### ISSUE TITLE
Effect feature(s) request

### ISSUE THREAD

**Issue by BitBork** [CyclopsMC/EverlastingAbilities#75]
:heavy_plus_sign: Feature request

 Hi there, I'd like to request some features to be added to this mod, if it's within the scope of it / if the
 author has the time.
____
Short description:
 - I'd very much like a feature where negative effects can be applied on the player too. *
 - The possibility to apply area-effects to be affecting the player only, or vice versa
   (player-only effects to be used in an area)

(* I'm combining this mod with 'JJ Races' [](https://minecraft.curseforge.com/projects/jj-races?gameCategorySlug=mc-mods&projectID=281490) , so that I can give each race abilities according to their physique eg. the 'elf' has speed & jump boost, 'kull' has strenght and slowness etc.)
____

**Comment by rubensworks** [comment]
Out of scope/time for me, but I'm happy to accept PRs.

**Comment by BitBork** [comment]
Has this request been considered at all since I posted it? You did say it is out of scope but did also add 'feature long-term'.
Edit: if not, would you allow me to try and find someone who would consider adding these features?

**Comment by rubensworks** [comment]
I don't have the bandwith to implement this myself unfortunately. But feel free to find someone that can submit a Pull Request for it.

**Comment by rubensworks** [comment]
Should be possible now with the datapack functionality.
