### ISSUE TITLE
Feature request. Disabling the particle effects showing rarity on mobs

### ISSUE THREAD

**Issue by mewzurui** [CyclopsMC/EverlastingAbilities#77]
:heavy_plus_sign: Can you please make a config option to turn off the particle effects on mobs. Or tell me the option because I am not seeing it.  I run with mods which add mobs and the particles everywhere are a bit annoying and I'm not seeing an option to remove the particles except on the player.

Thank you
~Mew

**Comment by rubensworks** [comment]
Sure, that's definitely possible.

**Comment by mewzurui** [comment]
Thank you ^_^
