### ISSUE TITLE
ItemStackMutableAbilityStore crash

### ISSUE THREAD

**Issue by DatrixTHLK** [CyclopsMC/EverlastingAbilities#78]
#### Issue type:

- :snail: Performance issue

#### Steps to reproduce the problem:

1. Go into the overworld
2. Fly around a little
3. Lag happens and world nearly stops loading or slows down
4. Unexpected Crash occurs
____
#### Versions:

- Everlasting Abilities:  1.3.2
- CyclopsCore: 0.10.9
- Minecraft: 1.11.2
- Forge: 13.20.1.2588

#### Report file: https://gist.github.com/DatrixTHLK/acd7bf377eea526020acbb632617f4e4

Thanks for at least taking a look at the issue. I really like this mod. Let me know if I've missed something.

**Comment by DatrixTHLK** [comment]
Right After I took out Battle Towers from the mod list I play with, the game no longer freezes up after a few minutes. I have referenced the same issue with @AtomicStryker so he can see the Log File and crash report. I'm not sure whether to close this or keep it open.

**Comment by rubensworks** [comment]
This issue has been resolved in 1.12 already. Unfortunately, 1.11 is not maintained anymore, sorry.

**Comment by DatrixTHLK** [comment]
Figures as much. I'm going to 1.12 soon anyway.

**Comment by DatrixTHLK** [comment]
Samething is happening in 1.12. I recently started up minecraft with the mods I use and yet once again I have the very same issue with 1.12 as I did in 1.11
forge: 1.12.2-14.23.2.2624
Everlasting Abilities: 1.3.10
Cyclops Core: 0.11.4

Crash Log: https://gist.github.com/DatrixTHLK/7688f31f04e773ad85da669a2355eb66
FML: https://gist.github.com/DatrixTHLK/faf7d38cd77885d79e67fbeaa0966e68

If this issue has been resolved already (which both crash report and Fml log show to the opposite) and 1.11 isn't being updated anymore than please explain to me why I'm getting the very same error with 1.12 that I was with 1,11?

**Comment by DatrixTHLK** [comment]
Minecraft: 1.12.2
Forge: 14.23.2.2629
CyclopsCore: 0.11.4-801
Everlasting Abilities: 1.3.11

Crash Report: https://gist.github.com/DatrixTHLK/99b21723f8e83faea25a97fab30fc0c4
FML Log: https://gist.github.com/DatrixTHLK/5b3320103774e54b0e28b1783e8ffba7

This is the same error that happened within 1.11 that is now happening in 1.12 and yes I do have the most recent version. Let me guess this has already been dealt with and a dev build is what I'll need to use instead of 1.3.11?

EDIT: I answered my own question on that last one. Nevermind...

**Comment by rubensworks** [comment]
That looks like a slightly different crashlog, but the same root-problem.

For some reason, the ability registry contains a `null` ability.

Did you by any chance disable any of the abilities?

What happens if you try opening the creative tab of this mod? Does it crash as well?

**Comment by DatrixTHLK** [comment]
None of the abilities are disabled within the config file.
Here is my config file: https://gist.github.com/DatrixTHLK/b227740770373c881eef26bde105b55e

I couldn't get into the creative tab fast enough before the game suddenly makes me fly through the air like super man and then my game continuously lags so badly that I can't even move. Latest dev build 1.3.11-143 is doing the same thing 1.3.11 is doing. 

I'm very confused by it. Within the game all mobs have their arms flailing (human-like ones anyways), The sky turns odd colors and water droplets become huge. Minecraft logo screen starts to spin out of control to the point I feel nauseous. I wish I could show you but unsure how to do that for the minecraft logo screen.

Here is what I mean by minecraft logo screen spinning out of control
http://tinypic.com/r/5yer1k/9 

**EDIT(9:01am):** I took out every mod I have and now the game logo isn't spinning out of control but I'm still testing out which mod is the cause. I'm getting closer to figuring out what mod it is though.

**EDIT(10:27am):** It was better fps for some reason. It's fixed now. At least that part is fixed. I'm going to try and figure out if I crash while going into creative tab with the newer version 1.3.11.

**EDIT(3:42pm):** Going into the creative tab for Everlasting Abilities caused no crash to occur.  The only thing I can think of is BetterFPS freaked out when I put it on Taylors Algorithm instead of Rivens "Full" Algorithm, and I'm still confused by why that would be. Oh well, it may happen again, but as of right now nothing is happening. Thanks at least for taking a look at the issue at hand.

**Comment by rubensworks** [comment]
Just released a new version. It will either fix this bug, or produce new useful debug output. So be sure to send me the logs again if it still crashes.

**Comment by DatrixTHLK** [comment]
Will do. Thanks again.
