### ISSUE TITLE
Blacklist for mobs dropping ability totems

### ISSUE THREAD

**Issue by brisingraerowing** [CyclopsMC/EverlastingAbilities#79]
#### Issue type:

_Only keep the issue types that are applicable._

- :heavy_plus_sign: Feature request

#### Description

I would like to have a blacklist / whitelist for mobs that can drop ability totems, to remove some from being able to (like Horses, Llamas, Villagers, and Chocobos (from ChocoCraft)). This would also be useful for pack makers, allowing them to, say, force combat to get these by blacklisting all passive mobs.

**Comment by rubensworks** [comment]
Sure, definitely possible to implement.

**Comment by UltraCyberGod** [comment]
I'd agree on this all those that are farming animals like us must have lots. We farm Pigs and chickens quite heavily at the moment and get a totem nearly every other day! Would it be possible to have a true/false for include/exclude Minecraft friendly mobs? Even if it's just vanilla mobs at first. I have to add though this is a top mod, well done!
