### ISSUE TITLE
Ability stuck in bottle

### ISSUE THREAD

**Issue by JFMillerUSA** [CyclopsMC/EverlastingAbilities#80]
Bug

I think I removed the Ability and found a new Totem 1/1 and added it, now can't remove it

- CyclopsCore: 1.12.2-0.11.1
- Minecraft: 1.12.2
- Forge: 14.23.2.2619

![2018-02-27_17 22 11](https://user-images.githubusercontent.com/9157611/36762869-dae64d86-1be2-11e8-92d0-1941daa272e5.png)

**Comment by rubensworks** [comment]
Invisibility has a max level of 1, which means that this is the stack limit in your bottle (and you already have one in there). You'll need another bottle to move that one in.

**Comment by JFMillerUSA** [comment]
It's in my bottle twice, BUG

**Comment by ImCrazyMan** [comment]
I'd just like to add that I had the same issue, and was going through here to submit a bug report if I didn't find anything. Any chance we could get some text somewhere letting us know the bottle inventories aren't per player? I thought I was gonna have to wipe my ability data

**Comment by 4rz0** [comment]
Interesting, I didn't know that.
I was about to report that as well. It's a weird design decision tbh.

**Comment by 4rz0** [comment]
If the enchantments are per bottle and not per player, how comes they work even if the bottle isn't on the player?
