### ISSUE TITLE
Step Height effect breaks stepping from paths to slabs / stairs

### ISSUE THREAD

**Issue by brisingraerowing** [CyclopsMC/EverlastingAbilities#81]
#### Issue type:

_Only keep the issue types that are applicable._

- :bug: Bug

____
#### Short description:

In the step height effect, you set the player step height to 0.5 by default. This is incorrect, as 1.8 changed it to 0.6. See [this wiki page](https://minecraft.gamepedia.com/Block#Block_height) for confirmation.

#### Expected behaviour:
Can step up from paths to stairs / slabs.

#### Actual behaviour:
Cannot step up from paths to stairs / slabs

#### Steps to reproduce the problem:

1. Make a path
2. Put a stair facing the path
3. Try to walk up the stairs
4. ...?
5. Can't step up.

____
#### Versions:

_Exact versions of the following mods, not just *latest*._

- This mod: 1.3.10
- CyclopsCore: 0.11.5
- Minecraft: 1.12.2 (likely affects all versions)
- Forge: 2624

#### Log file: N/A

**Comment by rubensworks** [comment]
Thanks, will look into it.

**Comment by rubensworks** [comment]
I'm not experiencing any problems with this myself. I'll set the default to `0.6` in any case.
