### ISSUE TITLE
Question: Overlay position

### ISSUE THREAD

**Issue by Bearorrism** [CyclopsMC/EverlastingAbilities#82]
Issue type: Question

I've been using Everlasting Abilities in the Sprout pack (1.9.4), and the abilities I've collected show as overlays when I go into the inventory menu, but not on the general screen.

Using the 1.12.2 in a new pack, the overlay for the abilities is on the general screen and can't be moved/hidden, which is interfering with other information overlays.

I've checked both config files to see if there are any settings I can steal from Sprout 1.9.4, but there doesn't seem to be, and I am just wondering if I've missed something, or if there is something I can add to the config to hide it.

**Comment by rubensworks** [comment]
The overlay you talk about is just the overlay from Vanilla's potion effects, this mod changes nothing to that. If you want to change that behaviour, you should look into finding mods that change Vanilla potion effect rendering (no idea if any of those exist though).
