### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Nexusdog** [CyclopsMC/EverlastingAbilities#84]
MC/F 1.12.2/2653

EA/CC 1.3.12/0.11.5

https://pastebin.com/buGb9E1R

Intermittent - ability bottle missing upon spawn
Irregular - crash to launcher

**
Unconfirmed/unknown - performance issues, freezing/locking, excessive loading times between menu screens.

**Comment by rubensworks** [comment]
Probably related to #83.

**Comment by rubensworks** [comment]
Should be fixed in 0bfd3c33694f039596a3e29cf12a5c388219639c
