### ISSUE TITLE
A Lot of Ability Totems in one chest

### ISSUE THREAD

**Issue by andr9528** [CyclopsMC/EverlastingAbilities#86]
#### Issue type:
🐛 
#### Short description:

Too many ability Totems in Nether Fortress Chest

#### Expected behaviour:

Maybe 1 or max 2 in one chest

#### Actual behaviour:

Completely or almost completely fills the chest with Ability Totems

Both pictures shows freshly found chests content
![image](https://user-images.githubusercontent.com/21788044/38453137-2b71000c-3a51-11e8-999a-a38094eb7d40.png)

![image](https://user-images.githubusercontent.com/21788044/38453140-36c1cd88-3a51-11e8-9fb4-e0a8ca4f1dfd.png)

#### Steps to reproduce the problem:

1. Instal the Versions
2. Boot up Minecraft
3. Go to Nether
4. Find Nether Fortress
5. Find chest within.
6. Look in chest
7. ???
8. Profit!

#### Versions:

- This mod: 1.12.2-1.3.12
- CyclopsCore: 1.12.2-0.11.5
- Minecraft: 1.12.2
- Forge: 14.23.2.2653

#### Log file: 

Here is the bottom half of the Lastest.log, the file is to large to pastebin it all, tell me if any other thing is needed. 
https://pastebin.com/w82Lb08Y

**Comment by rubensworks** [comment]
Hmm, that doesn't seem right indeed...

**Comment by andr9528** [comment]
You think? XD

**Comment by andr9528** [comment]
it is not only the Nether fortress, just found a normal dungeon with the same occurrence.

![image](https://user-images.githubusercontent.com/21788044/38453790-a0d19ad2-3a5b-11e8-8b9a-68d26170d11e.png)
![image](https://user-images.githubusercontent.com/21788044/38453797-b015f5ba-3a5b-11e8-94fd-062bf55d2bb8.png)

Something is forcing the chests to be full it would seem

**Comment by andr9528** [comment]
Stronghold does it too, and that even on the newer version of Everlasting Ability.
Version: 1.12.2-1.3.15

**Comment by andr9528** [comment]
Found a chest in the Stronghold which is spawning pseudo correctly.
![image](https://user-images.githubusercontent.com/21788044/38467982-0e8349c4-3b40-11e8-89c1-83c19c491632.png)

So not all loot tables are broken...

**Comment by rubensworks** [comment]
@andr9528 Can you check if you can reproduce this behaviour with only EA installed? It's possible that another mod is indeed forcing the chests to be completely full.

**Comment by andr9528** [comment]
With only EA and its core, a normal dungeon chest looks something like this,
![image](https://user-images.githubusercontent.com/21788044/38499452-e42a3fca-3c07-11e8-960e-84db133b9e3c.png)
![image](https://user-images.githubusercontent.com/21788044/38499482-fb59e95c-3c07-11e8-97ed-6edbf7dfcf9c.png)

Still quite a lot of items in these chests, but at least these aren't overflowing with ability totems, i have also found other dungeon that have way fewer items.
I will show pictures of chest from the other areas that i have previously shown to be messed up

Stronghold:
![image](https://user-images.githubusercontent.com/21788044/38499749-dba8c5b4-3c08-11e8-9dc3-3d3f1722e0a8.png)

Nether Fortress
![image](https://user-images.githubusercontent.com/21788044/38500085-afa0b534-3c09-11e8-8780-4dc80ae092d1.png)

it would seem that it is working as intended with only this mod, will try and add some of the other mods i have, which i think could be the culprit of this bug, now that we know it isn't this mod

**Comment by rubensworks** [comment]
Ok, thanks for checking. I'll leave this issue open for now, in case EA would somehow be triggering this behaviour in combination with some other mod.

**Comment by andr9528** [comment]
Tested a handful of mods, most of which generate some form of dungeons and are present in my map that is bugging out, but none of them caused the full loot chest bug while installed with EA.

List of mods Tested:
Botania - MegaLoot - Recurrent Complex - Rougelike Dungeons - Battle Towers - The Erebus

**Comment by rubensworks** [comment]
Note to self: this was a similar issue in EvilCraft, so let's fix it in the same way: https://github.com/CyclopsMC/EvilCraft/commit/a091b6ef0b782fcf56a32eb4b1bec1d3adfba2b2#diff-14c88c53a77052f23a4cabeffad78aa4
