### ISSUE TITLE
Graphic glitches & controls weirdness

### ISSUE THREAD

**Issue by Nexusdog** [CyclopsMC/EverlastingAbilities#89]
MC/F 1.12.2/2654
EverlastingAbilities-1.12.2-1.3.15

Title menu - background image flickering & jumping around
Villagers - legs jumping around
Torch flames - image stretched
Controls - super fast in random direction, no control

**1.3.14 roll back does not fix this issue**

**Comment by rubensworks** [comment]
I don't see what this has to do with EA. Can you reproduce this with just EA installed?

Please use the proper issue template in the future.

**Comment by Nexusdog** [comment]
Yeah, it's my fault - accept my apologies...
