### ISSUE TITLE
Searing Light passes through ( Caster )

### ISSUE THREAD

**Issue by Knito58** [CyclopsMC/EverlastingAbilities#90]
- :bug: Searing Light passes through mob without hitting it

#### Short description:

The yellow beam (Offensive Caster first spell) always hits when the target is still there on arrival. But the much better and faster searing light very often seems to pass through without harming. I cannot rely on it in short range battles in caves as the spell very often is just lost.

#### Expected behaviour:

Searing Light should always deal damage when it hits a target.

#### Actual behaviour:

Looks as if there were "spots of no light" where targets like skeletons or zombies fit in perfectly. Immobile targets can get hit on second or third try when moving one or two steps towards them. The searing light has a 50% chance to hit a skeleton on first try. (Not calculated - it feels like so)

This behaviour is constant since at least 3 EA versions. I also updated Forge to see if this was a problem. I remember a time when it was not a question if the searing light would deal damage. Maybe there was some optimizing to counter possible lag spikes?

#### Steps to reproduce the problem:

1. Become a caster.
2. Battle alot with searing light.
____
#### Versions:

- This mod: 1.12.2.-1.3.15 (and earlier)
- CyclopsCore:  1.12.2-0.11.5
- Minecraft:  1.12.2
- Forge: 14.23.2.2654 (and earlier)

**Comment by rubensworks** [comment]
Not sure what _Searing Light_ is, pretty sure it's not from this mod. (Unless I completely misunderstand your description)

**Comment by Knito58** [comment]
Ha! Thank you. Shame on me.
This one was for Angel of Vengeance.
Sorry.
