### ISSUE TITLE
Can't change maximum amount of abilities a player can have to infinity

### ISSUE THREAD

**Issue by espilsad** [CyclopsMC/EverlastingAbilities#91]
Hello,
I tried to change the maximum amount of abilities a player can have to -1 (~I also tried other values~ seems like I didn't try them properly) in the config file (/config/everlastingabilities.cfg), but I still can't use more than 5 totems. Is this a issue or am I doing something wrong?

Thanks

**Comment by rubensworks** [comment]
I assume you try to make the max number infinite? That's not supported at the moment, just make it a huge number for now.

**Comment by espilsad** [comment]
Thanks a lot, will try that

**Comment by espilsad** [comment]
I just want to add that every player has to change the number in their individual Mod Settings Menu for it to work
