### ISSUE TITLE
Abilities cause hunger?

### ISSUE THREAD

**Issue by Plurp13** [CyclopsMC/EverlastingAbilities#92]
#### Issue type:
- :question: Question

So I don't know if this is intended or not so I'll post it as a question. Is having abilities equipped supposed to make hunger go down faster? I almost starved to death because I walked away from the computer while standing in my base with my inventory open aka doing nothing. This seems strange but I don't know if it's wrong or not. I'm in minecraft 1.12.2 with what I think is the latest version, I added it yesterday or the day before.

**Comment by rubensworks** [comment]
Yes, that's correct. There's a config option for it though: `exhaustionPerAbilityTick`

**Comment by Plurp13** [comment]
Aha! Wonderful, thank you ^.^
