### ISSUE TITLE
Option to disable abilities effect towards mobs from an enitre mod

### ISSUE THREAD

**Issue by zezreli** [CyclopsMC/EverlastingAbilities#93]
- :question: So i have been using everlasting abilities for awhile and another mod called minecolonies, the problem I'm having is that the abilities like wither and poison and the other harmfull effects hurt the mobs from that mod and they have to many veriants to disable one by one, so is there a possibility to add an option to disable abilities towards an entire mod?

**Comment by rubensworks** [comment]
Should definitely be possible to implement.

**Comment by zezreli** [comment]
Amazing thank you very much.
