### ISSUE TITLE
Abilities that grant potion effects stopped working

### ISSUE THREAD

**Issue by MindCaged** [CyclopsMC/EverlastingAbilities#95]
Okay, I don't know what got corrupted in my worlds, but while the flight ability still works, it seems any ability that grants potion effects no longer grants those potions effects. I've tried everything I can think of, but nothing seems to fix it besides starting a whole new world. I've tried removing all mods besides cyclops core and everlasting abilities and it still refuses to work.

EverlastingAbilities-1.12.2-1.3.16
CyclopsCore-1.12.2.0.11.6

Minecraft 1.12.2

Forge-14.23.4.2730

Attached is a test world I had where it stopped working, I've removed all mods besides Everlasting Abilities, Cyclops Core, and JEI. I'd love to know if there's some way of fixing it with an NBT editor or something, or if I'm doomed to either not use EA any further in my main world, or have to start a whole new one if I want to use it, and I suppose for that matter risk it happening again since I'm really not sure what caused it in the first place. Since it might play a role, I did have NotEnoughIDs installed, along with almost 300 other mods, but since it doesn't work even /after/ I disable those mods I figure it has to have changed

 something in the world itself in nbt or something, and at least if I can figure out what that is, I might be able to fix it in an editor. I've tried deleting dimensions, deleting the overworld, deleting a bunch of the player nbt. Nothing seems to get it to work again.

OK, I've tried deleting everything in the save folder besides level.dat, and I even used a nbt editor to delete the player data there, and it /still/ doesn't work.

[Test World 2.zip](https://github.com/CyclopsMC/EverlastingAbilities/files/2178059/Test.World.2.zip)

**Comment by rubensworks** [comment]
Which abilities exactly stop working? What happens vs what you expect to happen.

In the future I would appreciate it if you would follow the issue template btw.

**Comment by MindCaged** [comment]
Sorry about that. There's no error message or crash, the potion effects and abilities simply don't work. I've tried the following in the test world I uploaded:
Dont Work:  
 Resistance, Speed, Water Breathing, Slowness, Night Vision, Absorbtion, Saturation, Power Stare, Strength, Glowing, Levitation, Fire Resistance, Haste, Jump Boost, Wither, Poison, Regeneration, Invisibility, Bonemealer.

Does Work:
  Flight, Magnetize, Step Assist.

So basically, all potion based abilities have stopped working either on the player or on mobs. Some of the ones on mobs are hard to test if they're working besides looking for potion effects, but the ones which should have an easily noticable effect don't seem to work. There's no potion indicator in the inventory, and the effect doesn't happen. Speed doesn't speed me up, jump boost doesn't change my jump height, etc. And no potion particles.

Again, if I start a whole new world everything seems to work fine, but in the world I uploaded, almost nothing does. So it's something in the level.dat that I uploaded Perhaps something is registered wrong somehow. Not sure how that happened unless some other mod did it, but if i don't know what's wrong I can't even try to fix it with an nbt editor. Also not sure why the ids or whatever would have changed in an existing world. The test world isn't important, the problem is it happened in my main world too.

Ok, I think I found something that seems to have fixed it in my test world, though it's rather dangerous I think. I regenerated the world, then copies that level.dat into my 'corrupted' world, and now everlasting abilities seems to work. Not sure if that might screw up something else, but I might try that with my main world(after backing up of course).

**Comment by MindCaged** [comment]
Okay, was able to find a level.dat from 3 backups ago where EA still works, then copied the player data with an nbt data editor so I didn't lose anything I think, not sure what happened to the level.dat, maybe it didn't get saved properly, somehow it got corrupted, and also my test world.... Some other mod must've done it, but not sure which one.
