### ISSUE TITLE
potion effects blinkes.

### ISSUE THREAD

**Issue by matyklug18** [CyclopsMC/EverlastingAbilities#98]
#### Issue type:

- :bug: Bug

____

#### Short description:

almoust all potions sometimes run out for short time and then it work again. also FOV blinks. 

#### Steps to reproduce the problem:

1. Monk lvl 20
2. Matter Overdrive: become android and upgrade everything to max
3. put on all upgrades from Cyberware
4. level up all skills from Levels

#### Expected behaviour:

all effects should be consistent and do not flash

____

#### Versions:

- This mod: 1.3.17
- Minecraft: 1.12.2
- Forge: 14.23.4.2757

#### Other mods:
Cyberware
Monk
Matter overdrive
level up
jei
this mod
ReWIRED

**Comment by matyklug18** [comment]
and step assist do not work.

**Comment by rubensworks** [comment]
Please try reproducing without any other mods installed. Because it sounds like this is a mod incompatibility.
