### ISSUE TITLE
Can duplicate abilities on server

### ISSUE THREAD

**Issue by Bahnschrift** [CyclopsMC/EverlastingAbilities#99]
#### Issue type:

- :bug: 

____

#### Short description:

You can duplicate abilities that you already have if you are on a server (might work singleplayer, haven't tested)

#### Steps to reproduce the problem:

1. Obtain multiple abilities, and move them all to one ability bottle
2. Spam click the button to move abilities from the bottle to your player

#### Expected behaviour:

I expect the abilities not not duplicate? What am I supposed to put here?

____

#### Versions:

- This mod: 1.12.2-1.3.17
- Minecraft: 1.12.2 
- Forge: 2730

**Comment by rubensworks** [comment]
Are the duplicates persistent? Do they stay there after closing/reopening the bottle gui?

**Comment by Bahnschrift** [comment]
They do. They last permanently and do not remove themselves even after relogging.

**Comment by rubensworks** [comment]
Then it sounds like there is a server-check missing, thanks for reporting!

**Comment by Bahnschrift** [comment]
No problem. Thanks for getting back so fast!
